/* =====================================================================
   data.js  —  THE ONLY FILE YOU NEED TO EDIT TO ADD QUESTIONS
   ---------------------------------------------------------------------
   HOW TO ADD A NEW SET (copy-paste steps):
   1. Scroll to the bottom of this file, find the line that says: ADD NEW SETS ABOVE THIS LINE
   2. Paste a new block just above it, like this:

      {
        set: "SET-10",
        questions: [
          { n: 1, sec: "Modern History", q: "Question text?",
            o: ["Option A", "Option B", "Option C", "Option D"],
            a: "B",                       // correct answer letter: A, B, C or D
            e: "Explanation text." },
          { n: 2, ... },
        ]
      },

   FIELDS
     n    = original question number in that set (do not change it)
     sec  = ONE of the 14 section names listed in "sections" below (copy exactly)
     q    = question text
     o    = four options, in the original order (without the (A) (B) letters)
     a    = correct option letter "A" / "B" / "C" / "D"
     e    = explanation (optional)
     d    = difficulty "Easy" / "Medium" / "Hard" (optional)
     flag = optional note shown in review, e.g. "Answer may be outdated"

   The app builds every index, count, card and test from this file.
   Nothing else needs to change.
   ===================================================================== */

window.QUIZ_DATA = {

  appTitle: "Wise Choice Mock Tests",

  // Used by the validation panel (Settings → Developer mode)
  expectedSets: 15,
  expectedPerSet: 100,

  // The 14 sections. Every question's "sec" must match one of these exactly.
  sections: [
    "Ancient History",
    "Medieval History",
    "Modern History",
    "Indian Geography",
    "West Bengal Geography",
    "Arts and Culture",
    "Indian Polity",
    "Indian Economy",
    "Physics",
    "Chemistry",
    "Biology",
    "Static GK",
    "Current Affairs",
    "Aptitude & Mental Ability"
  ],

  sets: [

    /* ------------------------------------------------------------------
       SET-08  (Miscellaneous Studies Mock Test – 08)
       Source file was cut off after Q56 — Q57 onward still to be added.
       ------------------------------------------------------------------ */
    {
      set: "SET-08",
      questions: [
        { n: 1, sec: "Ancient History", q: "Which event related to the life of Lord Buddha is known as “Mahabhinishkramana”?",
          o: ["His birth", "His renunciation of home", "His attainment of enlightenment", "His demise (passing away)"], a: "B",
          e: "In Buddhist traditions, Siddhartha Gautama's departure from his palace and worldly life at the age of 29 is known as Mahabhinishkramana. His passing away is referred to as Mahaparinirvana." },
        { n: 2, sec: "Ancient History", q: "Who was the first to decipher the rock edicts of Emperor Ashoka?",
          o: ["Alexander Cunningham", "James Prinsep", "William Jones", "John Marshall"], a: "B",
          e: "In 1837, James Prinsep, an officer of the East India Company, deciphered the Brahmi and Kharosthi scripts used in Emperor Ashoka's royal edicts." },
        { n: 3, sec: "Ancient History", q: "Between which two rivers was Taxila University located?",
          o: ["Indus and Jhelum", "Jhelum and Chenab", "Chenab and Ravi", "Indus and Saraswati"], a: "A",
          e: "Taxila, an ancient center of higher learning (now in Pakistan), was situated between the Indus and Jhelum (Hydaspes) rivers." },
        { n: 4, sec: "Medieval History", q: "Which Sultan of Delhi established a separate Employment Bureau for the welfare of citizens?",
          o: ["Alauddin Khalji", "Muhammad bin Tughluq", "Firoz Shah Tughlaq", "Ghiyasuddin Balban"], a: "C",
          e: "Firoz Shah Tughlaq set up an employment bureau to help alleviate unemployment, along with charitable institutions like Dar-ul-Shafa (hospitals) and Diwan-i-Khairat (charity department)." },
        { n: 5, sec: "Medieval History", q: "During the Mughal period, which royal order or decree was termed “Nishan”?",
          o: ["An order issued directly by the Emperor", "A directive issued by the Wazir/Prime Minister", "An order bearing the seal of a Prince or Begum of the royal family", "An order issued by a provincial Governor"], a: "C",
          e: "While an executive decree directly from the Emperor was called a Farman, an official directive or charter issued by Mughal princes or female royals was known as a Nishan." },
        { n: 6, sec: "Modern History", q: "Who was the Prime Minister of Britain during the Battle of Plassey (1757)?",
          o: ["Robert Walpole", "William Pitt (The Elder)", "Duke of Newcastle", "Lord North"], a: "C",
          e: "Thomas Pelham-Holles, 1st Duke of Newcastle, was serving as the British Prime Minister during the Battle of Plassey in 1757." },
        { n: 7, sec: "Modern History", q: "Who first described the Revolt of 1857 as the “First War of Indian Independence”?",
          o: ["R. C. Majumdar", "Vinayak Damodar Savarkar", "Sir Syed Ahmad Khan", "Jawaharlal Nehru"], a: "B",
          e: "V. D. Savarkar characterized the uprising as a planned national rebellion in his 1909 book The Indian War of Independence 1857." },
        { n: 8, sec: "Modern History", q: "What official reason did Lord Curzon state for the Partition of Bengal in 1905?",
          o: ["To curb the political influence of Hindus", "To create a separate state for Muslims", "Administrative convenience and easing the governance of an oversized province", "To suppress nationalist movements"], a: "C",
          e: "Although the true motive was a “divide and rule” strategy to weaken Indian nationalism, the official British stance cited the vast size and administrative burden of the Bengal Presidency." },
        { n: 9, sec: "Modern History", q: "What was the main significance of the historic Lucknow Pact of 1916?",
          o: ["Demanding complete independence (Purna Swaraj) for India", "Political agreement between Congress and the Muslim League, and reunion of Moderates and Extremists", "Reversal of the partition of Bengal", "Supporting the Khilafat Movement"], a: "B",
          e: "Presided over by Ambica Charan Mazumdar, the session facilitated a formal pact between the Indian National Congress and the Muslim League, while also reuniting the Moderates and Extremists who had split at Surat in 1907." },
        { n: 10, sec: "Modern History", q: "What was the primary reason for the withdrawal of the Non-Cooperation Movement in 1922?",
          o: ["Repressive policies of the British Government", "Arrest of Jawaharlal Nehru and Subhash Chandra Bose", "Violent incident at Chauri Chaura", "Abolition of the Rowlatt Act"], a: "C",
          e: "On February 5, 1922, a crowd set fire to a police station at Chauri Chaura (Gorakhpur, UP), leading to the death of 22 policemen. Mahatma Gandhi called off the movement because it violated his fundamental principle of non-violence." },
        { n: 11, sec: "Modern History", q: "Who termed the proposals of the Cripps Mission (1942) as “A post-dated cheque on a crashing bank”?",
          o: ["Jawaharlal Nehru", "Mahatma Gandhi", "Muhammad Ali Jinnah", "Subhash Chandra Bose"], a: "B",
          e: "Gandhi criticized Sir Stafford Cripps’ offer of post-war Dominion status due to growing distrust in British intentions and their deteriorating wartime position." },
        { n: 12, sec: "Modern History", q: "When was the Indian Independence Act passed by the British Parliament?",
          o: ["3rd June, 1947", "4th July, 1947", "18th July, 1947", "15th August, 1947"], a: "C",
          e: "Introduced on July 4, 1947, based on the Mountbatten Plan, the bill received Royal Assent on July 18, 1947." },
        { n: 13, sec: "Indian Geography", q: "Which of the following mountain ranges belongs to the “Himachal” or Lesser/Middle Himalayas?",
          o: ["K2", "Pir Panjal", "Zaskar", "Dhaulagiri"], a: "B",
          e: "Pir Panjal, Dhauladhar, and Mahabharat Lekh are major ranges of the Middle Himalayas (Himachal). K2 belongs to the Karakoram, and Zaskar is part of the Trans-Himalayan system." },
        { n: 14, sec: "Indian Geography", q: "Where is India’s only active volcano, “Barren Island”, located?",
          o: ["Lakshadweep", "Nicobar Islands", "Middle Andaman (Andaman Sea)", "Great Nicobar"], a: "C",
          e: "Barren Island is situated in the Andaman Sea, northeast of Port Blair (east of the Middle Andaman group), and is the only active volcano in South Asia." },
        { n: 15, sec: "Indian Geography", q: "Which river flows through a rift valley and serves as the lifeline of the “Ruhr of India” region?",
          o: ["Godavari", "Damodar", "Narmada", "Mahanadi"], a: "B",
          e: "Due to its rich mineral and coal belt, the Damodar Valley (Asansol-Durgapur region) is called the “Ruhr of India,” and the river flows through a faulted rift valley." },
        { n: 16, sec: "Indian Geography", q: "What mineral gives the black (Regur) soil of the Deccan plateau its high water-holding capacity?",
          o: ["Illite", "Kyanite", "Montmorillonite", "Gibbsite"], a: "C",
          e: "The clay mineral montmorillonite expands significantly upon absorbing moisture, making the soil sticky when wet and causing deep fissures upon drying, which aids moisture retention." },
        { n: 17, sec: "Indian Geography", q: "Which is the first Multipurpose River Valley Project of independent India?",
          o: ["Bhakra Nangal Project", "Hirakud Project", "Damodar Valley Corporation (DVC)", "Chambal Valley Project"], a: "C",
          e: "Established in 1948 modeled on the Tennessee Valley Authority (TVA) of the USA, DVC was India's first multipurpose river basin initiative." },
        { n: 18, sec: "Indian Geography", q: "In which layer of the atmosphere do meteors burn up upon entering?",
          o: ["Stratosphere", "Mesosphere", "Thermosphere", "Exosphere"], a: "B",
          e: "The mesosphere is the coldest atmospheric layer (around -100°C), where incoming meteoroids experience high frictional heating and burn away." },
        { n: 19, sec: "Indian Geography", q: "Among greenhouse gases, which one has the highest Global Warming Potential (GWP)?",
          o: ["Carbon dioxide (CO₂)", "Methane (CH₄)", "Nitrous oxide (N₂O)", "Sulfur hexafluoride (SF₆)"], a: "D",
          e: "While CO₂ contributes most by overall volume, SF₆ has a Global Warming Potential roughly 23,500 times greater than CO₂ molecule-for-molecule over a 100-year timescale." },
        { n: 20, sec: "Indian Geography", q: "Which is the largest Biosphere Reserve in India by area?",
          o: ["Sundarbans", "Gulf of Mannar", "Rann of Kutch", "Nilgiri"], a: "C",
          e: "The Great Rann of Kutch in Gujarat is India's largest biosphere reserve by geographic coverage. The Gulf of Mannar is second, and Nilgiri was India's first designated biosphere reserve in 1986." },
        { n: 21, sec: "Biology", q: "Which component becomes severely depleted in a water body as a consequence of Eutrophication?",
          o: ["Nitrate", "Phosphate", "Dissolved Oxygen (DO)", "Carbon dioxide"], a: "C",
          e: "Agricultural runoff rich in nitrates/phosphates triggers rapid algal blooms. When the algae die, decomposing bacteria consume the available Dissolved Oxygen, creating hypoxic dead zones." },
        { n: 22, sec: "Arts and Culture", q: "How many UNESCO World Heritage Sites are currently in India?",
          o: ["40", "42", "43", "45"], a: "C",
          e: "India has 43 recognized sites, with Assam’s Moidams – the Mound-Burial System of the Ahom Dynasty being inscribed as the 43rd site.",
          flag: "Count changes over time — India's total has risen since this set was written. Verify before relying on it." },
        { n: 23, sec: "Physics", q: "On which optical principle does an Optical Fiber work?",
          o: ["Refraction of light", "Dispersion of light", "Total Internal Reflection", "Polarization of light"], a: "C",
          e: "Light signals travel through the glass/plastic core by repeatedly undergoing total internal reflection whenever the incident angle exceeds the critical angle." },
        { n: 24, sec: "Physics", q: "What is the SI unit of the Power of a Lens?",
          o: ["Watt", "Candela", "Dioptre", "Lumen"], a: "C",
          e: "The power of a lens is the reciprocal of its focal length in meters (P = 1/f), measured in dioptres (D)." },
        { n: 25, sec: "Physics", q: "What happens to the surface tension of water when soap or detergent is added?",
          o: ["Surface tension increases", "Surface tension decreases", "Remains unchanged", "First increases, then decreases"], a: "B",
          e: "Surfactants disrupt cohesive hydrogen bonding among water molecules, lowering surface tension and improving its ability to penetrate cloth fibers." },
        { n: 26, sec: "Chemistry", q: "In which group of the modern periodic table are the Halogens located?",
          o: ["Group 15", "Group 16", "Group 17", "Group 18"], a: "C",
          e: "Group 17 contains fluorine (F), chlorine (Cl), bromine (Br), iodine (I), and astatine (At). Group 18 houses the noble gases." },
        { n: 27, sec: "Chemistry", q: "Bronze is an alloy composed primarily of which metals?",
          o: ["Copper and Zinc", "Copper and Tin", "Copper and Nickel", "Zinc and Lead"], a: "B",
          e: "Bronze typically consists of ~88% copper and ~12% tin. An alloy of copper and zinc forms brass." },
        { n: 28, sec: "Physics", q: "When an alpha (α) particle is emitted from a radioactive nucleus, how does its atomic number change?",
          o: ["Decreases by 2 units", "Decreases by 4 units", "Increases by 1 unit", "Does not change"], a: "A",
          e: "An alpha particle is a helium nucleus (⁴₂He). Emitting it reduces mass number by 4 and decreases atomic number (Z) by 2." },
        { n: 29, sec: "Biology", q: "Which cell organelle is known as the “Suicidal Bag” of the cell?",
          o: ["Mitochondria", "Golgi Apparatus", "Lysosome", "Ribosome"], a: "C",
          e: "Lysosomes contain hydrolytic digestive enzymes. If damaged or malfunctioning, they burst and autolyze their own host cell." },
        { n: 30, sec: "Biology", q: "Which protein present in blood plasma directly participates in blood clotting?",
          o: ["Albumin", "Globulin", "Fibrinogen", "Hemoglobin"], a: "C",
          e: "Fibrinogen is converted into insoluble fibrin strands by thrombin during vascular injury to form a blood clot." },
        { n: 31, sec: "Biology", q: "Which hormone regulates calcium levels in the human bloodstream?",
          o: ["Thyroxine", "Parathormone (PTH)", "Insulin", "Melatonin"], a: "B",
          e: "Parathyroid hormone (PTH) elevates blood calcium levels, balancing calcitonin (secreted by the thyroid), which lowers blood calcium." },
        { n: 32, sec: "Biology", q: "What is the primary function of Phloem tissue in plants?",
          o: ["Transporting water and mineral salts from roots to leaves", "Translocating synthesized food from leaves to various plant organs", "Providing only mechanical support to the plant", "Storing metabolic waste materials"], a: "B",
          e: "Xylem carries water and minerals upwards from roots, whereas phloem carries photosynthetic products bidirectionally throughout the plant." },
        { n: 33, sec: "Biology", q: "Who is known as the “Father of Genetics”?",
          o: ["Charles Darwin", "Gregor Johann Mendel", "Louis Pasteur", "Thomas Hunt Morgan"], a: "B",
          e: "Mendel formulated the fundamental laws of inheritance (law of segregation and independent assortment) through hybridization experiments on garden pea plants." },
        { n: 34, sec: "Biology", q: "The human body has 46 chromosomes. How many of these are Autosomes?",
          o: ["44", "46", "2", "22"], a: "A",
          e: "Humans have 23 pairs (46 total) of chromosomes: 22 pairs (44 chromosomes) are autosomes, and 1 pair (2 chromosomes, XX or XY) are allosomes (sex chromosomes)." },
        { n: 35, sec: "Static GK", q: "“Cache Memory” in a computer acts as a high-speed buffer between which two components?",
          o: ["RAM and Hard Disk", "CPU and RAM", "CPU and ROM", "Hard Disk and Pen Drive"], a: "B",
          e: "Cache memory provides ultra-fast temporary storage located between the CPU and system RAM to minimize access latency for frequently used instructions." },
        { n: 36, sec: "Static GK", q: "An Operating System (OS) is an example of which type of software?",
          o: ["Application Software", "System Software", "Utility Software", "Malware"], a: "B",
          e: "An OS serves as interface-level system software controlling underlying hardware and executing application programs." },
        { n: 37, sec: "Static GK", q: "How many bits make up an address in Internet Protocol version 4 (IPv4)?",
          o: ["16 bits", "32 bits", "64 bits", "128 bits"], a: "B",
          e: "IPv4 addresses consist of 32 bits grouped into four 8-bit octets (e.g., 192.168.1.1). IPv6 addresses are 128 bits wide." },
        { n: 38, sec: "Static GK", q: "What is an error or flaw in a computer program that produces an unintended or incorrect result called?",
          o: ["Bug", "Spam", "Virus", "Cookie"], a: "A",
          e: "A coding fault causing software failures is known as a bug, and resolving these faults is known as debugging." },
        { n: 39, sec: "Static GK", q: "Which of the following is an open-source operating system?",
          o: ["MS Windows", "macOS", "Linux", "iOS"], a: "C",
          e: "The source code of Linux is freely accessible, modifiable, and distributable under open-source licensing, whereas Windows and macOS/iOS are proprietary systems." },
        { n: 40, sec: "Arts and Culture", q: "The classical dance form “Kuchipudi” originated from which Indian state?",
          o: ["Tamil Nadu", "Kerala", "Andhra Pradesh", "Karnataka"], a: "C",
          e: "Kuchipudi traces its origin to the village of Kuchelapuram in Andhra Pradesh's Krishna district. Bharatanatyam belongs to Tamil Nadu." },
        { n: 41, sec: "Arts and Culture", q: "Ustad Amjad Ali Khan is renowned worldwide for playing which musical instrument?",
          o: ["Sitar", "Sarod", "Santoor", "Shehnai"], a: "B",
          e: "Amjad Ali Khan is an acclaimed Indian classical sarod maestro. Pandit Shivkumar Sharma was famous for the santoor." },
        { n: 42, sec: "Static GK", q: "From which city is the Nobel Peace Prize awarded each year?",
          o: ["Stockholm (Sweden)", "Oslo (Norway)", "Geneva (Switzerland)", "New York (USA)"], a: "B",
          e: "While the other Nobel prizes are presented in Stockholm, Alfred Nobel specified that the Peace Prize be awarded in Oslo, Norway." },
        { n: 43, sec: "Static GK", q: "Who was the first Indian recipient of the Ramon Magsaysay Award?",
          o: ["Acharya Vinoba Bhave", "Mother Teresa", "Satyajit Ray", "Kiran Bedi"], a: "A",
          e: "In 1958, Bhoodan Movement leader Vinoba Bhave became the inaugural Indian laureate of this honor." },
        { n: 44, sec: "Static GK", q: "Where is the headquarters of the International Labour Organization (ILO) located?",
          o: ["Paris", "London", "Geneva", "Vienna"], a: "C",
          e: "Geneva, Switzerland hosts the headquarters of the ILO, WHO, and WTO." },
        { n: 45, sec: "Static GK", q: "In which city is the headquarters of the European Union (EU) situated?",
          o: ["Paris (France)", "Brussels (Belgium)", "Berlin (Germany)", "Rome (Italy)"], a: "B",
          e: "Brussels serves as the de facto capital of the EU and hosts the headquarters of NATO." },
        { n: 46, sec: "Current Affairs", q: "Olaf Scholz is the Chancellor of which country?",
          o: ["Austria", "Germany", "France", "Netherlands"], a: "B",
          e: "Olaf Scholz assumed office as Chancellor of Germany in December 2021, succeeding Angela Merkel.",
          flag: "Outdated — Olaf Scholz is no longer Chancellor. The country (Germany) is still the expected exam answer." },
        { n: 47, sec: "Static GK", q: "What is the currency of South Africa?",
          o: ["Rial", "Rand", "Dinar", "Shilling"], a: "B",
          e: "South Africa's currency is the South African Rand (ZAR)." },
        { n: 48, sec: "Static GK", q: "Where is the Central Potato Research Institute (CPRI) located in India?",
          o: ["Cuttack", "Shimla", "Dehradun", "Nagpur"], a: "B",
          e: "The Central Potato Research Institute is located at Kufri, Shimla (Himachal Pradesh)." },
        { n: 49, sec: "Modern History", q: "Who founded the Arya Samaj?",
          o: ["Raja Ram Mohan Roy", "Swami Dayananda Saraswati", "Swami Vivekananda", "Atmaram Pandurang"], a: "B",
          e: "Swami Dayananda Saraswati established the Arya Samaj in Bombay in 1875, popularizing the call “Go back to the Vedas”." },
        { n: 50, sec: "Static GK", q: "When is “National Science Day” observed annually in India?",
          o: ["12th January", "28th February", "29th August", "23rd December"], a: "B",
          e: "February 28 commemorates Sir C.V. Raman's discovery of the “Raman Effect” in 1928, which won him the Nobel Prize in Physics in 1930." },
        { n: 51, sec: "Static GK", q: "In which year were the modern Olympic Games revived?",
          o: ["1896", "1900", "1904", "1924"], a: "A",
          e: "The first modern Olympic Games were held in Athens, Greece, in 1896 through the initiative of Baron Pierre de Coubertin." },
        { n: 52, sec: "Static GK", q: "The “Thomas Cup” is associated with which sport?",
          o: ["Football", "Lawn Tennis", "Men's Badminton", "Table Tennis"], a: "C",
          e: "The Thomas Cup represents the World Men's Team Badminton Championship. Its female equivalent is the Uber Cup." },
        { n: 53, sec: "Static GK", q: "Who authored the famous book “The Discovery of India”?",
          o: ["Mahatma Gandhi", "Jawaharlal Nehru", "Bal Gangadhar Tilak", "Dr. B. R. Ambedkar"], a: "B",
          e: "Nehru wrote the book during his imprisonment at Ahmednagar Fort (1942–1946) during the Quit India movement." },
        { n: 54, sec: "Arts and Culture", q: "Which is the highest literary award in India?",
          o: ["Sahitya Akademi Award", "Vyas Samman", "Jnanpith Award", "Saraswati Samman"], a: "C",
          e: "Established in 1961, the Jnanpith Award is India's highest civilian literary honour. Malayalam poet G. Sankara Kurup was its first recipient." },
        { n: 55, sec: "Static GK", q: "Which city is famously known as the “City of Lakes” in India?",
          o: ["Jaipur", "Udaipur", "Nainital", "Srinagar"], a: "B",
          e: "Udaipur, Rajasthan, is surrounded by major artificial and natural lakes (Pichola, Fateh Sagar, etc.) and is called the “City of Lakes” or “Venice of the East”." },
        { n: 56, sec: "Static GK", q: "Which state is referred to as the “Spice Garden of India”?",
          o: ["Karnataka", "Kerala", "Andhra Pradesh", "Tamil Nadu"], a: "B",
          e: "Kerala is known as the “Spice Garden of India” for its longstanding production of pepper, cardamom, clove, and cinnamon." }
      ]
    },

    /* ------------------------------------------------------------------
       SET-09  ⚠ CHECK THIS LABEL
       The second file you shared had no title / set number, so it is
       filed here as "SET-09" only as a placeholder. If it belongs to a
       different set, change the two words  "SET-09"  below (just the
       name on the line under this comment). Cut off after Q53.
       ------------------------------------------------------------------ */
    {
      set: "SET-09",
      questions: [
        { n: 1, sec: "Ancient History", q: "Which of the following pairs is not correct (Mahajanapada and its Capital)?",
          o: ["Anga – Champa", "Vatsa – Kaushambi", "Matsya – Viratanagara", "Asmaka – Suktimati"], a: "D",
          e: "The capital of Asmaka (or Assaka) Mahajanapada was Podana or Potali (the only Mahajanapada located in South India). Suktimati was the capital of the Chedi Mahajanapada. All other pairs are correct." },
        { n: 2, sec: "Ancient History", q: "In which Major Rock Edict of Ashoka are the horrors of the Kalinga War and his remorse described?",
          o: ["5th Rock Edict", "10th Rock Edict", "11th Rock Edict", "13th Major Rock Edict"], a: "D",
          e: "Ashoka's Major Rock Edict XIII describes the Kalinga War fought in 261 BCE and narrates his profound transformation from ‘Chandashoka’ to ‘Dharmashoka’." },
        { n: 3, sec: "Ancient History", q: "Which book was authored by Varahamihira, the famous astronomer of the Gupta era?",
          o: ["Aryabhatiya", "Panchasiddhantika", "Brahmasphutasiddhanta", "Suryasiddhanta"], a: "B",
          e: "Varahamihira was one of the Navaratnas of the Gupta court. His major works include Panchasiddhantika and Brihat Samhita. Aryabhatiya was written by Aryabhata." },
        { n: 4, sec: "Medieval History", q: "Which Sultan of Delhi was the first to establish a permanent standing army and introduce the practice of paying cash salaries to soldiers?",
          o: ["Iltutmish", "Balban", "Alauddin Khalji", "Muhammad bin Tughluq"], a: "C",
          e: "Alauddin Khalji ended the Iqta system for soldiers and began paying them cash salaries directly from the state treasury. He also introduced the systems of Dagh (branding of horses) and Huliya (descriptive roll of soldiers) to prevent corruption." },
        { n: 5, sec: "Medieval History", q: "Krishnadeva Raya, the greatest ruler of the Vijayanagara Empire, belonged to which dynasty?",
          o: ["Sangama Dynasty", "Saluva Dynasty", "Tuluva Dynasty", "Aravidu Dynasty"], a: "C",
          e: "Krishnadeva Raya was the third and most powerful ruler of the Tuluva Dynasty. His reign is regarded as the golden age of Telugu literature." },
        { n: 6, sec: "Medieval History", q: "Which Sikh Guru was executed by the Mughal Emperor Jahangir?",
          o: ["Guru Arjan Dev", "Guru Tegh Bahadur", "Guru Hargobind", "Guru Gobind Singh"], a: "A",
          e: "In 1606, Jahangir executed the 5th Sikh Guru, Guru Arjan Dev, for aiding his rebel son Khusrau. The 9th Sikh Guru, Guru Tegh Bahadur, was executed by Aurangzeb." },
        { n: 7, sec: "Modern History", q: "Who among the following was NOT an initial member of the Governor-General’s Council formed under the Regulating Act of 1773?",
          o: ["Philip Francis", "John Clavering", "Richard Barwell", "Charles Wood"], a: "D",
          e: "The four council members serving alongside Governor-General Warren Hastings were Philip Francis, John Clavering, George Monson, and Richard Barwell. Charles Wood was associated with the Wood's Despatch of 1854." },
        { n: 8, sec: "Modern History", q: "Lord Curzon formally implemented the Partition of Bengal on October 16, 1905. At whose call did Bengalis observe this day as ‘Raksha Bandhan Day’?",
          o: ["Surendranath Banerjee", "Rabindranath Tagore", "Ramendra Sundar Tribedi", "Ananda Mohan Bose"], a: "B",
          e: "To foster communal harmony and solidarity between Hindus and Muslims, Rakhi Bandhan was observed across Bengal upon the call of Rabindranath Tagore." },
        { n: 9, sec: "Modern History", q: "In which special session of the Indian National Congress was the resolution of the Non-Cooperation Movement of 1920 first adopted?",
          o: ["Nagpur Session", "Calcutta Special Session", "Bombay Session chaired by Lala Lajpat Rai", "Lahore Session"], a: "B",
          e: "In September 1920, the resolution for the Non-Cooperation Movement was initially adopted at the Special Session in Calcutta presided over by Lala Lajpat Rai. It received formal ratification at the regular Nagpur session in December of the same year." },
        { n: 10, sec: "Modern History", q: "What was the primary demand or goal of the ‘Nehru Report’ drafted in 1928?",
          o: ["Complete Independence (Poorna Swaraj)", "Dominion Status", "Separate Electorates", "Dyarchy"], a: "B",
          e: "The report, prepared under the chairmanship of Motilal Nehru, recommended ‘Dominion Status’ for India. Younger leaders like Subhas Chandra Bose and Jawaharlal Nehru opposed this and pressed for complete independence (Poorna Swaraj)." },
        { n: 11, sec: "Modern History", q: "Who was the Prime Minister of Britain when the Cripps Mission arrived in India (1942)?",
          o: ["Ramsay MacDonald", "Clement Attlee", "Winston Churchill", "Neville Chamberlain"], a: "C",
          e: "During World War II (1939–1945), Winston Churchill (Conservative Party) served as the British Prime Minister. Clement Attlee (Labour Party) was Prime Minister when India achieved independence in 1947." },
        { n: 12, sec: "Modern History", q: "In which year was the Wavell Plan announced, and the related Shimla Conference held?",
          o: ["1942", "1945", "1946", "1944"], a: "B",
          e: "Viceroy Lord Wavell proposed a plan in June 1945 to break the political deadlock in India. The Shimla Conference met between June 25 and July 14, 1945, to discuss these proposals." },
        { n: 13, sec: "Indian Geography", q: "Through which of the following states does the ‘Tropic of Cancer’ NOT pass?",
          o: ["Tripura", "Mizoram", "Odisha", "Rajasthan"], a: "C",
          e: "The Tropic of Cancer passes through 8 Indian states: Gujarat, Rajasthan, Madhya Pradesh, Chhattisgarh, Jharkhand, West Bengal, Tripura, and Mizoram. It does not traverse Odisha." },
        { n: 14, sec: "Indian Geography", q: "In which state is the famous ‘Nathu La’ Pass located?",
          o: ["Himachal Pradesh", "Uttarakhand", "Sikkim", "Arunachal Pradesh"], a: "C",
          e: "Nathu La Pass connects Sikkim with China's Tibet Autonomous Region. Another vital Himalayan pass in Sikkim is Jelep La." },
        { n: 15, sec: "Indian Geography", q: "On which river valley or course is the ‘Hirakud Dam’ constructed?",
          o: ["Godavari", "Narmada", "Mahanadi", "Sutlej"], a: "C",
          e: "Hirakud Dam is built across the Mahanadi river near Sambalpur in Odisha. It is one of the longest earthen dams in the world." },
        { n: 16, sec: "Indian Geography", q: "Which type of natural vegetation predominantly covers the Chota Nagpur Plateau region of India?",
          o: ["Tropical Evergreen", "Tropical Deciduous", "Mangrove", "Montane / Alpine"], a: "B",
          e: "The Chota Nagpur Plateau primarily hosts tropical moist deciduous forests. Prominent tree species include Sal, Mahua, Piyal, and Teak." },
        { n: 17, sec: "Indian Geography", q: "Which mountain pass in the Western Ghats connects the cities of Mumbai and Pune?",
          o: ["Thal Ghat", "Bhor Ghat", "Pal Ghat", "Shencottah Gap"], a: "B",
          e: "Bhor Ghat connects Mumbai with Pune. Thal Ghat links Mumbai with Nashik. Pal Ghat links Kerala (Palakkad) with Tamil Nadu (Coimbatore)." },
        { n: 18, sec: "Indian Geography", q: "In which atmospheric layer is the concentration of ozone gas highest, leading it to be called the ‘Ozonosphere’?",
          o: ["Troposphere", "Stratosphere", "Mesosphere", "Thermosphere"], a: "B",
          e: "The ozone layer sits predominantly in the lower stratosphere, roughly 15 to 35 km above Earth's surface, where it absorbs harmful ultraviolet (UV) radiation." },
        { n: 19, sec: "Indian Geography", q: "Which of the following is a global environmental treaty signed to phase out ‘Ozone Depleting Substances’ (ODS)?",
          o: ["Kyoto Protocol", "Montreal Protocol", "Paris Agreement", "Ramsar Convention"], a: "B",
          e: "Finalized in 1987 in Montreal, Canada, this treaty aimed to phase out substances like chlorofluorocarbons (CFCs) responsible for ozone depletion. The Kyoto Protocol deals with greenhouse gas emissions." },
        { n: 20, sec: "Indian Geography", q: "Which Biodiversity Hotspot region in India is exceptionally rich in endemic species?",
          o: ["Indo-Gangetic Plain", "Thar Desert", "Western Ghats", "Eastern Ghats"], a: "C",
          e: "Among the recognized global biodiversity hotspots present in India, the Western Ghats (extending to Sri Lanka) has very high floral and faunal endemism." },
        { n: 21, sec: "Indian Geography", q: "In which year was ‘Project Tiger’ launched in India?",
          o: ["1972", "1973", "1980", "1986"], a: "B",
          e: "Launched on April 1, 1973, under Prime Minister Indira Gandhi at Jim Corbett National Park, Project Tiger was instituted to halt the decline of Bengal tigers. The Wildlife Protection Act was passed earlier in 1972." },
        { n: 22, sec: "Indian Geography", q: "In which year was the ‘Ramsar Convention’ on wetland conservation adopted in Ramsar, Iran?",
          o: ["1971", "1975", "1982", "1992"], a: "A",
          e: "Adopted on February 2, 1971, in the Iranian city of Ramsar, this international treaty provides the framework for national action and international cooperation regarding wetland conservation. February 2 is observed globally as World Wetlands Day." },
        { n: 23, sec: "Biology", q: "Which instrument is used to measure human blood pressure?",
          o: ["Barometer", "Sphygmomanometer", "Stethoscope", "Hydrometer"], a: "B",
          e: "A sphygmomanometer measures arterial blood pressure. Typical resting blood pressure in a healthy adult is approximately 120/80 mm Hg." },
        { n: 24, sec: "Biology", q: "Which hormone is termed the ‘Emergency Hormone’?",
          o: ["Insulin", "Thyroxine", "Adrenaline", "Estrogen"], a: "C",
          e: "Secreted rapidly by the adrenal medulla during stress or fear, adrenaline triggers the physiological “fight-or-flight” response." },
        { n: 25, sec: "Biology", q: "Who discovered the Double Helix structure of DNA?",
          o: ["Robert Hooke", "Watson and Crick", "Gregor Johann Mendel", "Louis Pasteur"], a: "B",
          e: "In 1953, James Watson and Francis Crick elucidated the double-helix model of DNA, which later earned them the Nobel Prize." },
        { n: 26, sec: "Biology", q: "Which plant hormone helps in the initiation of flowering?",
          o: ["Auxin", "Gibberellin", "Cytokinin", "Florigen"], a: "D",
          e: "Florigen is a shoot-transmissible protein/hormone synthesized in the leaves that induces floral transition in the apical meristem." },
        { n: 27, sec: "Physics", q: "If the momentum of an object is doubled, by what factor will its kinetic energy increase?",
          o: ["2 times", "4 times", "8 times", "Remains unchanged"], a: "B",
          e: "Kinetic energy is given by KE = p²/2m. If momentum p is doubled to 2p, the new kinetic energy becomes (2p)²/2m = 4 × (p²/2m) = 4 × KE." },
        { n: 28, sec: "Physics", q: "Which optical phenomenon causes an underwater air bubble to shine?",
          o: ["Refraction", "Diffraction", "Total Internal Reflection", "Interference"], a: "C",
          e: "When light travelling in water hits the water-air interface at an angle exceeding the critical angle, total internal reflection occurs, making the bubble appear silvery and brilliant." },
        { n: 29, sec: "Physics", q: "What is the unit of measurement for the Power of a Lens?",
          o: ["Lumen", "Candela", "Dioptre", "Watt"], a: "C",
          e: "Lens power is calculated as the reciprocal of focal length in meters (P = 1/f), with the SI unit expressed in dioptres (D)." },
        { n: 30, sec: "Chemistry", q: "Brass is an alloy composed of which metals?",
          o: ["Copper and Tin", "Copper and Zinc", "Copper and Nickel", "Iron and Chromium"], a: "B",
          e: "Brass typically consists of roughly 70% copper and 30% zinc. Bronze is an alloy primarily composed of copper and tin." },
        { n: 31, sec: "Chemistry", q: "In what volume ratio are concentrated HCl and concentrated HNO₃ mixed to prepare Aqua Regia?",
          o: ["1:3", "3:1", "2:3", "3:2"], a: "B",
          e: "Aqua Regia consists of 3 parts concentrated hydrochloric acid (HCl) and 1 part concentrated nitric acid (HNO₃) by volume. It dissolves noble metals such as gold and platinum." },
        { n: 32, sec: "Chemistry", q: "Which acid is primarily used as an electrolyte in automobile lead-acid batteries?",
          o: ["Nitric Acid", "Hydrochloric Acid", "Sulfuric Acid", "Acetic Acid"], a: "C",
          e: "Car batteries (lead-acid cells) use dilute sulfuric acid (H₂SO₄) as the electrolyte." },
        { n: 33, sec: "Physics", q: "What should be the ideal characteristics of an electric ‘Fuse Wire’?",
          o: ["High resistance and high melting point", "Low resistance and low melting point", "High resistance and low melting point", "Low resistance and high melting point"], a: "C",
          e: "A fuse wire needs relatively high resistance so that excess current generates sufficient Joule heat (I²Rt), and a low melting point so it melts rapidly to break the circuit safely. It is usually made from an alloy of lead and tin." },
        { n: 34, sec: "Static GK", q: "What is another name for a computer's main circuit board or ‘Motherboard’?",
          o: ["System Board", "Central Board", "Logic Gate", "Storage Unit"], a: "A",
          e: "The motherboard is also referred to as the system board or mainboard. It houses the CPU, memory, and expansion slots for peripherals." },
        { n: 35, sec: "Static GK", q: "Which was the first high-level computer programming language?",
          o: ["COBOL", "FORTRAN", "BASIC", "C"], a: "B",
          e: "Developed by John Backus at IBM in 1957, FORTRAN (Formula Translation) was designed for complex numeric and scientific computations." },
        { n: 36, sec: "Static GK", q: "Which cryptographic security protocol displays the ‘padlock’ icon in a web browser's address bar to safeguard data over the internet?",
          o: ["FTP", "SSL/TLS", "SMTP", "HTTP"], a: "B",
          e: "SSL (Secure Sockets Layer) and TLS (Transport Layer Security) encrypt network communication, serving content via secure HTTPS." },
        { n: 37, sec: "Static GK", q: "What is the standard modern unit used to measure the clock speed of a computer processor?",
          o: ["Kilobytes", "Megabits", "Gigahertz (GHz)", "RPM"], a: "C",
          e: "Modern CPU frequencies are stated in Gigahertz (GHz) or Megahertz (MHz). 1 GHz represents 1 billion clock cycles per second." },
        { n: 38, sec: "Static GK", q: "Linux is an example of what type of software?",
          o: ["Closed-source Operating System", "Open-source Operating System", "Application Software", "Utility Software"], a: "B",
          e: "Linux is an open-source operating system whose source code is freely available, editable, and redistributable." },
        { n: 39, sec: "Static GK", q: "Which symbol separates the two main parts (username and domain name) of an email address?",
          o: ["#", "&", "@", "$"], a: "C",
          e: "The ‘@’ symbol divides the username from the destination domain name (e.g., username@domain.com). It was introduced for network email addresses by Ray Tomlinson in 1971." },
        { n: 40, sec: "Arts and Culture", q: "Which famous festival of Assam is celebrated three times a year across different seasons?",
          o: ["Bihu", "Hornbill", "Ambubachi", "Baishagu"], a: "A",
          e: "Bihu is celebrated in three distinct phases: Bohag Bihu (spring/seeding), Kati Bihu (autumn/crop protection), and Magh Bihu (winter/harvest)." },
        { n: 41, sec: "Arts and Culture", q: "Pandit Hariprasad Chaurasia is a world-renowned maestro associated with which musical instrument?",
          o: ["Sitar", "Bansuri (Flute)", "Santoor", "Sarangi"], a: "B",
          e: "Pandit Hariprasad Chaurasia is an internationally acclaimed classical flautist and Padma Vibhushan recipient." },
        { n: 42, sec: "Static GK", q: "Who was the first Indian (or person of Indian origin) to receive the Nobel Memorial Prize in Economic Sciences, and in which year?",
          o: ["Amartya Sen, 1998", "Abhijit Banerjee, 2019", "C.V. Raman, 1930", "Har Gobind Khorana, 1968"], a: "A",
          e: "Professor Amartya Sen received the Nobel Prize in 1998 for his contributions to welfare economics and poverty research. Abhijit Banerjee was awarded the prize in 2019." },
        { n: 43, sec: "Static GK", q: "Where is the headquarters of the Asian Development Bank (ADB) located?",
          o: ["Jakarta, Indonesia", "Manila, Philippines", "Tokyo, Japan", "Beijing, China"], a: "B",
          e: "Established in 1966, the ADB is headquartered in Mandaluyong, Metro Manila, Philippines." },
        { n: 44, sec: "Indian Geography", q: "In which Indian state are the Ramsar sites ‘Chilika Lake’ and ‘Bhitarkanika Mangroves’ located?",
          o: ["West Bengal", "Andhra Pradesh", "Odisha", "Tamil Nadu"], a: "C",
          e: "Both wetlands are located in Odisha. In 1981, Chilika Lake was designated as India's first Ramsar site of international importance." },
        { n: 45, sec: "Static GK", q: "Every year on February 28, ‘National Science Day’ is observed to commemorate the scientific discovery of which Indian scientist?",
          o: ["Jagadish Chandra Bose", "C.V. Raman", "Homi J. Bhabha", "A.P.J. Abdul Kalam"], a: "B",
          e: "On February 28, 1928, Sir C.V. Raman discovered the inelastic scattering of light, known as the Raman Effect, for which he was awarded the Nobel Prize in Physics in 1930." },
        { n: 46, sec: "Static GK", q: "The Olympic flag consists of five interlocking rings of different colors. Which continent is represented by the ‘yellow’ ring?",
          o: ["Asia", "Africa", "Europe", "America"], a: "A",
          e: "The rings correspond to five major continents: Blue = Europe, Black = Africa, Red = Americas, Yellow = Asia, and Green = Oceania (Australia)." },
        { n: 47, sec: "Static GK", q: "With which sport is the prestigious ‘Thomas Cup’ (men's category) associated?",
          o: ["Lawn Tennis", "Badminton", "Table Tennis", "Chess"], a: "B",
          e: "The Thomas Cup is the world men's team championship in badminton. Its female equivalent is the Uber Cup. India won its historic maiden Thomas Cup title in 2022." },
        { n: 48, sec: "Static GK", q: "In which year and city were the 1st Asian Games held?",
          o: ["1951, New Delhi", "1954, Manila", "1962, Jakarta", "1958, Tokyo"], a: "A",
          e: "The inaugural Asian Games took place in New Delhi in March 1951, with India serving as the host and a principal founding nation." },
        { n: 49, sec: "Static GK", q: "On which date is ‘World Population Day’ observed globally?",
          o: ["July 11", "September 8", "September 16", "December 10"], a: "A",
          e: "Established by the United Nations Development Programme in 1989, World Population Day is marked every year on July 11. September 16 is World Ozone Day." },
        { n: 50, sec: "Arts and Culture", q: "The monolithic ‘Kailashnath Temple’ at the Ellora Caves was constructed during the reign of which dynasty?",
          o: ["Rashtrakuta Dynasty", "Pallava Dynasty", "Chalukya Dynasty", "Chola Dynasty"], a: "A",
          e: "Located in Aurangabad (Chhatrapati Sambhaji Nagar), Maharashtra, this rock-cut temple complex was commissioned by the Rashtrakuta king Krishna I." },
        { n: 51, sec: "Arts and Culture", q: "‘Yakshagana’ is a traditional folk theatre dance form native to which Indian state?",
          o: ["Kerala", "Karnataka", "Tamil Nadu", "Andhra Pradesh"], a: "B",
          e: "Yakshagana is a traditional theatre art form from coastal and malenadu regions of Karnataka combining dance, music, dialogue, and costume, usually based on episodes from the Epics." },
        { n: 52, sec: "Indian Geography", q: "The industrial steel city of Jamshedpur is situated at the confluence of which rivers?",
          o: ["Damodar", "Rupnarayan", "Subarnarekha and Kharkai", "Mahanadi"], a: "C",
          e: "Jamshedpur (Tatanagar) in Jharkhand sits at the meeting point of the Subarnarekha and Kharkai rivers. Tata Steel (TISCO) was established here in 1907." },
        { n: 53, sec: "Static GK", q: "In which Union Territory of India is the historic ‘Cellular Jail’ (known as Kala Pani) situated?",
          o: ["Lakshadweep", "Daman and Diu", "Andaman and Nicobar Islands", "Puducherry"], a: "C",
          e: "The Cellular Jail is located in Port Blair, Andaman and Nicobar Islands. It was used by the British colonial government to exile and imprison political prisoners." }
      ]
    },

    /* ADD NEW SETS ABOVE THIS LINE */

  ]
};
