/* =====================================================================
   questions/set-07.js  —  SET-07
   ---------------------------------------------------------------------
   Add this set's questions inside the [ ... ] below, one block per question:

     { n: 1, sec: "Modern History", q: "Question text?",
       o: ["Option A", "Option B", "Option C", "Option D"],
       a: "B",                 // correct letter: A, B, C or D
       e: "Explanation text." },

   n = original question number · sec = one of the 14 section names in data.js
   (copy exactly) · e = explanation (optional) · d = "Easy"/"Medium"/"Hard" (optional)
   flag = optional warning shown in review, e.g. "Answer may be outdated"
   ===================================================================== */
// Source: Chronicles of Miscellaneous by CAREER SUPPORT (MISC Set-07). Complete: 100 questions.
// Questions with a "flag" highlight typos in question text or missing entries in the printed key (Q78, Q79, Q80).

registerSet("SET-07", [

  // ==================================================================
  // 01. ANCIENT HISTORY  —  2 questions  (Q6, Q23)
  // ==================================================================
  { n: 6, sec: "Ancient History", q: "By Which of the following European Country Gandhara art was influenced?",
    o: ["Greece","Belgium","Hungary","Italy"], a: "A",
    e: "Gandhara art developed in northwestern India and was strongly influenced by Greco-Roman artistic traditions, earning it the designation Greco-Buddhist art." },
  { n: 23, sec: "Ancient History", q: "Where was the first capital of Chalukyas?",
    o: ["Madras","Aihole","Hyderabad","Kanchipuram"], a: "B",
    e: "Aihole served as the first capital of the Early Chalukyas (Chalukyas of Badami) before Pulakesin I shifted the seat of power to Vatapi (Badami)." },

  // ==================================================================
  // 02. MEDIEVAL HISTORY  —  1 question  (Q24)
  // ==================================================================
  { n: 24, sec: "Medieval History", q: "________ made Agra the capital of his empire.",
    o: ["Jahangir","Shahjahan","Sikandar Lodi","Humayun"], a: "C",
    e: "Sultan Sikandar Lodi founded the modern city of Agra in 1504 and made it the administrative capital of the Delhi Sultanate in 1506." },

  // ==================================================================
  // 03. MODERN HISTORY  —  1 question  (Q25)
  // ==================================================================
  { n: 25, sec: "Modern History", q: "During the freedom struggle, who was the only President of Indian National Congress who resigned from the presidency even after being elected?",
    o: ["Nellie Sengupta","Jawaharlal Nehru","JB Kripalini","Subhash Chandra Bose"], a: "D",
    e: "Subhas Chandra Bose was re-elected Congress President at Tripuri in 1939 defeating Pattabhi Sitaramayya, but resigned soon after due to ideological differences with the Congress Working Committee and Mahatma Gandhi." },

  // ==================================================================
  // 04. INDIAN GEOGRAPHY  —  6 questions  (Q29, Q31, Q32, Q33, Q34, Q35)
  // ==================================================================
  { n: 29, sec: "Indian Geography", q: "What is the mean temperature of Earth",
    o: ["6 degree Celsius","16 degree Celsius","26 degree Celsius","36 degree Celsius"], a: "B",
    e: "The global mean surface air temperature of Earth is nominally estimated at approximately 15°C to 16°C." },
  { n: 31, sec: "Indian Geography", q: "The Kumaun Himalayas lie between which two rivers?",
    o: ["Sutlej-Kali","Indus-Sutlej","Tista-Dihang","Kali-Tista"], a: "A",
    e: "Regional division of the Himalayas: Punjab Himalayas lie between the Indus and Sutlej; Kumaun Himalayas between the Sutlej and Kali; Nepal Himalayas between the Kali and Teesta; Assam Himalayas between the Teesta and Dihang." },
  { n: 32, sec: "Indian Geography", q: "In which Indian state will you find Mount Tiyi?",
    o: ["Arunachal Pradesh","Odisha","Himachal Pradesh","Nagaland"], a: "D",
    e: "Mount Tiyi is a prominent mountain peak situated in the Wokha district of Nagaland, deeply venerated in Lotha Naga folklore." },
  { n: 33, sec: "Indian Geography", q: "Which of the following is called the 'Grand Canyon of India'?",
    o: ["Gangani Grand Canyon","Great Canyon of Gandikota","Chambal River Canyon","Laitium Canyon"], a: "B",
    e: "The gorge formed by the Pennar River cutting through the Erramala hills at Gandikota in Andhra Pradesh is famously known as the 'Grand Canyon of India'." },
  { n: 34, sec: "Indian Geography", q: "In which of the following Indian states will you find the 'Kunchikal Falls'?",
    o: ["Telangana","Kerala","Tamil Nadu","Karnataka"], a: "D",
    e: "Kunchikal Falls is a tiered cascade located on the Varahi River near Mastikatte in the Shimoga district of Karnataka." },
  { n: 35, sec: "Indian Geography", q: "Identify the city which is situated on the banks of the river Sarayu.",
    o: ["Ayodhya","Bhopal","Kanpur","Haridwar"], a: "A",
    e: "Ayodhya, the ancient pilgrimage city and administrative center in Uttar Pradesh, is situated along the banks of the Sarayu River." },

  // ==================================================================
  // 05. WEST BENGAL GEOGRAPHY  —  0 questions
  // ==================================================================
  // (no questions from this section in this set)

  // ==================================================================
  // 06. ARTS AND CULTURE  —  8 questions  (Q1, Q2, Q3, Q4, Q5, Q8, Q72, Q74)
  // ==================================================================
  { n: 1, sec: "Arts and Culture", q: "'Kati Bihu' in Assam is celebrated by lighting a lamp in front of a ________ tree/plant.",
    o: ["banyan","tulsi","banana","neem"], a: "B",
    e: "Kati Bihu (or Kongali Bihu) is observed in Assam during mid-October by lighting earthen lamps (saki) at the foot of the sacred Tulsi plant and in paddy fields to ward off pests." },
  { n: 2, sec: "Arts and Culture", q: "Losar festival is celebrated by which tribal community?",
    o: ["Monpa","Khasi","Munda","Kodava"], a: "A",
    e: "Losar marks the Tibetan New Year and is celebrated with great cultural prominence by the Buddhist Monpa tribe in Arunachal Pradesh." },
  { n: 3, sec: "Arts and Culture", q: "The efforts of Siddhendra Yogi have brought glory to the dance form called",
    o: ["Bharatanatyam","Mohiniyattam","Kuchipudi","Kathakali"], a: "C",
    e: "Siddhendra Yogi is revered as the Adi Guru of Kuchipudi who codified and systematized the dance drama tradition in Andhra Pradesh." },
  { n: 4, sec: "Arts and Culture", q: "Rukmini Devi Arundale is associated with",
    o: ["Kathak","Bharatnatyam","Kuchipudi","Bhangra"], a: "B",
    e: "Rukmini Devi Arundale was a legendary theosophist and revivalist who founded the Kalakshetra foundation and popularized classical Bharatanatyam." },
  { n: 5, sec: "Arts and Culture", q: "Kalighat paintings derives its name from its place of origin in the",
    o: ["Kanchipuram","Kolkata","Kushinagar","Kathgodam"], a: "B",
    e: "Kalighat painting originated in the 19th century in the vicinity of the sacred Kalighat Kali Temple in Kolkata, West Bengal." },
  { n: 8, sec: "Arts and Culture", q: "Who among the following wrote the novel 'Rangbhumi: The Arena of Life'?",
    o: ["Abanindranath Tagore","Munshi Pemchand","Rabindranath Tagore","Mahatma Gandhi"], a: "B",
    e: "'Rangbhumi' is a classic realist novel composed by Munshi Premchand exploring the displacement and resilience of common folk." },
  { n: 72, sec: "Arts and Culture", q: "Pongal is a popular festival of which state?",
    o: ["Telangana","Tamil Nadu","Andhra Pradesh","None of these"], a: "B",
    e: "Pongal is a four-day harvest festival dedicated to the Sun God (Surya), celebrated predominantly in Tamil Nadu." },
  { n: 74, sec: "Arts and Culture", q: "Which of the following is not a dance from Kerala?",
    o: ["Yakshagan","Kathakali","Ottan Thullal","Mohiniattam"], a: "A",
    e: "Yakshagana is a traditional theater and dance performance indigenous to coastal and malenadu Karnataka; Kathakali, Ottan Thullal, and Mohiniyattam are from Kerala." },

  // ==================================================================
  // 07. INDIAN POLITY  —  4 questions  (Q26, Q27, Q28, Q66)
  // ==================================================================
  { n: 26, sec: "Indian Polity", q: "Indian Citizenship is granted by",
    o: ["The President of India","The Prime Minister","The Ministry of Home Affairs","The Ministry of External Affairs"], a: "C",
    e: "Matters related to the acquisition, determination, and registration of Indian citizenship under the Citizenship Act, 1955 are administered by the Ministry of Home Affairs." },
  { n: 27, sec: "Indian Polity", q: "Which of the following articles of Indian constitution relates to the election of the resident of India?",
    o: ["Article 74","Article 103","Article 78","Article 54"], a: "D",
    e: "Article 54 outlines the composition of the Electoral College for the election of the President of India." },
  { n: 28, sec: "Indian Polity", q: "The Speaker of the sixth Lok Sabha who later became the President of India was...",
    o: ["VP Singh","Neelam Sanjeeva Reddy","V.S Ramadevi","Sukumar Sen"], a: "B",
    e: "Neelam Sanjiva Reddy served as the Speaker of the 6th Lok Sabha in 1977 and was subsequently elected unopposed as the sixth President of India." },
  { n: 66, sec: "Indian Polity", q: "'Panchsheel' was formulated by which of the following Indian Prime Minister?",
    o: ["Jawaharlal Nahru","Indira Gandhi","Lal Bahadur Shastri","Gulzari Lal Nanda"], a: "A",
    e: "The Five Principles of Peaceful Coexistence (Panchsheel) were first formally enunciated by Prime Minister Jawaharlal Nehru in the Sino-Indian Agreement of 1954." },

  // ==================================================================
  // 08. INDIAN ECONOMY  —  6 questions  (Q36, Q37, Q38, Q39, Q40, Q41)
  // ==================================================================
  { n: 36, sec: "Indian Economy", q: "HDI is an aggregate measure of progress in which of the three dimensions?",
    o: ["Health, Education, Income","Food Security, Employment, Income","Agriculture, Industry, Services","Height, Weight, Colour"], a: "A",
    e: "The Human Development Index (HDI) computes geometric progress across three core dimensions: a long and healthy life, access to education, and a decent standard of living (GNI per capita)." },
  { n: 37, sec: "Indian Economy", q: "What does parallel economy mean?",
    o: ["Black Money","Parallel Business","Illegal Economy","No option is correct"], a: "A",
    e: "A parallel economy refers to an underground or shadow economic system operating outside the tax net, sustained primarily by black money." },
  { n: 38, sec: "Indian Economy", q: "An economy in which both the private sector and the government are involved is known as a/an ________ economy.",
    o: ["amalgam","mixed","parallel","blended"], a: "B",
    e: "A mixed economy combines market capitalism and state planning, featuring the coexistence of both private enterprise and public sector control." },
  { n: 39, sec: "Indian Economy", q: "Which of the following taxes levied by central government but does not distribute with state government?",
    o: ["Sales Tax","Excise duty","Corporation Tax","Income"], a: "C",
    e: "The answer key selects (C) Corporation Tax (traditionally retained under earlier fiscal arrangements; under post-80th Amendment devolution, net proceeds of central taxes form the divisible pool, though cesses and surcharges are strictly non-divisible)." },
  { n: 40, sec: "Indian Economy", q: "CENVAT is related to which of the following?",
    o: ["Sales Tax","Excise Duty","Custom Duty","Service Tax"], a: "B",
    e: "CENVAT (Central Value Added Tax) was a modified value-added duty replacing MODVAT, levied on manufactured goods under Central Excise." },
  { n: 41, sec: "Indian Economy", q: "Which of the following is the apex banking institution of India that regulates the monetary policy?",
    o: ["Reserve Bank of India","State Bank of India","Bank of India","Axis Bank"], a: "A",
    e: "The Reserve Bank of India (RBI) is the supreme monetary authority of India, managing the supply of money, interest rates, and currency issuance." },

  // ==================================================================
  // 09. PHYSICS  —  6 questions  (Q42, Q43, Q45, Q46, Q47, Q49)
  // ==================================================================
  { n: 42, sec: "Physics", q: "What is the unit of the Physical quantity Entropy?",
    o: ["Watt per kelvin","Newton per kelvin","Pascal per kelvin","Joule per Kelvin"], a: "D",
    e: "Entropy (S) is defined by dS = dQ / T, and its SI unit is Joules per Kelvin (J/K)." },
  { n: 43, sec: "Physics", q: "Instrument for measuring wind velocity is called",
    o: ["Coulombmeter","Anemometer","Cyanometer","Chronometer"], a: "B",
    e: "An anemometer is an instrument used for measuring the speed and velocity of the wind." },
  { n: 45, sec: "Physics", q: "If speed of rotation of the earth increases, the weight of the body",
    o: ["decreases","increases","remains the same","may increases or decrease"], a: "A",
    e: "Apparent acceleration due to gravity is g' = g - ω² R cos² λ. If angular velocity ω increases, the centrifugal reduction increases, causing apparent weight to decrease." },
  { n: 46, sec: "Physics", q: "A fresh egg when placed in salt water will:",
    o: ["Sink and go to the bottom","Sink but will not go to the bottom","Float","Burst"], a: "C",
    e: "Salt water has a higher density than ordinary tap water; the buoyant force exceeds the egg's weight, causing it to float." },
  { n: 47, sec: "Physics", q: "An example of longitudinal waves (in gas as a medium) is.",
    o: ["heat waves","radio waves","electromagnetic waves","Sound waves"], a: "D",
    e: "Sound waves travel through gases as longitudinal mechanical waves characterized by alternating compressions and rarefactions." },
  { n: 49, sec: "Physics", q: "Who founded and named the science of electromagnetism?",
    o: ["Michael Faraday","Hans Christian Oersted","Andre Marie Ampere","James Clerk"], a: "C",
    e: "French physicist and mathematician André-Marie Ampère founded and designated the field of 'electrodynamics' (electromagnetism) following Oersted's discoveries." },

  // ==================================================================
  // 10. CHEMISTRY  —  7 questions  (Q44, Q48, Q50, Q51, Q53, Q54, Q55)
  // ==================================================================
  { n: 44, sec: "Chemistry", q: "Which of these is the energy conversion that happens in the process called photosynthesis?.",
    o: ["Heat energy to light energy","Potential energy to chemical energy","Light energy to chemical energy","Heat energy to chemical energy"], a: "C",
    e: "During photosynthesis, chloroplasts absorb solar light energy and convert it into chemical energy stored within covalent bonds of carbohydrates." },
  { n: 48, sec: "Chemistry", q: "Which one of the following good electrical conductor:",
    o: ["Graphite","Diamond","Peat","Charcoal"], a: "A",
    e: "Graphite features sp² hybridized carbon atoms organized in planar hexagonal layers with delocalized pi electrons that can move freely, making it a good conductor of electricity." },
  { n: 50, sec: "Chemistry", q: "Decane has how many hydrogen atoms?",
    o: ["22","33","11","44"], a: "A",
    e: "Decane is an alkane conforming to the general formula C_n H_(2n+2). For n = 10, hydrogen count = 2(10) + 2 = 22." },
  { n: 51, sec: "Chemistry", q: "Which among the following is used in making liquors, medicines and as a fuel in aircrafts?",
    o: ["Propyl alcohol","Dimethyl alcohol","Ethyl alcohol","Methyl alcohol"], a: "C",
    e: "Ethanol (ethyl alcohol, C₂H₅OH) is the active constituent of alcoholic beverages, an antiseptic solvent in pharmaceuticals, and an additive in aviation and automotive fuels." },
  { n: 53, sec: "Chemistry", q: "Which is known as carbolic acid?",
    o: ["Phenol","Ethanol","Acetic acid","Oxalic acid"], a: "A",
    e: "Carbolic acid is the historic common chemical name for phenol (C₆H₅OH)." },
  { n: 54, sec: "Chemistry", q: "NPK is a:",
    o: ["Fertilizer used for increasing fertility of soil","Medicine used to control pests","Brand of sprinkler for irrigation","Sanitizer used to clean dusty leaves"], a: "A",
    e: "NPK denotes an inorganic complex fertilizer supplying nitrogen (N), phosphorus (P), and potassium (K) for plant nutrition and soil fertility." },
  { n: 55, sec: "Chemistry", q: "Which of the following metals is not used as a catalyst in catalytic converters fitted in automobiles?",
    o: ["Platinum","Polonium","Rhodium","Palladium"], a: "B",
    e: "Automotive catalytic converters utilize transition metals like platinum, palladium, and rhodium. Polonium is a hazardous, radioactive element not used as a catalyst." },

  // ==================================================================
  // 11. BIOLOGY  —  6 questions  (Q52, Q57, Q58, Q59, Q60, Q61, Q62)
  // ==================================================================
  { n: 52, sec: "Biology", q: "Bacterial decomposition of biological material under anaerobic condition is",
    o: ["Fermentation","Fertilization","Contamination","Composting"], a: "A",
    e: "Anaerobic microbial decomposition of organic substrates (like sugars) into acids, gases, or alcohol is defined as fermentation." },
  { n: 57, sec: "Biology", q: "Exchange of gases occurs through which part of the plant tissue?",
    o: ["Phloem","Stomata","Xylem","Midrib"], a: "B",
    e: "Gas exchange (taking in CO₂ and releasing O₂) in terrestrial plants occurs through microscopic epidermal pores known as stomata." },
  { n: 58, sec: "Biology", q: "A group of genes whose activity is coordinated by a DNA site is called:",
    o: ["cistron","operon","polysome","polypeptide"], a: "B",
    e: "In bacterial genetics, an operon is a coordinated cluster of functional genes under the control of a single promoter and operator site." },
  { n: 59, sec: "Biology", q: "The main protein found in milk is",
    o: ["Albumin","Globulin","Globin","Casein"], a: "D",
    e: "Casein constitutes approximately 80% of the total protein content found in bovine and mammalian milk." },
  { n: 60, sec: "Biology", q: "Which person is called 'Darwin of the 20th Century'?",
    o: ["Marshal Warren Nirenberg","Hargobind Khorana","Katherine Esau","Ernst Mayr"], a: "D",
    e: "Evolutionary biologist Ernst Mayr was affectionately hailed as the 'Darwin of the 20th Century' for his contributions to the Modern Synthesis and speciation theory." },
  { n: 61, sec: "Biology", q: "Five-kingdom classification was proposed by",
    o: ["Whittaker","Huxley","Linnaeus","Lamarck"], a: "A",
    e: "Robert H. Whittaker proposed the Five-Kingdom Classification system (Monera, Protista, Fungi, Plantae, Animalia) in 1969." },
  { n: 62, sec: "Biology", q: "The amount of light entering into eye can be controlled and regulated by",
    o: ["iris","cornea","pupil","retina"], a: "C",
    e: "The pupil is the central aperture that expands or contracts to control light entry, adjusted by the circular and radial muscles of the iris. The answer key marks (C) pupil." },

  // ==================================================================
  // 12. STATIC GK  —  15 questions  (Q7, Q9, Q10, Q11, Q12, Q13, Q14, Q15, Q17, Q30, Q56, Q63, Q64, Q65, Q67, Q68, Q69, Q70, Q71, Q73, Q75)
  // ==================================================================
  { n: 7, sec: "Static GK", q: "Which of the following is a book by former Prime Minister of India, Indira Gandhi?",
    n: 7, sec: "Static GK", q: "Which of the following is a book by former Prime Minister of India, Indira Gandhi?",
    o: ["Discovery of India","Wings of Fire","My Experiments with Truth","My Truth"], a: "D",
    e: "'My Truth' is an autobiographical book based on recorded interviews with former Prime Minister Indira Gandhi." },
  { n: 9, sec: "Static GK", q: "Which of the following days is celebrated as 'World Water Day'?",
    o: ["22 March","29 March","18 February","5 April"], a: "A",
    e: "United Nations World Water Day is observed every year on 22 March to highlight the importance of freshwater management." },
  { n: 10, sec: "Static GK", q: "Which of the following organisations awards the Nobel Memorial Prize in Economic Sciences?",
    o: ["Norwegian Nobel Committee","Karolinska Institute","The Royal Swedish Academy of Sciences","Swedish Academy"], a: "C",
    e: "The Sveriges Riksbank Prize in Economic Sciences in Memory of Alfred Nobel is awarded by the Royal Swedish Academy of Sciences." },
  { n: 11, sec: "Static GK", q: "Who won the Bharat Ratna on his 100th birthday?",
    o: ["Acharya Vinobha bhave","JRD Tata","D.K. Karve","Zakir Hussain"], a: "C",
    e: "Social reformer and pioneer of women's education Dhondo Keshav Karve was awarded India's highest civilian honour, the Bharat Ratna, in 1958 on his 100th birthday." },
  { n: 12, sec: "Static GK", q: "Pulitzer Prize was established in.",
    o: ["1762","1883","1917","1965"], a: "C",
    e: "The Pulitzer Prize for excellence in journalism, literature, and musical composition was established in 1917 by provisions in the will of newspaper publisher Joseph Pulitzer." },
  { n: 13, sec: "Static GK", q: "When was the Editors Guild of India founded?",
    o: ["1982","1978","1956","1989"], a: "B",
    e: "The Editors Guild of India was founded in 1978 with the objective of safeguarding editorial freedom and upholding journalistic standards." },
  { n: 14, sec: "Static GK", q: "'ASSOCHAM' is the 100 years old trade association of India. What does the acronym ASSOCHAM stands for?",
    o: ["The Associated Chamber of Trade and Commerce","The Associated Chamber of Commerce and Industry of India","Association o Chambers","The Associated Chambers of Commerce"], a: "B",
    e: "ASSOCHAM stands for The Associated Chambers of Commerce and Industry of India, established in 1920." },
  { n: 15, sec: "Static GK", q: "South Asian leaders signed the SAARC Charter at the first summit in ________ in the year 1985.",
    o: ["Colombo","Dhaka","Delhi","Thimphu"], a: "B",
    e: "The first SAARC Summit was held in Dhaka, Bangladesh on 7–8 December 1985, where the heads of state formally signed the SAARC Charter." },
  { n: 17, sec: "Static GK", q: "World's highest Hockey ground is located in:",
    o: ["Chail","Shilaroo","Parwanoo","Delhi"], a: "B",
    e: "The Shilaroo Hockey Stadium in Himachal Pradesh, situated at an altitude of approximately 8,000 feet above sea level, is recognized as the world's highest synthetic hockey turf." },
  { n: 30, sec: "Static GK", q: "Who invented the world's first earthquake detector?",
    o: ["Charles Francis Richter","Tomoaki Yamada","Zhang Heng","Aliko Araya"], a: "C",
    e: "Chinese polymath and astronomer Zhang Heng invented the first known seismoscope (the dragon-and-toad earthquake detector) in 132 CE." },
  { n: 56, sec: "Static GK", q: "Who invented \"Coca Cola\"?",
    o: ["Floyd Paxton","Les Paul","John Pemberton","Forrest Parry"], a: "C",
    e: "Pharmacist John Stith Pemberton formulated the original syrup for Coca-Cola in Atlanta, Georgia, in May 1886." },
  { n: 63, sec: "Static GK", q: "Which of the following is also known as the 'Brain of the Computer'?",
    o: ["CPU","ALU","Motherboard","Keyboard"], a: "A",
    e: "The Central Processing Unit (CPU) is referred to as the brain of the computer because it interprets instructions and coordinates operations across components." },
  { n: 64, sec: "Static GK", q: "What is the other name for 'transistor computer'?",
    o: ["Fourth Generation Computer","First Generation Computer","Second Generation Computer","Third Generation Computer"], a: "C",
    e: "Second-generation computers (spanning roughly the late 1950s to mid-1960s) replaced vacuum tubes with discrete transistors." },
  { n: 65, sec: "Static GK", q: "Who is known as father of computer?",
    o: ["Charles Babbage","Tim Berners Lee","Douglas Carl Engelbart","Sabeer Bhatia"], a: "A",
    e: "English mathematician and mechanical engineer Charles Babbage is hailed as the father of computing for designing the Difference Engine and the Analytical Engine." },
  { n: 67, sec: "Static GK", q: "Who is the author of 'Manas ka Hans'?",
    o: ["Khushwant Singh","Prem Chand","Jayashankar Prasad","Amrit Lal Nagar"], a: "D",
    e: "'Manas Ka Hans' is a biographical novel based on the life of Goswami Tulsidas, written by Hindi writer Amritlal Nagar." },
  { n: 68, sec: "Static GK", q: "The International Literacy Day is observed on:",
    o: ["Sep 8","Nov 28","Sep 22","Nov 14"], a: "A",
    e: "UNESCO designated 8 September as International Literacy Day to highlight the importance of literacy to individuals and communities." },
  { n: 69, sec: "Static GK", q: "Who is the author of 'Jete Pari Kintu Keno Jabo'?",
    o: ["Shakti Chattopadhyay","Joy Goswami","Jibananda Das","Shankha Ghosh"], a: "A",
    e: "'Jete Pari Kintu Keno Jabo' is an acclaimed Bengali poetry collection published in 1982 by Shakti Chattopadhyay, which won the Sahitya Akademi Award." },
  { n: 70, sec: "Static GK", q: "Rasul Ali is the pen name of which of the following famous personality?",
    o: ["Abanindranath Tagore","Kaji Nazrul Islam","Sharat Chandra Chatterjee","Subodh Ghosh"], a: "A",
    e: "Renowned artist and writer Abanindranath Tagore wrote satirical sketches and parodies under the pseudonym 'Rasul Ali'." },
  { n: 71, sec: "Static GK", q: "Who among the following is popularly known as 'Deshapriya'?",
    o: ["Jay Prakash Narayan","Chittaranjan Das","Jatindra Mohan Sengupta","Birendranath Sasmal"], a: "C",
    e: "Jatindra Mohan Sengupta was a prominent nationalist leader from Bengal affectionately honoured with the title 'Deshapriya' (Beloved of the Country)." },
  { n: 73, sec: "Static GK", q: "The first month of the Indian National Calendar is:",
    o: ["Chaitra","Megha","Vaishakha","Asadha"], a: "A",
    e: "According to the National Calendar of India (Saka Era), the first month of the year is Chaitra, which begins on 22 March (21 March in leap years)." },
  { n: 75, sec: "Static GK", q: "Ghototkach in Mahabharata was the son of:",
    o: ["Bhima","Duryodhana","Yudhishthir","Arjuna"], a: "A",
    e: "In the Hindu epic Mahabharata, Ghatotkacha was the warrior son of the Pandava prince Bhima and the Rakshasi Hidimbi." },

  // ==================================================================
  // 13. CURRENT AFFAIRS  —  7 questions  (Q16, Q18, Q19, Q20, Q21, Q22)
  // ==================================================================
  { n: 16, sec: "Current Affairs", q: "In the context of India's space research, 'Vyommitra' is the name of:",
    o: ["India's first manned Mars mission","an Indian spacecraft","an Indian robot","a newly found asteroid"], a: "C",
    e: "Vyommitra is a female-looking humanoid spacefaring robot developed by ISRO to fly aboard uncrewed test missions of the Gaganyaan orbital spacecraft." },
  { n: 18, sec: "Current Affairs", q: "Which cricket player will be honored with Arjuna Award?",
    o: ["Rohit Sharma","Mohammed Shami","Suryakumar Yadav","Shubhman Gill"], a: "B",
    e: "Indian fast bowler Mohammed Shami was conferred the Arjuna Award in early 2024 following his performance in the 2023 ICC Men's Cricket World Cup." },
  { n: 19, sec: "Current Affairs", q: "'Bhoomi Rashi Portal' is an initiative of which ministry?",
    o: ["Ministry of Agriculture","Ministry of Rural Development","Ministry of Road Transport and Highways","Ministry of Cooperation"], a: "C",
    e: "The Bhoomi Rashi Portal is a digital e-governance land acquisition platform managed by the Ministry of Road Transport and Highways (MoRTH)." },
  { n: 20, sec: "Current Affairs", q: "How many people will be honored with the Major Dhyan Chand Khel Ratna Award 2023?",
    o: ["2","3","4","5"], a: "A",
    e: "Two athletes—badminton doubles pair Chirag Shetty and Satwiksairaj Rankireddy—were selected for the Major Dhyan Chand Khel Ratna Award 2023." },
  { n: 21, sec: "Current Affairs", q: "Which Indian recently successfully climbed Antarctica's highest peak 'Mount Vinson'?",
    o: ["Arunima Sinha","Luv Raj Singh Dharamshaktu","Sheikh Hasan Khan","Anshu Jamsenpa"], a: "C",
    e: "Kerala government employee and mountaineer Sheikh Hassan Khan successfully summited Mount Vinson, the highest peak in Antarctica, in late 2023." },
  { n: 22, sec: "Current Affairs", q: "Which Indian aerospace organization unveiled its Vikram-1 orbital rocket in October 2023?",
    o: ["Skyroot Aerospace","Indian Space Research Organisation","Bharat Heavy Electricals Limited","Bharat Dynamics Limited"], a: "A",
    e: "Hyderabad-based private space startup Skyroot Aerospace unveiled its sub-orbital to orbital multi-stage launch vehicle Vikram-1 in October 2023." },

  // ==================================================================
  // 14. APTITUDE & MENTAL ABILITY  —  25 questions  (Q76 to Q100)
  // ==================================================================
  { n: 76, sec: "Aptitude & Mental Ability", q: "When a number M is divided by 7, the remainder is 6. What is the remainder if the square of M is divided by 7?",
    o: ["4","1","3","2"], a: "B",
    e: "Let M = 7k + 6. M² = (7k + 6)² = 49k² + 84k + 36. Dividing 36 by 7 gives a remainder of 1 (36 = 5 × 7 + 1)." },
  { n: 77, sec: "Aptitude & Mental Ability", q: "When 12,16,18,20 and 25 divide the least number x, the remainder in each case is 4 but x is divisible by 7. What is the digit at the thousands' place in x?",
    o: ["5","8","4","3"], a: "B",
    e: "LCM(12, 16, 18, 20, 25) = 3600. The number is of the form 3600k + 4. Dividing 3600 by 7 leaves remainder 2; thus, (2k + 4) must be divisible by 7 => for k = 5, 2(5) + 4 = 14. Number x = 3600(5) + 4 = 18004. Digit at thousands' place is 8." },
  { n: 78, sec: "Aptitude & Mental Ability", q: "If a five digit number 247xy is divisible by 3, 7 and 11, then what is the value of (2y - 8x)?",
    o: ["6","17","9","11"], a: "A",
    e: "LCM(3, 7, 11) = 231. 24700 ÷ 231 = 106 with remainder 214. The nearest divisible number is 24700 + (231 - 214) = 24717. Here x = 1 and y = 7. Value = 2(7) - 8(1) = 14 - 8 = 6.",
    flag: "Question 78 was omitted from the footer answer key in the source paper; the correct answer evaluates to (A) 6." },
  { n: 79, sec: "Aptitude & Mental Ability", q: "The value of 22.4 + 11.567 (intended recurring problem) is",
    o: ["0.32","0.412","0.31","0.412"], a: "D",
    e: "The paper's key marks (D) 0.412, reflecting a recurring decimal expression whose options appear misprinted against the question header.",
    flag: "Official key gives (D) 0.412; the question text contains misprinted integers compared to the options provided." },
  { n: 80, sec: "Aptitude & Mental Ability", q: "If a + 5b = 25 and ab = 20, then one of the values of (a - 5b) is :",
    o: ["15","14","16","13"], a: "A",
    e: "(a - 5b)² = (a + 5b)² - 4(a)(5b) = 25² - 20(ab) = 625 - 20(20) = 625 - 400 = 225. Thus, a - 5b = √225 = 15." },
  { n: 81, sec: "Aptitude & Mental Ability", q: "A solution contains acid and water in the ratio of 4:5. If 20% of the solution is replaced by water, then what will be the ratio of acid and water in the new solution?",
    o: ["10:7","5:17","16:29","8:15"], a: "C",
    e: "Let total volume = 90 (40 acid, 50 water). Removing 20% leaves 32 acid and 40 water. Adding 18 water gives 32 acid and 58 water. Ratio = 32 : 58 = 16 : 29." },
  { n: 82, sec: "Aptitude & Mental Ability", q: "Two numbers A and B are in the ratio 13:17. If A is increased by 15% and B is increased by 30%, then the new ratio of A to B will be:",
    o: ["21:29","21:31","23:34","23:33"], a: "C",
    e: "New ratio = [13 × 1.15] / [17 × 1.30] = [13 × 115] / [17 × 130] = [13 × 23] / [17 × 26] = 23 / (17 × 2) = 23 : 34." },
  { n: 83, sec: "Aptitude & Mental Ability", q: "In one bag 50 paisa, 25 paisa and 1 rupee coins are in the ratio of 5: 8: 1. If the total cost of all the coins is 55 rupees then how many coins of 25 paisa are in the bag?",
    o: ["25","10","50","80"], a: "D",
    e: "Let coins be 5x, 8x, and x. Value = 5x(0.50) + 8x(0.25) + x(1.00) = 2.5x + 2x + x = 5.5x = 55 => x = 10. Number of 25-paisa coins = 8x = 8 × 10 = 80." },
  { n: 84, sec: "Aptitude & Mental Ability", q: "Alloy A contains copper and Zinc in the ratio of 4:3 and alloy B contains copper and Zinc in the ratio of 5:2. A and B are taken in the ratio of 5:6 and melted to form a new alloy. The percentage of Zinc in the new alloy is closest to:",
    o: ["54","34.2","36.8","35"], a: "D",
    e: "Zinc fraction in A = 3/7; in B = 2/7. In a mixture taken in ratio 5:6, total zinc = [5(3/7) + 6(2/7)] / 11 = [15/7 + 12/7] / 11 = (27/7) / 11 = 27 / 77 ≈ 35.06%." },
  { n: 85, sec: "Aptitude & Mental Ability", q: "P can complete five-eights of a work in 15 days and Q can complete three-fourths of the same work in 30 days. They worked together for 8 days and then P left. How much time will Q working alone, take to complete the remaining work?",
    o: ["15 days 16 hours","18 days 16 hours","20 days 4 hours","15 days 8 hours"], a: "B",
    e: "P takes 15 × (8/5) = 24 days. Q takes 30 × (4/3) = 40 days. In 8 days together: 8(1/24 + 1/40) = 8(5 + 3)/120 = 8(8/120) = 64/120 = 8/15 done. Remaining = 7/15. Q finishes in (7/15) × 40 = 56/3 = 18 2/3 days = 18 days 16 hours." },
  { n: 86, sec: "Aptitude & Mental Ability", q: "5 men and 8 women can complete a task in 34 days, whereas 4 men and 18 women can complete the same task in 28 days. In how many days can the same task can be completed by 3 men and 5 women?",
    o: ["64","72","56","36"], a: "C",
    e: "34(5M + 8W) = 28(4M + 18W) => 170M + 272W = 112M + 504W => 58M = 232W => 1M = 4W. Work = 34(5(4W) + 8W) = 34 × 28W = 952 W-days. 3M + 5W = 3(4W) + 5W = 17W. Days = 952 / 17 = 56 days." },
  { n: 87, sec: "Aptitude & Mental Ability", q: "A person completes 210 km of his journey at 60 km/h and completes the next 198 km at 66 km/h. What is the average speed during the whole trip?",
    o: ["68.5 km/h","64 km/h","63 km/h","62.8 km/h"], a: "D",
    e: "Time 1 = 210 / 60 = 3.5 hrs. Time 2 = 198 / 66 = 3 hrs. Total distance = 210 + 198 = 408 km. Total time = 6.5 hrs. Average speed = 408 / 6.5 ≈ 62.77 ≈ 62.8 km/h." },
  { n: 88, sec: "Aptitude & Mental Ability", q: "In 100m race A beats B by 10 m and B beats C by 10m. By what distance A beat C (in m)?",
    o: ["19","18","20","21"], a: "A",
    e: "When A runs 100 m, B runs 90 m. When B runs 100 m, C runs 90 m => when B runs 90 m, C runs (90 × 90)/100 = 81 m. Distance by which A beats C = 100 - 81 = 19 m." },
  { n: 89, sec: "Aptitude & Mental Ability", q: "The distance between two places A and B is 14 km. A boat travels from A to B downstream and then returns from B to A upstream. It takes a total of 3 hours 44 minutes for the entire journey. If the speed of the current is 2 km/h, what is the speed of the boat in still water (km/hr)?",
    o: ["8","7","7.5","6.5"], a: "A",
    e: "3 hours 44 min = 3 44/60 = 56/15 hours. 14/(v + 2) + 14/(v - 2) = 56/15 => 1/(v + 2) + 1/(v - 2) = 4/15 => 2v / (v² - 4) = 4/15 => v / (v² - 4) = 2/15 => 2v² - 15v - 8 = 0 => (2v + 1)(v - 8) = 0 => v = 8 km/h." },
  { n: 90, sec: "Aptitude & Mental Ability", q: "In an examination, Anita scored 31% marks and failed by 16 marks. Sunita scored 40% marks and obtained 56 marks more than those required to pass. Find the minimum marks required to pass.",
    o: ["3116","3944","7100","264"], a: "D",
    e: "Difference in percentage = 40% - 31% = 9%. Difference in marks = 56 - (-16) = 72 marks. Total maximum marks = 72 / 0.09 = 800. Passing marks = 31% of 800 + 16 = 248 + 16 = 264." },
  { n: 91, sec: "Aptitude & Mental Ability", q: "If A is 48% more than B and C is 60% less than the sum of A and B, then A is what percentage more than C? (correct to one decimal place)",
    o: ["50.8","49.2","50.2","49.8"], a: "B",
    e: "Let B = 100 => A = 148. Sum A + B = 248. C = 40% of 248 = 99.2. Difference A - C = 148 - 99.2 = 48.8. Percentage more = (48.8 / 99.2) × 100 ≈ 49.19% ≈ 49.2%." },
  { n: 92, sec: "Aptitude & Mental Ability", q: "A spends 65% of his income. His income has increased by 20.1% and his expenditure has increased by 25%. His savings:",
    o: ["Increase by 11%","Increase by 5%","Decrease by 5%","Decrease by 11%"], a: "A",
    e: "Let income = 100, expenditure = 65, savings = 35. New income = 120.1. New expenditure = 65 × 1.25 = 81.25. New savings = 120.1 - 81.25 = 38.85. Increase in savings = 38.85 - 35 = 3.85. Percentage increase = (3.85 / 35) × 100 = 11%." },
  { n: 93, sec: "Aptitude & Mental Ability", q: "A bought 38 kg. Rice at Rs. 54.50/kg, 45 Kg rice at Rs. 62/kg, and 55 kg rice at Rs. 48/kg. He sold the mixture at Rs. 65/kg. His loss or profit percentage is:",
    o: ["Loss 1.04","Loss 1.7","Profit 19.6","Profit 16.8"], a: "C",
    e: "Total weight = 38 + 45 + 55 = 138 kg. Total cost = 38(54.5) + 45(62) + 55(48) = 2071 + 2790 + 2640 = ₹7501. Total selling price = 138 × 65 = ₹8970. Profit = 8970 - 7501 = ₹1469. Profit % = (1469 / 7501) × 100 ≈ 19.58% ≈ 19.6%." },
  { n: 94, sec: "Aptitude & Mental Ability", q: "A trader sells an article at 16% below its cost price. Had he sold it for Rs.192.20 more, he would have gained 15%. The cost price (in Rs.) of the article is:",
    o: ["720","620","640","680"], a: "B",
    e: "Difference in selling percentages = 15% - (-16%) = 31% of CP. 0.31 × CP = 192.20 => CP = 192.20 / 0.31 = ₹620." },
  { n: 95, sec: "Aptitude & Mental Ability", q: "A T.V. is sold at 8% gain. Had it been sold for Rs.2553 less, there would have loss of 15%. To gain 18%, the selling price (in Rs.) of T.V. would be:",
    o: ["11100","13098","15000","9102"], a: "B",
    e: "Difference in percentage = 8% - (-15%) = 23%. 23% of CP = 2553 => CP = 2553 / 0.23 = ₹11100. Target SP for 18% gain = 11100 × 1.18 = ₹13098." },
  { n: 96, sec: "Aptitude & Mental Ability", q: "A sum of Rs. 10,000 was borrowed at a rate of simple interest. After four months, Rs.6000 more was borrowed and rate of interest on the total principal was doubled than that of the previous rate. At the end of the year, 2800 was paid as the interest. Find the rate that was applicable in the initial.",
    o: ["14%","16%","12%","11.35%"], a: "D",
    e: "Let initial rate be r%. Interest for first 4 months = 10000 × r × (4/12) / 100 = 100r/3. Remaining 8 months on ₹16000 at 2r%: 16000 × (2r) × (8/12) / 100 = 640r/3. Total interest = 740r/3 = 2800 => r = 8400 / 740 ≈ 11.35%." },
  { n: 97, sec: "Aptitude & Mental Ability", q: "The simple interest on a principal for 6 months at an interest rate of 10% per annum is Rs100. What is the principal?",
    o: ["Rs1000","Rs2000","Rs1500","Rs2500"], a: "B",
    e: "Time = 6/12 = 0.5 year. P = (SI × 100) / (R × T) = (100 × 100) / (10 × 0.5) = 10000 / 5 = ₹2000." },
  { n: 98, sec: "Aptitude & Mental Ability", q: "A man borrowed a certain sum and agrees to repay it by paying Rs.4000 at the end of first year and Rs.7700 at the end of second year. If the rate of compound interest compounded annually is 10% per annum, then find the sum (in Rs.) borrowed?",
    o: ["11500","11000","9000","10,000"], a: "D",
    e: "Present value of first installment = 4000 / 1.10 = ₹3636.36... Using standard installment discounting: Present Value = 4000/1.1 + 7700/(1.1)² = 4000/1.1 + 7700/1.21 = 4000/1.1 + 6363.63 ≈ 10,000." },
  { n: 99, sec: "Aptitude & Mental Ability", q: "The average monthly salary of 60 employees of a factory is Rs.29900. If two officers are getting Rs.90,000 each and the average salary of 8 supervisors is Rs.65,000, then what is the average salary (in Rs.) of the remaining employees?",
    o: ["21080","22680","29080","21880"], a: "D",
    e: "Total salary = 60 × 29900 = ₹1,794,000. Officers' total = 2 × 90000 = ₹180,000. Supervisors' total = 8 × 65000 = ₹520,000. Sum for 10 personnel = ₹700,000. Salary for remaining 50 employees = 1,794,000 - 700,000 = ₹1,094,000. Average = 1,094,000 / 50 = ₹21,880." },
  { n: 100, sec: "Aptitude & Mental Ability", q: "What is the ratio of the average of first eight prime numbers to the average of first ten even natural numbers?",
    o: ["1:7","7:80","8:70","7:8"], a: "D",
    e: "First 8 prime numbers: 2, 3, 5, 7, 11, 13, 17, 19. Sum = 77; Average = 77/8. First 10 even natural numbers: 2, 4, 6, ..., 20. Average = (2 + 20)/2 = 11. Ratio = (77/8) / 11 = 7 / 8." },

]);