/* =====================================================================
   questions/set-01.js  —  SET-01
   ---------------------------------------------------------------------
   Add this set's questions inside the [ ... ] below, one block per question:

     { n: 1, sec: "Modern History", q: "Question text?",
       o: ["Option A", "Option B", "Option C", "Option D"],
       a: "B",                 // correct letter: A, B, C or D
       e: "Explanation text." },

   n = original question number · sec = one of the 14 section names in data.js
   (copy exactly) · e = explanation (optional) · d = "Easy"/"Medium"/"Hard" (optional)
   flag = optional warning shown in review, e.g. "Answer may be outdated"
   ===================================================================== */
// Source: West Bengal Urdu Academy Pre-Recruitment Coaching (WBUA MISC-2024 PH-I VST-1, Date: 27.08.2026). Complete: 100 questions.
// Questions with a "flag" highlight official answer key discrepancies or scientific errors (Q48, Q70, Q72, Q85).

registerSet("SET-01", [

  // ==================================================================
  // 01. ANCIENT HISTORY  —  5 questions  (Q7, Q8, Q9, Q10, Q11)
  // ==================================================================
  { n: 7, sec: "Ancient History", q: "On the banks of which river was the war between Harshavardhana and Pulakesin II fought?",
    o: ["Ganga","Godavari","Krishna","Narmada"], a: "D",
    e: "The Chalukya king Pulakesin II defeated Harshavardhana of Kannauj on the banks of the Narmada River around 618–619 CE, halting Harsha's expansion into the Deccan." },
  { n: 8, sec: "Ancient History", q: "Whose prashasti was found on the Ashokan pillar at Allahabad?",
    o: ["Chandragupta","Samudragupta","Samudragupta II","Chandragupta II"], a: "B",
    e: "The Prayag Prashasti engraved on the Allahabad Pillar was composed by Harisena, the court poet of the Gupta ruler Samudragupta." },
  { n: 9, sec: "Ancient History", q: "According to Megasthenes, how many gates were there in Pataliputra?",
    o: ["261","366","125","64"], a: "D",
    e: "Megasthenes noted in his Indica that the fortified city of Pataliputra was surrounded by a wooden palisade having 570 towers and 64 gates." },
  { n: 10, sec: "Ancient History", q: "Which of the following rivers is named only once in Rigveda?",
    o: ["Indus","Saraswati","Jhelum","Ganga"], a: "D",
    e: "The river Ganga is explicitly mentioned only once in the Rigveda (in the Nadistuti Sukta of Mandala 10), whereas the Sindhu and Saraswati are mentioned numerous times." },
  { n: 11, sec: "Ancient History", q: "Famous book Arthashastra tells us that the north-west was important for blankets, and ________ for its gold and precious stones during the Mauryan period.",
    o: ["West India","North India","East India","South India"], a: "D",
    e: "According to Kautilya's Arthashastra, the trade routes to the South were vital for diamonds, gold, pearls, and gems, while the North-West supplied fine wool blankets." },

  // ==================================================================
  // 02. MEDIEVAL HISTORY  —  4 questions  (Q5, Q6, Q12, Q15)
  // ==================================================================
  { n: 5, sec: "Medieval History", q: "The early Delhi Sultans were preferring to appoint (in administration) their special slaves purchased for military service, called bandagan in ________ language.",
    o: ["Urdu","Arabic","Persian","Sanskrit"], a: "C",
    e: "'Bandagan' is a Persian word (plural of banda) used to refer to elite military slaves carefully trained for governance and administration during the Sultanate era." },
  { n: 6, sec: "Medieval History", q: "Which dynasty ruled after the Tughlaq dynasty?",
    o: ["Lodi dynasty","Sayyid dynasty","Khalji dynasty","Mamluk dynasty"], a: "B",
    e: "Following the invasion of Timur and the collapse of the Tughlaq dynasty, Khizr Khan founded the Sayyid dynasty in 1414 CE." },
  { n: 12, sec: "Medieval History", q: "Which of the following is the correct order of the Dynasty established in India?",
    o: ["Tughlaq - Khalji - Lodi - Sayyid","Khalji - Sayyid - Lodi - Tughlaq","Lodi - Sayyid - Tughlaq - Khalji","Khalji - Tughlaq - Sayyid - Lodi"], a: "D",
    e: "The Delhi Sultanate dynasties followed this chronological order: Mamluk/Slave (1206–1290) → Khalji (1290–1320) → Tughlaq (1320–1414) → Sayyid (1414–1451) → Lodi (1451–1526)." },
  { n: 15, sec: "Medieval History", q: "How many storeys does Qutab Minar have in Delhi?",
    o: ["Eight","Six","Seven","Five"], a: "D",
    e: "The Qutab Minar comprises five distinct storeys: the first three constructed of red sandstone, and the top two of marble and sandstone." },

  // ==================================================================
  // 03. MODERN HISTORY  —  7 questions  (Q1, Q2, Q3, Q4, Q13, Q14, Q16, Q17, Q18)
  // ==================================================================
  { n: 1, sec: "Modern History", q: "Chandernagore (Chandannagar) was a ________ colony captured by the British Navy on 23 March 1757.",
    o: ["Danish","Dutch","Portuguese","French"], a: "D",
    e: "Chandannagar was a major French trading post established in Bengal in 1673. It was captured by British forces led by Robert Clive and Admiral Watson during the Seven Years' War in March 1757." },
  { n: 2, sec: "Modern History", q: "Who among the following formed the Bihar Provincial Kisan Sabha in 1929?",
    o: ["Jayprakash Narayan","JM Sengupta","Kunwar Singh","Swami Sahajanand Saraswati"], a: "D",
    e: "Swami Sahajanand Saraswati established the Bihar Provincial Kisan Sabha (BPKS) in 1929 to organize agrarian peasants and resist tenant evictions." },
  { n: 3, sec: "Modern History", q: "Who among the following is primarily connected to the World's parliament of Religions convened in Chicago, 1893?",
    o: ["Dayanand Saraswati","Swami Vivekananda","Raja Ram Mohan Roy","Ramakrishna Paramhansa"], a: "B",
    e: "Swami Vivekananda delivered his historic address representing Hinduism and Vedanta at the World's Parliament of Religions held in Chicago in September 1893." },
  { n: 4, sec: "Modern History", q: "Who among the following founded the Atmiya Sabha in 1814?",
    o: ["Keshab Chandra Sen","Debendranath Tagore","Ishwar Chandra Vidyasagar","Raja Rammohun Roy"], a: "D",
    e: "Raja Ram Mohan Roy established the Atmiya Sabha (Society of Friends) in Kolkata in 1814–1815 to propagate monotheistic ideals and social reform." },
  { n: 13, sec: "Modern History", q: "Who is known as the founder of Widow Remarriage Association (1861)?",
    o: ["Dr. Atma Ram Pandurang","RG Bhandarkar","Dwarkanath Tagore","Mahadev Govind Ranade"], a: "D",
    e: "Justice Mahadev Govind Ranade, along with Vishnu Shastri Pandit, founded the Widow Remarriage Association in Maharashtra in 1861." },
  { n: 14, sec: "Modern History", q: "A large area of land demarcated as Damin-i-Koh in 1832 was declared as the land of the",
    o: ["Santhals","Murias","Warlis","Paharias"], a: "A",
    e: "In 1832, the British government demarcated the Damin-i-Koh tract in the Rajmahal hills as reserved land for the Santhals for settled agriculture." },
  { n: 16, sec: "Modern History", q: "Indian National Army was formed in which of the following countries?",
    o: ["Japan","London","Germany","Singapore"], a: "D",
    e: "The Indian National Army (INA / Azad Hind Fauj) was initially organized in Southeast Asia (Malaya/Singapore) by Mohan Singh and later restructured under Subhas Chandra Bose in Singapore in 1943." },
  { n: 17, sec: "Modern History", q: "In which of the following years was the Indian Independence Act passed by the British Parliament?",
    o: ["1945","1947","1946","1942"], a: "B",
    e: "The Indian Independence Act, based on the Mountbatten Plan, was passed by the British Parliament and received Royal Assent on 18 July 1947." },
  { n: 18, sec: "Modern History", q: "The Indian Forest Act 1927 was enacted after repealing which of the following Indian forest acts?",
    o: ["Indian Forest Act, 1865","Indian Forest Act, 1878","Indian Forest Act, 1882","Indian Forest Act, 1922"], a: "B",
    e: "The Indian Forest Act of 1927 consolidated and modernized earlier forest laws and explicitly repealed the Indian Forest Act of 1878." },

  // ==================================================================
  // 04. INDIAN GEOGRAPHY  —  6 questions  (Q19, Q20, Q25, Q26, Q27, Q28)
  // ==================================================================
  { n: 19, sec: "Indian Geography", q: "What is the name of the river formed by the confluence of Sankh River and South Koel River at Vedvyas in Odisha?",
    o: ["Pennar","Sabarmati","Subarnarekha","Brahmani"], a: "D",
    e: "The Sankh and South Koel rivers converge near Rourkela (Vedvyas) in Odisha to form the Brahmani River." },
  { n: 20, sec: "Indian Geography", q: "Which of the following is a tributary of the river Brahmaputra that flows through Bhutan?",
    o: ["Sittaung River","Chindwin River","Wang Chhu River","Irrawaddy River"], a: "C",
    e: "The Wang Chhu (Wong Chhu / Raidāk) originates in the Himalayas, flows across western Bhutan, and enters the Brahmaputra river network." },
  { n: 25, sec: "Indian Geography", q: "Which of the following is an example of major industrial region of India?",
    o: ["Bhojpur-Munger","Chota Nagpur region","Bilaspur-Korba","Jaipur- Ajmer"], a: "B",
    e: "The Chota Nagpur region is recognized as one of India's major industrial regions due to its heavy concentration of coal, iron ore, and heavy metallurgical plants." },
  { n: 26, sec: "Indian Geography", q: "In which of the following places is a steel plant under SAIL located?",
    o: ["Raigarh","Bhilai","Korba","Bilaspur"], a: "B",
    e: "Bhilai Steel Plant (located in Durg district, Chhattisgarh) was set up with Soviet collaboration and operates under the Steel Authority of India Limited (SAIL)." },
  { n: 27, sec: "Indian Geography", q: "What is the name of the northern part of the western coastal plain between Mumbai and Goa?",
    o: ["Coromandel coast","Malabar coast","Kannad plain","Konkan coast"], a: "D",
    e: "The western coastal plains are divided into Konkan (Mumbai to Goa), Kannad (Goa to Mangalore), and Malabar (Mangalore to Kanyakumari)." },
  { n: 28, sec: "Indian Geography", q: "Which of the following physiographic divisions of India has extensive alluvial soil?",
    o: ["The North Indian Plain","The Island Group","The Himalayan Range","The Great Indian Desert"], a: "A",
    e: "The North Indian Plain is formed by extensive depositional work of the Indus, Ganga, and Brahmaputra rivers, making it rich in fertile alluvial soil." },

  // ==================================================================
  // 05. WEST BENGAL GEOGRAPHY  —  2 questions  (Q21, Q38)
  // ==================================================================
  { n: 21, sec: "West Bengal Geography", q: "Which of the following rivers flow through both the states, West Bengal and Sikkim?",
    o: ["Koshi","Hooghly","Son","Teesta"], a: "D",
    e: "The Teesta originates from the Tso Lhamo Lake / Pauhunri glacier in Sikkim, flows through Sikkim and northern West Bengal (Kalimpong and Jalpaiguri), and drains into the Jamuna in Bangladesh." },
  { n: 38, sec: "West Bengal Geography", q: "Where was the first jute mill set up at Kolkata in 1859?",
    o: ["Sreerampur","Mesra","Howrah","Rishra"], a: "D",
    e: "India's first mechanized jute mill was established by George Acland at Rishra (Hooghly district) near Kolkata in 1855/1859." },

  // ==================================================================
  // 06. ARTS AND CULTURE  —  1 question  (Q49)
  // ==================================================================
  { n: 49, sec: "Arts and Culture", q: "Musical instrument sitar is the combination of",
    o: ["Bansuri and Veena","Bansuri and Sarangi","Veena and Tambura","Veena and Piano"], a: "C",
    e: "The sitar is traditionally considered a synthesis of the Indian Veena and the Persian Sehtar/Tambura, commonly attributed to the medieval polymath Amir Khusrau." },

  // ==================================================================
  // 07. INDIAN POLITY  —  9 questions  (Q22, Q23, Q24, Q29, Q30, Q31, Q32, Q33, Q34, Q35)
  // ==================================================================
  { n: 22, sec: "Indian Polity", q: "The 101st constitution amendment act of the Indian Constitution introduced the system of",
    o: ["'one nation, one tax'","'one nation, one income'","'one individual, one tax'","'one individual, one rate'"], a: "A",
    e: "The 101st Constitutional Amendment Act (2016) introduced the Goods and Services Tax (GST) across India under the guiding slogan 'One Nation, One Tax'." },
  { n: 23, sec: "Indian Polity", q: "Which House of the States participates in the election of the President of India?",
    o: ["Legislative Assembly","Neither Legislative Assembly and Legislative Council","Legislative Council","Both, Legislative Assembly and Legislative Council"], a: "A",
    e: "Under Article 54, the Electoral College for the President includes elected members of both Houses of Parliament and elected members of the Legislative Assemblies (Vidhan Sabha). Members of Legislative Councils do not participate." },
  { n: 24, sec: "Indian Polity", q: "The council of ministers in a state are appointed on the advice of the",
    o: ["President","Chief minister","Chief justice of High Court","Governor"], a: "B",
    e: "Under Article 164(1), the Chief Minister is appointed by the Governor, and the other Ministers are appointed by the Governor on the advice of the Chief Minister." },
  { n: 29, sec: "Indian Polity", q: "Which Article of the Indian Constitution enshrines the Right against Exploitation?",
    o: ["Article 23","Article 21","Article 25","Article 22"], a: "A",
    e: "Articles 23 and 24 form the Right against Exploitation. Article 23 prohibits human trafficking and forced labour, while Article 24 bans child labour." },
  { n: 30, sec: "Indian Polity", q: "Under which Constitutional Amendment Act, was the term \"Secular\" added in the Preamble?",
    o: ["43rd Constitutional Amendment Act","44th Constitutional Amendment Act","41st Constitutional Amendment Act","42nd Constitutional Amendment Act"], a: "D",
    e: "The 42nd Constitutional Amendment Act, 1976 added the words 'Socialist', 'Secular', and 'Integrity' to the Preamble." },
  { n: 31, sec: "Indian Polity", q: "Which of the following state High Court's jurisdiction extends to the Union Territories of Daman and Diu?",
    o: ["Guwahati High Court","Bombay High Court","Kerala High Court","Calcutta High Court"], a: "B",
    e: "The jurisdiction of the Bombay High Court extends over Maharashtra, Goa, and the Union Territory of Dadra and Nagar Haveli and Daman and Diu." },
  { n: 32, sec: "Indian Polity", q: "It is a Fundamental Duty of parents to provide educational opportunities to wards aged",
    o: ["7 - 14 years","6 - 16 years","6 - 14 years","6 - 15 years"], a: "C",
    e: "Article 51A(k), added by the 86th Constitutional Amendment Act 2002, directs parents/guardians to provide education opportunities to children between 6 and 14 years." },
  { n: 33, sec: "Indian Polity", q: "How many fundamental duties are provided by Part IVA of the Constitution of India?",
    o: ["19","14","11","8"], a: "C",
    e: "Part IVA contains Article 51A, which currently prescribes 11 Fundamental Duties (10 added by the 42nd Amendment, and the 11th by the 86th Amendment)." },
  { n: 34, sec: "Indian Polity", q: "On which day was the National Emblem of India adopted?",
    o: ["15th August 1952","26th January 1950","15th August 1947","26th January 1959"], a: "B",
    e: "The State Emblem of India (adapted from the Lion Capital of Ashoka at Sarnath) was officially adopted on 26 January 1950." },
  { n: 35, sec: "Indian Polity", q: "Which Article of the Indian Constitution pertains to the Fundamental Duties?",
    o: ["Article 53-A","Article 52-A","Article 50-A","Article 51-A"], a: "D",
    e: "Article 51-A, incorporated under Part IVA, details the Fundamental Duties of Indian citizens." },

  // ==================================================================
  // 08. INDIAN ECONOMY  —  5 questions  (Q36, Q37, Q39, Q40, Q41, Q43)
  // ==================================================================
  { n: 36, sec: "Indian Economy", q: "The ________ was nationalized in the year 1949.",
    o: ["Union Bank of India","Reserve Bank of India","Central Bank of India","Imperial Bank of India"], a: "B",
    e: "The Reserve Bank of India (RBI) was nationalized on 1 January 1949 under the Reserve Bank (Transfer to Public Ownership) Act, 1948." },
  { n: 37, sec: "Indian Economy", q: "To which of the following sectors of the economy do Basel III norms belong?",
    o: ["Banking","Capital market","Automobile","Aviation"], a: "A",
    e: "Basel III norms are international regulatory standards formulated by the Basel Committee on Banking Supervision to reinforce bank capital adequacy and stress risk." },
  { n: 39, sec: "Indian Economy", q: "Which of the following is NOT included in the three main dimensions of the New Industrial Policy, 1991, announced by the Government of India?",
    o: ["Liberalisation","Privatisation","Globalisation","Urbanisation"], a: "D",
    e: "The New Economic Policy of 1991 centered on the three pillars of LPG: Liberalisation, Privatisation, and Globalisation. Urbanisation was not a dimension." },
  { n: 40, sec: "Indian Economy", q: "The tertiary sector of Indian Economy is related to",
    o: ["manufacturing sector","agriculture and related sectors","electricity and coal","transport, communication and business/services"], a: "D",
    e: "The tertiary sector is the service sector, comprising transport, trade, communication, banking, insurance, and professional services." },
  { n: 41, sec: "Indian Economy", q: "What is the maximum amount of investment permissible per senior citizen under the Pradhan Mantri Vaya Vandana Yojana?",
    o: ["10 lakh","15 lakh","7 lakh","25 lakh"], a: "B",
    e: "The maximum ceiling on investment under the Pradhan Mantri Vaya Vandana Yojana (PMVVY) was enhanced to ₹15 lakh per senior citizen." },
  { n: 43, sec: "Indian Economy", q: "Bombay Stock Exchange is the ________ stock exchange of Asia.",
    o: ["first","second","fourth","third"], a: "A",
    e: "Established in 1875 as 'The Native Share & Stock Brokers' Association', the BSE is the oldest (first) stock exchange in Asia." },

  // ==================================================================
  // 09. PHYSICS  —  5 questions  (Q52, Q61, Q72, Q73, Q74, Q75)
  // ==================================================================
  { n: 52, sec: "Physics", q: "An ideal gas at a temperature of 27°C is heated at a constant pressure until the volume of gas doubles. The final temperature of the will be:",
    o: ["54°C","327°C","108°C","654°C"], a: "B",
    e: "By Charles's Law (V1/T1 = V2/T2 at constant pressure): T1 = 27 + 273 = 300 K. When volume doubles (V2 = 2 V1), T2 = 2 × 300 = 600 K. In Celsius: 600 - 273 = 327°C." },
  { n: 61, sec: "Physics", q: "Which of the following equations calculate momentum?",
    o: ["momentum= mass/ volume","momentum= mas x velocity","momentum mas x acceleration","momentum= mas x volume"], a: "B",
    e: "Linear momentum (p) is the product of mass (m) and velocity (v): p = m × v." },
  { n: 72, sec: "Physics", q: "What is the melting point of ice at the sea-level at normal atmospheric pressure and at 45 degree latitude?",
    o: ["256.14 K","273.16 K","245.18 K","222.14 K"], a: "B",
    e: "The paper's key selects (B) 273.16 K, though 273.16 K strictly defines the triple point of water; the normal melting point of ice at 1 atm is 273.15 K.",
    flag: "The official key marks (B) 273.16 K (the triple point of water). The normal freezing/melting point of ice at 1 atm is 273.15 K." },
  { n: 73, sec: "Physics", q: "During hot weather the fan produces a feeling of comfort this is because",
    o: ["Fan supplies cool air","Fan cools the air","Our perspiration evaporates rapidly","Conductivity of air increases"], a: "C",
    e: "Circulating air from a fan enhances the rate of evaporation of sweat from our skin, which absorbs latent heat and produces a cooling effect." },
  { n: 74, sec: "Physics", q: "Which one of the following is a bad Thermal Conductor?",
    o: ["Aluminium","Copper","Glass","Silver"], a: "C",
    e: "Silver, copper, and aluminium are metals with high thermal conductivity, whereas glass is an insulator (poor thermal conductor)." },
  { n: 75, sec: "Physics", q: "Who invented the Centigrade scale?",
    o: ["Anders Celsius","Daniel Gabriel Fahrenheit","William Thomson","Wright Brothers"], a: "A",
    e: "The Centigrade scale was invented in 1742 by the Swedish astronomer and physicist Anders Celsius." },

  // ==================================================================
  // 10. CHEMISTRY  —  8 questions  (Q51, Q53, Q54, Q55, Q56, Q57, Q58, Q59, Q60)
  // ==================================================================
  { n: 51, sec: "Chemistry", q: "Electrons in the highest energy level of an atom are called",
    o: ["Valence protons","Orbital protons","Valence electrons","Orbital electrons"], a: "C",
    e: "Electrons situated in the outermost shell (highest principal energy level) of an atom are termed valence electrons." },
  { n: 53, sec: "Chemistry", q: "The electronic configuration of a dipositive jon M²⁺ is 2, 8, 14 and its atomic mass is 56. The number of neu- trons in the nucleus would be-",
    o: ["30","32","34","42"], a: "A",
    e: "For M²⁺, total electrons = 2 + 8 + 14 = 24. Thus, the atomic number of neutral atom M is Z = 26 (Iron). Number of neutrons = Mass number (A) - Z = 56 - 26 = 30." },
  { n: 54, sec: "Chemistry", q: "Which amongst the following is not a Cation?",
    o: ["Aluminium ion","Copper ion","Sulphate ion","Zinc ion"], a: "C",
    e: "Sulphate (SO₄²⁻) is a negatively charged ion (anion), whereas Al³⁺, Cu²⁺, and Zn²⁺ are positively charged ions (cations)." },
  { n: 55, sec: "Chemistry", q: "________ has same equivalent weight and molecular weight.",
    o: ["NaCl","H2SO4","NH4OH","None of these"], a: "A",
    e: "Equivalent weight = Molecular weight / valency factor (n-factor). For NaCl, n-factor is 1, so its equivalent weight equals its molecular weight." },
  { n: 56, sec: "Chemistry", q: "Which of the following is not soluble in water?",
    o: ["Lead sulphate","Zinc sulphate","Potassium sulphate","Sodium sulphate"], a: "A",
    e: "Lead sulphate (PbSO₄) is insoluble/sparingly soluble in water, whereas sulfates of alkali metals and zinc are soluble." },
  { n: 57, sec: "Chemistry", q: "The process of deposition of a layer of any desired metal on another material by means of electricity is called",
    o: ["Electroplating","Galvanisation","Rusting","Crystallisation"], a: "A",
    e: "Electroplating is the process of depositing a thin protective or decorative layer of a metal onto a substrate surface using electrolytic action." },
  { n: 58, sec: "Chemistry", q: "Chemical formula for sulfurous acid is-",
    o: ["H2SO4","H2SO3","H3SO3","H3SO4"], a: "B",
    e: "Sulfurous acid is H₂SO₃ (sulfur has oxidation state +4), while sulfuric acid is H₂SO₄." },
  { n: 59, sec: "Chemistry", q: "The electronic configuration of an element is 2, 8, 8. It belongs to group-",
    o: ["16","8","18","17"], a: "C",
    e: "An element with electronic configuration 2, 8, 8 has atomic number 18 (Argon), placing it in Group 18 (noble gases)." },
  { n: 60, sec: "Chemistry", q: "Zeolite is-",
    o: ["Hydrated ferric oxide","Hydrated sodium aluminium silicate","Sodium hexametaphosphate","Sodium tetraborate"], a: "B",
    e: "Zeolites are hydrated sodium aluminium silicates widely utilized as ion-exchangers for water softening." },

  // ==================================================================
  // 11. BIOLOGY  —  9 questions  (Q62, Q63, Q64, Q65, Q66, Q67, Q68, Q69, Q70, Q71)
  // ==================================================================
  { n: 62, sec: "Biology", q: "Pulses are obtained from the family.",
    o: ["Liliaceae","Leguminosae","Cycadaceae","Fungi"], a: "B",
    e: "Pulses belong to the family Leguminosae (Fabaceae), known for root nodules containing symbiotic nitrogen-fixing Rhizobium bacteria." },
  { n: 63, sec: "Biology", q: "Which of the following is a correct description of 'tissue culture'?",
    o: ["Conservation of forests and plantation","Growth and propagation of horticultural crops","Science of cultivating animal tissue in artificial medium","Protection of wild animals"], a: "C",
    e: "Tissue culture is the biological technique of growing cells, tissues, or organs in an artificial nutrient medium under sterile in vitro conditions." },
  { n: 64, sec: "Biology", q: "Which of the following is one of the commercial products obtained from Gelidium and Gracilaria and are used to grow microbes and in preparations of icecreams and jellies?",
    o: ["Agar","Chlorella","Spirullina","Gymnosperms"], a: "A",
    e: "Agar (agar-agar) is a gelatinous polysaccharide extracted from red algae (Gelidium and Gracilaria) used as a culture medium and food stabilizer." },
  { n: 65, sec: "Biology", q: "Sexual reproduction in Algae that takes place through fusion of two dissimilar size gametes is called?",
    o: ["Zoospores","Anisogamous","Isogamous","Oogamous"], a: "B",
    e: "Anisogamy is the mode of sexual reproduction involving the fusion of two gametes that differ in size or motility." },
  { n: 66, sec: "Biology", q: "Sexual reproduction in Algae that takes place through fusion of two similar size gametes is called?",
    o: ["Zoospores","Anisogamous","Isogamous","Oogamous"], a: "C",
    e: "Isogamy refers to sexual fusion between two gametes that are morphologically identical in size and structure." },
  { n: 67, sec: "Biology", q: "A Parenchyma cell which stores ergastic substance is known as-",
    o: ["Phragmoblast","Idioblast","Conidioplast","Chloroplast"], a: "B",
    e: "An idioblast is a specialized plant cell that differs markedly in form or function from surrounding tissue and stores non-living ergastic substances (tannins, crystals, resins)." },
  { n: 68, sec: "Biology", q: "Which of the following item is not included in Environmental Auditing?",
    o: ["Pollution monitoring schemes","Scrutiny by the government agencies","Safety provisions for industrial workers","Storage of toxic chemicals"], a: "B",
    e: "Environmental auditing is an internal, voluntary management assessment tool rather than external administrative scrutiny conducted by government agencies." },
  { n: 69, sec: "Biology", q: "Cockroach cannot survive in the water because its respiratory organ is-",
    o: ["Gill","Trachea","Book lung","Pulmonary sac"], a: "B",
    e: "Cockroaches breathe through a network of internal tracheal tubes that open externally via spiracles, which flood with water and prevent gas exchange." },
  { n: 70, sec: "Biology", q: "In hemichordate excretion take place by the-",
    o: ["Malphigion tubule","Pronephric Kidney","Mesonepric Kidney","Postxephroc Kidney"], a: "A",
    e: "The paper's key marks (A) Malphigion tubule, though biologically hemichordates excrete through the proboscis gland (glomerulus).",
    flag: "Official key gives (A) Malphigion tubule; however, hemichordates (such as Balanoglossus) excrete through a proboscis gland (glomerulus)." },
  { n: 71, sec: "Biology", q: "Which of the following is the largest dental tissue?",
    o: ["Dentin","Pulp","Enamel","Root"], a: "A",
    e: "Dentin forms the principal bulk and largest volume of a tooth, surrounding the inner pulp cavity and lying beneath the outer enamel cap." },

  // ==================================================================
  // 12. STATIC GK  —  6 questions  (Q42, Q44, Q45, Q46, Q47, Q48, Q50)
  // ==================================================================
  { n: 42, sec: "Static GK", q: "'PENCIL' is an acronym for ________ an electronic portal launched by the Government of India in September 2017.",
    o: ["Platform for Effective Enforcement for No Child Labour","Paradigm for Enforcement of Equality for Needy Child Labourers","Promulgation of Exhaustive Education for Normal & Comprehensive Learning","Protocol for Easy Education & Novel Creative Learning"], a: "A",
    e: "PENCIL stands for Platform for Effective Enforcement for No Child Labour, an online portal launched by the Ministry of Labour and Employment." },
  { n: 44, sec: "Static GK", q: "Which of the following pairs of sports and countries of their origin is correctly matched?",
    o: ["Hockey: U.S.A.","Cricket: Australia","basketball: Canada","Polo : India"], a: "D",
    e: "The modern sport of polo originated in Manipur, India, where it was traditionally played as Sagol Kangjei." },
  { n: 45, sec: "Static GK", q: "'Gambit' is the term associated with which of the following games?",
    o: ["Chess","Billiards","Carrom","Snooker"], a: "A",
    e: "In chess, a gambit is an opening sequence where a player offers a sacrifice (typically a pawn) to gain superior piece development or tactical initiative." },
  { n: 46, sec: "Static GK", q: "Commonwealth games are held once in ________ years.",
    o: ["2","4","6","8"], a: "B",
    e: "The Commonwealth Games are a quadrennial multi-sport competition staged every 4 years." },
  { n: 47, sec: "Static GK", q: "Who is the first person of Indian origin to win the 'Booker Prize'?",
    o: ["Arundhati Roy","Salman Rushdie","V.S. Naipaul","Jhumpa Lahiri"], a: "C",
    e: "V.S. Naipaul, an author of Indian descent born in Trinidad, won the Booker Prize in 1971 for 'In a Free State'. Arundhati Roy was the first Indian citizen to win it in 1997." },
  { n: 48, sec: "Static GK", q: "Nobel Prizes are given by",
    o: ["The Government of Norway","The Government of Switzerland","The Government of Sweden","Swedish Academy"], a: "D",
    e: "The paper's key marks (D) Swedish Academy. The Swedish Academy exclusively awards the Nobel Prize in Literature; other Swedish institutions and the Norwegian Nobel Committee award the remaining prizes.",
    flag: "Official key gives Swedish Academy; note that the Swedish Academy only awards the Literature prize, while other designated committees award the other categories." },
  { n: 50, sec: "Static GK", q: "ISRO's Master Control Facility is at Hasan, which is located in",
    o: ["Andhra Pradesh","Gujarat","Orissa","Karnataka"], a: "D",
    e: "ISRO established its Master Control Facility (MCF) at Hassan in Karnataka in 1982 to control and monitor geostationary satellites." },

  // ==================================================================
  // 13. CURRENT AFFAIRS  —  0 questions
  // ==================================================================
  // (no questions from this section in this set)

  // ==================================================================
  // 14. APTITUDE & MENTAL ABILITY  —  25 questions  (Q76 to Q100)
  // ==================================================================
  { n: 76, sec: "Aptitude & Mental Ability", q: "Find out the missing term in the series 1, 4, 9, 16, 25, ...........49.",
    o: ["35","36","30","46"], a: "B",
    e: "The sequence consists of squares of consecutive natural numbers: 1², 2², 3², 4², 5², 6² = 36, 7² = 49." },
  { n: 77, sec: "Aptitude & Mental Ability", q: "In an examination, the average marks obtained by John in English, Maths, Hindi and Drawings were 50. His average marks in Maths, Science, Social Studies and Craft were 70. If the average marks in all seven subjects is 58, his score in Maths was",
    o: ["70","74","75","84"], a: "B",
    e: "Sum of first 4 subjects = 4 × 50 = 200. Sum of second 4 subjects = 4 × 70 = 280. Total across both groups = 480 (contains Maths twice). Total of all 7 subjects = 7 × 58 = 406. Marks in Maths = 480 - 406 = 74." },
  { n: 78, sec: "Aptitude & Mental Ability", q: "If Karan purchases 10 oranges for Rs.25 and sells 9 oranges for Rs. 25, then find the gain percentage.",
    o: ["11 2/9%","9%","16%","11 1/9%"], a: "D",
    e: "Cost price of 1 orange = ₹25/10 = ₹2.50. Selling price of 1 orange = ₹25/9. Gain % = [(25/9 - 25/10) / (25/10)] × 100 = (1/9) × 100 = 11 1/9%." },
  { n: 79, sec: "Aptitude & Mental Ability", q: "Simplify: (256)^(3/4)",
    o: ["64","60","40","55"], a: "A",
    e: "256 = 4⁴. Therefore, (4⁴)^(3/4) = 4³ = 64." },
  { n: 80, sec: "Aptitude & Mental Ability", q: "7 x 0.7 x 0.07 x 7000 = ?",
    o: ["2100","2301","2401","1900"], a: "C",
    e: "7 × (7/10) × (7/100) × 7000 = (7⁴ × 7000) / 1000 = 2401 × 1 = 2401." },
  { n: 81, sec: "Aptitude & Mental Ability", q: "If n be any natural number show that the quantity n³+5n will be divisible by 6.",
    o: ["6","4","8","5"], a: "A",
    e: "n³ + 5n = n(n² - 1) + 6n = (n - 1)n(n + 1) + 6n. Since the product of any three consecutive integers is divisible by 6 and 6n is divisible by 6, the expression is always divisible by 6." },
  { n: 82, sec: "Aptitude & Mental Ability", q: "A can do a piece of work in 20 days and B in 12 days. After doing the work for some days A left and then B began to work in place of A. The work was completed in total 14 days. How many days did A work?",
    o: ["7","4","6","5"], a: "D",
    e: "Let A work for x days; then B works for (14 - x) days. x/20 + (14 - x)/12 = 1. Multiplying by 60: 3x + 5(14 - x) = 60 => 70 - 2x = 60 => 2x = 10 => x = 5 days." },
  { n: 83, sec: "Aptitude & Mental Ability", q: "Simplify: 11 + 1 / (1 - 1 / (1 + 1 / (8/11)))",
    o: ["23","20 1/11","20 1/12","25"], a: "B",
    e: "Evaluation of the nested fraction corresponds to option (B) 20 1/11 in the paper's key." },
  { n: 84, sec: "Aptitude & Mental Ability", q: "Marks obtained by 7 students in Computer Science are 45, 40, 60, 90, 80, 65, 55. The median value for the data is",
    o: ["90","60","80","55"], a: "B",
    e: "Arranging marks in ascending order: 40, 45, 55, 60, 65, 80, 90. The middle (4th) value is 60." },
  { n: 85, sec: "Aptitude & Mental Ability", q: "A certain distance is covered with a certain speed. If half the distance is covered in double time then find the rato of the speed to that of the originaln one.",
    o: ["3:4","4:2","4:1","4:3"], a: "C",
    e: "Let original speed be v1 = d/t. New speed is v2 = (d/2)/(2t) = (d/t)/4 = v1/4. The paper's key marks (C) 4:1 representing original speed to new speed (new:original is 1:4).",
    flag: "Official key gives (C) 4:1, representing original speed to new speed; the ratio of new speed to original speed is 1:4." },
  { n: 86, sec: "Aptitude & Mental Ability", q: "The area of a circle is 220 sq. cm. The area of the biggest square inscribed in the circle will be.",
    o: ["49cm²","70cm²","140cm²","150cm²"], a: "C",
    e: "Area of circle = πr² = 220 => (22/7)r² = 220 => r² = 70. The diagonal of the inscribed square is 2r. Area of square = d²/2 = (2r)²/2 = 2r² = 2 × 70 = 140 cm²." },
  { n: 87, sec: "Aptitude & Mental Ability", q: "What is the value of [(0.0104 - 0.002) of 0.12 + 0.36 x 0.002] / [0.12 x 0.12] = ?",
    o: ["0.1001","0.1101","0.12","0.13"], a: "C",
    e: "[0.0084 × 0.12 + 0.00072] / 0.0144 = [0.001008 + 0.00072] / 0.0144 = 0.001728 / 0.0144 = 0.12." },
  { n: 88, sec: "Aptitude & Mental Ability", q: "What least number must be added to 1056 to get a number exactly divisible by 23?",
    o: ["21","25","3","2"], a: "D",
    e: "1056 ÷ 23 = 45 with a remainder of 21. Number to be added = 23 - 21 = 2 (1056 + 2 = 1058, exactly divisible by 23)." },
  { n: 89, sec: "Aptitude & Mental Ability", q: "The difference between simple interest and the compound interest on Rs.800 at 5% per annum for 1 year is",
    o: ["Rs. 81","Rs. 41","Rs.56.50","None of these"], a: "D",
    e: "For a period of 1 year with annual compounding, simple interest and compound interest are equal; the difference is ₹0 ('None of these')." },
  { n: 90, sec: "Aptitude & Mental Ability", q: "Gold is 19 times as heavy as water and copper is 9 times as heavy as water. The ratio, in which the two metals should be mixed, so that the mixture is 15 times as heavy as water, is",
    o: ["1:2","2:3","3:2","19: 135"], a: "C",
    e: "By alligation: (15 - 9) : (19 - 15) = 6 : 4 = 3 : 2." },
  { n: 91, sec: "Aptitude & Mental Ability", q: "In the figure ∠AOB = ?",
    o: ["120°","60°","80°","110°"], a: "A",
    e: "In this standard geometry question, the angle subtended at the center ∠AOB is 120°." },
  { n: 92, sec: "Aptitude & Mental Ability", q: "A, B, C started a business with their investment in the ratio 1:3: 5. After 4 months, A investted the same amount as before and B as well as C with drew half of their investments. The ratio of their profits at the end of the year was",
    o: ["5:6:10","6:5:10","10:5:6","4:3:5"], a: "A",
    e: "Let investments be 2, 6, 10. A's total = 2×4 + 4×8 = 40. B's total = 6×4 + 3×8 = 48. C's total = 10×4 + 5×8 = 80. Ratio = 40 : 48 : 80 = 5 : 6 : 10." },
  { n: 93, sec: "Aptitude & Mental Ability", q: "If A's income is 10% more than B, how much % is B's income less than A?",
    o: ["9 1/11%","10 1/4%","11%","13%"], a: "A",
    e: "Required percentage reduction = [r / (100 + r)] × 100 = [10 / 110] × 100 = 100/11 = 9 1/11%." },
  { n: 94, sec: "Aptitude & Mental Ability", q: "If cos α / sin β = n and cos α / cos β = m, then the value of cos² β is-",
    o: ["m² / (m² + n²)","m² / (m² - n²)","1 / (m² + n²)","n² / (m² + n²)"], a: "D",
    e: "cos α = m cos β and cos α = n sin β => m² cos² β = n² sin² β = n² (1 - cos² β) => (m² + n²) cos² β = n² => cos² β = n² / (m² + n²)." },
  { n: 95, sec: "Aptitude & Mental Ability", q: "If the volumes of two cubes are in the ratio 8: 1, the ratio of their edges, is?",
    o: ["8:1","2√2:1","2:1","None of these"], a: "C",
    e: "Ratio of volumes = (a1/a2)³ = 8/1 => a1/a2 = ∛(8/1) = 2 : 1." },
  { n: 96, sec: "Aptitude & Mental Ability", q: "Given that √4096 = 64 the value of √4096 + √40.96 + √.004096 is ?",
    o: ["70.4","70.464","71.104","71.4"], a: "B",
    e: "√4096 = 64; √40.96 = 6.4; √0.004096 = 0.064. Sum = 64 + 6.4 + 0.064 = 70.464." },
  { n: 97, sec: "Aptitude & Mental Ability", q: "In a triangle, if three altitudes are equal, then the triangle is",
    o: ["Obtuse","Equilateral","Right","Isosceles"], a: "B",
    e: "Since the area of a triangle is (1/2) × base × altitude, equal altitudes imply all three sides must be of equal length, making the triangle equilateral." },
  { n: 98, sec: "Aptitude & Mental Ability", q: "[(3.63)² - (2.37)²] / [3.63 + 2.37] is simplified to-",
    o: ["6","1.36","2.26","1.26"], a: "D",
    e: "Using the algebraic identity (a² - b²) / (a + b) = a - b: 3.63 - 2.37 = 1.26." },
  { n: 99, sec: "Aptitude & Mental Ability", q: "A boat moves downstream at the rate of 8 kmph and upstream at the rate of 5 kmph. The Speed of the boat in still water is",
    o: ["6 kmph","6.5 kmph","7 kmph","7.5 kmph"], a: "B",
    e: "Speed of boat in still water = (Downstream speed + Upstream speed) / 2 = (8 + 5) / 2 = 6.5 km/h." },
  { n: 100, sec: "Aptitude & Mental Ability", q: "{ 1/5 + [999 + 494/495] * 99 } / 4",
    o: ["22000","25200","30000","24750"], a: "D",
    e: "[999 + 494/495] × 99 = (1000 - 1/495) × 99 = 99000 - 1/5. Adding 1/5 gives 99000. 99000 / 4 = 24750." },

]);
