/* =====================================================================
   questions/set-06.js  —  SET-06
   ---------------------------------------------------------------------
   Add this set's questions inside the [ ... ] below, one block per question:

     { n: 1, sec: "Modern History", q: "Question text?",
       o: ["Option A", "Option B", "Option C", "Option D"],
       a: "B",                 // correct letter: A, B, C or D
       e: "Explanation text." },

   n = original question number · sec = one of the 14 section names in data.js
   (copy exactly) · e = explanation (optional) · d = "Easy"/"Medium"/"Hard" (optional)
   flag = optional warning shown in review, e.g. "Answer may be outdated"
   ===================================================================== */
// Source: West Bengal Urdu Academy Pre-Recruitment Coaching (WBUA MISC-2024 PH-I VST-6, Date: 24.09.2026). Complete: 100 questions.
// Questions with a "flag" highlight official answer key discrepancies or ambiguous phrasing (Q50, Q75).

registerSet("SET-06", [

  // ==================================================================
  // 01. ANCIENT HISTORY  —  4 questions  (Q31, Q45, Q46, Q72)
  // ==================================================================
  { n: 31, sec: "Ancient History", q: "Which of the following inscriptions of Rudradaman happened to be the first royal inscription of early India composed in chaste Sanskrit?",
    o: ["Prayag","Girnar","Chirand","Mehrauli"], a: "B",
    e: "The Junagadh (Girnar) Rock Inscription of Western Kshatrapa ruler Rudradaman I (c. 150 CE) is celebrated as the earliest extensive royal record in classical Sanskrit." },
  { n: 45, sec: "Ancient History", q: "'Saptaparni Cave' is situated in",
    o: ["Sanchi","Nalanda","Rajgriha","Pawapuri"], a: "C",
    e: "Saptaparni Cave is located on the Vaibhava Hill in Rajgriha (modern Rajgir, Bihar), where the First Buddhist Council was convened under King Ajatashatru in 483 BCE." },
  { n: 46, sec: "Ancient History", q: "Who was Alara Kalama?",
    o: ["A disciple of Buddha","A distinguished Buddhist monk","A king of Buddha's time","A teacher of Buddha"], a: "D",
    e: "Alara Kalama was an ascetic hermit and philosopher who taught Gautama Buddha the techniques of meditation and the philosophy of the sphere of nothingness." },
  { n: 72, sec: "Ancient History", q: "Mahabalipuram emerged as an important centre of temple architecture under which of the following kingdoms of south India?",
    o: ["Pallava","Chola","Chera","Chalukya"], a: "A",
    e: "Mahabalipuram (Mamallapuram) developed into a thriving port and architectural center of monolithic rock-cut rathas and shore temples under the Pallava rulers, particularly Narasimhavarman I." },

  // ==================================================================
  // 02. MEDIEVAL HISTORY  —  1 question  (Q32)
  // ==================================================================
  { n: 32, sec: "Medieval History", q: "The first Southern campaign of Alauddin Khilji in 1307-08 AD was led to which of the following regions?",
    o: ["Devagiri","Warangal","Dwar Samudra","Madura"], a: "A",
    e: "Alauddin Khalji's first major Deccan campaign under the command of Malik Kafur in 1307–1308 was directed against Rai Ramachandra of Devagiri for defaulting on tribute." },

  // ==================================================================
  // 03. MODERN HISTORY  —  9 questions  (Q33, Q34, Q35, Q36, Q37, Q47, Q48, Q49, Q56)
  // ==================================================================
  { n: 33, sec: "Modern History", q: "Who of the following persons called Irwin and Gandhi 'The Two Mahatmas'?",
    o: ["Mira Bahan","Sarojini Naidu","Madan Mohan Malviya","Jawaharlal Nehru"], a: "B",
    e: "Sarojini Naidu referred to Lord Irwin and Mahatma Gandhi as 'The Two Mahatmas' following the negotiations leading to the Gandhi-Irwin Pact of March 1931." },
  { n: 34, sec: "Modern History", q: "'Harijan Sewak Sangh' was organized by",
    o: ["Mahatma Gandhi","Dr. B.R. Ambedkar","G.D. Birla","Swami Vivekananda"], a: "A",
    e: "Mahatma Gandhi established the All India Anti-Untouchability League (later renamed Harijan Sevak Sangh) in September 1932 to eradicate untouchability, with Ghanshyam Das Birla as its founding president." },
  { n: 35, sec: "Modern History", q: "Integration of States was done under the leadership of",
    o: ["Maulana Azad","Govind Ballabh Pant","B.R. Ambedkar","S. V. Patel"], a: "D",
    e: "Sardar Vallabhbhai Patel, as Minister of States along with Secretary V.P. Menon, orchestrated the diplomatic integration of over 560 princely states into the Indian Union." },
  { n: 36, sec: "Modern History", q: "Which one of the following is not correctly matched?",
    o: ["Prarthana Samaj: Dr. Atmaram Pandurang","Atmiya Sabha: Debendra Nath Tagore","Brahmo Samaj of india: Keshab Chandra Sen","Arya Samaj: Dayanand Saraswati"], a: "B",
    e: "Atmiya Sabha was founded by Raja Ram Mohan Roy in 1814–1815 in Kolkata; Debendranath Tagore founded the Tattwabodhini Sabha in 1839." },
  { n: 37, sec: "Modern History", q: "The Ilbert Bill controversy was related to the",
    o: ["Imposition of certain restrictions to carry arms by the Indians","Imposition of restrictions on newspapers and magazines published in Indian language","Removal of disqualifications imposed on the Indian Magistrates about the trial of the Europeans","Removal of duty on imported cotton cloth"], a: "C",
    e: "Introduced in 1883 under Viceroy Lord Ripon, the Ilbert Bill sought to grant Indian magistrates jurisdiction to try European British subjects in criminal cases, triggering fierce opposition from Anglo-Indians." },
  { n: 47, sec: "Modern History", q: "Which one of the following pairs is not correctly matched?",
    o: ["V.D. Savarkar: The Indian War of Independence","R.C. Majumdar: The Sepoy Mutiny and Revolt of 1857","Radha Kamal Mukherjee: Awadh in Revolt (1857-1858)","S.B. Chaudhari: Civil Rebellions in the Indian Mutinies"], a: "C",
    e: "'Awadh in Revolt (1857–1858): A Study of Popular Resistance' was authored by historian Rudrangshu Mukherjee, not Radha Kamal Mukherjee." },
  { n: 48, sec: "Modern History", q: "In which one of the following jails, the book 'Discovery of India' was written by Jawaharlal Nehru?",
    o: ["Alipur Central Jail","Yerwada Jail","Naini Central Jail","Ahmadnagar Fort Jail"], a: "D",
    e: "Jawaharlal Nehru wrote 'The Discovery of India' between 1942 and 1945 during his imprisonment at Ahmednagar Fort following the Quit India movement." },
  { n: 49, sec: "Modern History", q: "Who said, \"Political Freedom is the life breath of a nation\"?",
    o: ["Bal Gangadhar Tilak","Aurobindo Ghosh","Bipin Chandra Pal","Mahatma Gandhi"], a: "B",
    e: "Sri Aurobindo Ghosh wrote this in a series of articles on passive resistance published in the journal Bande Mataram in April 1907." },
  { n: 56, sec: "Modern History", q: "The Centre introduced a new bill called the Criminal Procedure (Identification) Bill 2022. This bill will repeal the Identification of Prisoners Act which was established in",
    o: ["1930","1950","1945","1920"], a: "D",
    e: "The Criminal Procedure (Identification) Act, 2022 repealed and replaced the colonial Identification of Prisoners Act, 1920." },

  // ==================================================================
  // 04. INDIAN GEOGRAPHY  —  13 questions  (Q23, Q24, Q30, Q38, Q39, Q40, Q41, Q42, Q43, Q44, Q68, Q69, Q71)
  // ==================================================================
  { n: 23, sec: "Indian Geography", q: "Winterline, the natural phenomena is observed in which part of the country?",
    o: ["Shimla","Darjeeling","Mussoorie","Nanital"], a: "C",
    e: "The 'Winterline'—an atmospheric refraction and inversion horizon phenomenon visible at sunset during winter—is famously viewed from Mussoorie in Uttarakhand (and parts of Bern, Switzerland)." },
  { n: 24, sec: "Indian Geography", q: "According to the Koppen's Climate Classification the (Amw) climate is found predominantly in which part of India?",
    o: ["North-Western India","Western coastal region","Thar desert","Northern plain"], a: "B",
    e: "Under Köppen's classification, 'Amw' denotes a Monsoon type with a short dry winter season, typical of the Malabar and Konkan Western Coastal Plains of India." },
  { n: 30, sec: "Indian Geography", q: "Consider the following agricultural practices: 1. Contour bunding, 2. Relay cropping, 3. Zero tillage. In the context of global climate change, which of the above helps/help in carbon sequestration/storage in the soil?",
    o: ["1 and 2","Only 3","1, 2 and 3","None of these"], a: "B",
    e: "The official answer key marks (B) Only 3. Zero tillage minimizes soil disturbance and slows down microbial oxidation, thereby significantly increasing soil organic carbon storage." },
  { n: 38, sec: "Indian Geography", q: "Which of the following statements are true about India? 1. India is the fifth largest country of the world. 2. It occupies about 2.4% of the total area of the lithosphere. 3. Whole of India lies in the tropic zone. 4. 82°30' East longitude is used to determine Indian Standard Time. Use the code given below to select the correct answer.",
    o: ["Only 1 and 2","Only 2 and 3","Only 1 and 3","Only 2 and 4"], a: "D",
    e: "India is the 7th largest country (not 5th), and the Tropic of Cancer divides it so parts lie in the temperate/subtropical zone. Statements 2 (2.4% land area) and 4 (82.5° E IST meridian) are correct." },
  { n: 39, sec: "Indian Geography", q: "Consider the following relief features: 1. Zaskar Range, 2. Dhauladhar Range, 3. Ladakh Range, 4. Karakoram Range. The correct South to Northward sequence of the above relief features is:",
    o: ["2, 1, 3, 4","2, 3, 4, 1","4, 3, 2, 1","4, 2, 1, 3"], a: "A",
    e: "From south to north, the mountain ranges run: Dhauladhar (Lesser Himalayas) → Zanskar → Ladakh (Trans-Himalayas) → Karakoram. Sequence: 2, 1, 3, 4." },
  { n: 40, sec: "Indian Geography", q: "Which waterfall of India is popularly known as Niagara Falls?",
    o: ["Barkana falls","Chitrakote falls","Rajat Prapat","Keoti falls"], a: "B",
    e: "Chitrakote Falls on the Indravati River in Bastar district, Chhattisgarh, is widely known as the 'Niagara Falls of India' due to its horse-shoe shape and width during monsoons." },
  { n: 41, sec: "Indian Geography", q: "Which one of the following ports is located on Odisha coast?",
    o: ["Haldia","Mumbai.","Paradip","Visakhapatnam"], a: "C",
    e: "Paradip Port is an artificial deep-water seaport situated at the confluence of the Mahanadi River and the Bay of Bengal in Jagatsinghpur district, Odisha." },
  { n: 42, sec: "Indian Geography", q: "Which of the following is not correctly matched?",
    o: ["Shipki La: Himachal Pradesh","Bomdi La: Arunachal Pradesh","Nathu La: Meghalaya","Zoji La: Jammu & Kashmir"], a: "C",
    e: "Nathu La is a Himalayan mountain pass connecting Sikkim with the Tibet Autonomous Region; it is not in Meghalaya." },
  { n: 43, sec: "Indian Geography", q: "Which of the following option represents correct order of mountain Passes from West to East? 1. Shipki La, 2. Nathu La, 3. Bomdi La, 4. Lipulekh",
    o: ["1, 2, 3, 4","2, 3, 4, 1","1, 4, 2, 3","3, 2, 1, 4"], a: "C",
    e: "From west to east: Shipki La (Himachal Pradesh) → Lipulekh (Uttarakhand) → Nathu La (Sikkim) → Bomdi La (Arunachal Pradesh). Order: 1, 4, 2, 3." },
  { n: 44, sec: "Indian Geography", q: "Sucrose content in sugarcane decreases",
    o: ["if high rainfall occurs during the period of growth of the plant","if frost occurs during the period of ripening","if there is fluctuation in temperature during the period of growth of the plant","if there is high temperature during the time of ripening"], a: "B",
    e: "Severe frost during the ripening phase damages sugarcane parenchyma tissue and accelerates the inversion of sucrose into glucose and fructose, drastically reducing sucrose yield." },
  { n: 68, sec: "Indian Geography", q: "In which state of India is Kund or Tanka used for water harvesting?",
    o: ["Rajasthan","Andhra Pradesh","Uttar Pradesh","Punjab"], a: "A",
    e: "Kunds (or Tankas) are traditional underground rainwater harvesting cisterns widely constructed across the arid and semi-arid regions of Rajasthan (notably Bikaner, Barmer, and Jodhpur)." },
  { n: 69, sec: "Indian Geography", q: "According to the Census of India 2011, in rural India, which state has the maximum female workforce participation rate?",
    o: ["Arunachal Pradesh","Uttar Pradesh","Himachal Pradesh","Andhra Pradesh"], a: "C",
    e: "According to Census 2011 data, Himachal Pradesh recorded the highest female work participation rate in rural areas among Indian states, driven by intensive subsistence agrarian practices." },
  { n: 71, sec: "Indian Geography", q: "Which of the following is in geographical proximity to Sri Lanka?",
    o: ["Only Karaikal","Karaikal and Yanam","Mahe","Only Yanam"], a: "A",
    e: "Karaikal, an enclave of the Union Territory of Puducherry situated on the Coromandel Coast in Tamil Nadu, is in direct geographical proximity to the Palk Strait and Sri Lanka." },

  // ==================================================================
  // 05. WEST BENGAL GEOGRAPHY  —  1 question  (Q55)
  // ==================================================================
  { n: 55, sec: "West Bengal Geography", q: "Where was the first Jute factory in India established?",
    o: ["Cuttack, Odisha","Ongole, Andhra Pradesh","Rishra, West Bengal","Raigarh, Chhattisgarh"], a: "C",
    e: "India's first power-driven jute spinning mill was established by British entrepreneur George Acland in 1855 at Rishra in Hooghly district, West Bengal." },

  // ==================================================================
  // 06. ARTS AND CULTURE  —  1 question  (Q22)
  // ==================================================================
  { n: 22, sec: "Arts and Culture", q: "Which of the following is not a UNESCO World Heritage Site?",
    o: ["Qutb Minar","Red Fort","India Gate","None of teh above"], a: "C",
    e: "India Gate in New Delhi is a war memorial designed by Sir Edwin Lutyens and is not inscribed as a UNESCO World Heritage Site, unlike Qutb Minar (1993) and the Red Fort complex (2007)." },

  // ==================================================================
  // 07. INDIAN POLITY  —  2 questions  (Q54, Q73)
  // ==================================================================
  { n: 54, sec: "Indian Polity", q: "When, for the first time, did the Election Commission of India become a multimember body?",
    o: ["1995","1985","1989","1994"], a: "C",
    e: "The Election Commission was first made a multi-member body on 16 October 1989 when the President appointed two additional Election Commissioners (following the lowering of the voting age by the 61st Amendment)." },
  { n: 73, sec: "Indian Polity", q: "Who called the Governor of a state as \"federal fireman\"?",
    o: ["KT shah","BR Ambedkar","C Rajagopalachari","Dr. Rajendra Prasad"], a: "C",
    e: "Chakravarti Rajagopalachari famously described the office of the Governor as a 'federal fireman', functioning to extinguish constitutional and administrative crises within states." },

  // ==================================================================
  // 08. INDIAN ECONOMY  —  6 questions  (Q50, Q61, Q62, Q63, Q64, Q66)
  // ==================================================================
  { n: 50, sec: "Indian Economy", q: "The Bhartiya Kisan Union was established in",
    o: ["1975","1980","1986","1990"], a: "C",
    e: "The Bharatiya Kisan Union (BKU) was reorganized and formally founded by Chaudhary Mahendra Singh Tikait in Western Uttar Pradesh around 1986–1987. The official key selects (C) 1986.",
    flag: "Official key gives (C) 1986; historical records often cite Mahendra Singh Tikait formalizing BKU in 1986–1987." },
  { n: 61, sec: "Indian Economy", q: "As per the definition of Census of India, a 'marginal worker' is a person who works for:",
    o: ["less than 183 days in a year","more than 183 days in a year","eight months in a year","83 days in a year"], a: "A",
    e: "The Census of India defines a marginal worker as an individual who engaged in economically productive work for less than 183 days (or six months) during the preceding reference year." },
  { n: 62, sec: "Indian Economy", q: "In Pradhan Mantri Gramin Awaas Yojana, the cost of unit assistance is shared between Central and State Governments in the ratio ________ in plain areas.",
    o: ["60:40","40: 60","90: 10","30: 70"], a: "A",
    e: "Under the Pradhan Mantri Awaas Yojana - Gramin (PMAY-G), the financing pattern for unit assistance in plain areas is shared 60:40 between the Central and State Governments (and 90:10 in North-Eastern and Himalayan states)." },
  { n: 63, sec: "Indian Economy", q: "Which of the following goods need further transformation in the economic process?",
    o: ["Consumer durable goods","Finished goods","Intermediate goods","Capital goods"], a: "C",
    e: "Intermediate goods are semi-finished products used as inputs in production processes to produce final goods, requiring further economic transformation." },
  { n: 64, sec: "Indian Economy", q: "What is net investment?",
    o: ["Sum of all the investments in a country","Gross investment + depreciation","Gross capital investment - indirect taxes","Gross investment - depreciation"], a: "D",
    e: "Net investment measures the actual addition to the physical capital stock over a period and is calculated as Gross Investment minus Depreciation (capital consumption allowance)." },
  { n: 66, sec: "Indian Economy", q: "Which is the National Mission for Financial Inclusion to ensure access to financial services, namely, a basic savings and deposits accounts, remittance, credit, insurance, pension in an affordable manner?",
    o: ["Deendayal Antyodaya Yojana","Deen Dayal Upadhyaya Grameen Kaushalya Yojana","Swarnjayanti Gram Swarozgar Yojana","Pradhan Mantri Jan Dhan Yojana"], a: "D",
    e: "Pradhan Mantri Jan Dhan Yojana (PMJDY), launched on 28 August 2014, serves as India's national mission for comprehensive financial inclusion." },

  // ==================================================================
  // 09. PHYSICS  —  5 questions  (Q1, Q2, Q3, Q4, Q5)
  // ==================================================================
  { n: 1, sec: "Physics", q: "A pilot has to release the bomb to hit a target",
    o: ["Right above the target","Beyond the target","Before the target","None of these"], a: "C",
    e: "Due to inertia of motion, a bomb released from a horizontally flying aircraft continues moving forward with the plane's velocity as it falls along a parabolic path; therefore, it must be dropped before reaching the target." },
  { n: 2, sec: "Physics", q: "An object is in static equilibrium when it is",
    o: ["At rest","Moving in a circular path","Moving with uniform velocity","Accelerating at high speed"], a: "A",
    e: "An object is in static equilibrium when it remains at rest, with the vector sum of all external forces and torques acting on it equaling zero." },
  { n: 3, sec: "Physics", q: "If the Distance Time graph is a curve then it represents",
    o: ["Uniform speed","Constant displacement","Uniform momentum","Non-uniform speed"], a: "D",
    e: "A curved line on a distance-time graph indicates that the slope (speed) is changing over time, representing non-uniform (accelerated) speed." },
  { n: 4, sec: "Physics", q: "The ratio of the total distance travelled by a body to the total time taken by it is its",
    o: ["Instantaneous velocity","Linear velocity","Average speed","Acceleration"], a: "C",
    e: "Average speed is defined as total distance traveled divided by total elapsed time: s_avg = Total Distance / Total Time." },
  { n: 5, sec: "Physics", q: "A kilowatt-hour is unit of -",
    o: ["Energy","Power","Electric charge","Electric current"], a: "A",
    e: "A kilowatt-hour (kWh) is a commercial unit of electrical energy, representing work done or energy consumed at a rate of 1,000 watts for one hour (1 kWh = 3.6 × 10⁶ J)." },

  // ==================================================================
  // 10. CHEMISTRY  —  14 questions  (Q6, Q7, Q8, Q9, Q10, Q11, Q12, Q13, Q14, Q15, Q16, Q17, Q18, Q19, Q20, Q57, Q58)
  // ==================================================================
  { n: 6, sec: "Chemistry", q: "Which of the following is the scientific name of the mineral called chromite?",
    o: ["Aluminium chromium oxide","Copper chromium oxide","Silver chromium oxide","Iron chromium oxide"], a: "D",
    e: "Chromite is an iron chromium oxide mineral with the chemical formula FeCr₂O₄." },
  { n: 7, sec: "Chemistry", q: "Which of the following is used as raw material for the manufacture of rayon?",
    o: ["Coal","Petroleum","Cellulose","Plastic"], a: "C",
    e: "Rayon is a regenerated semi-synthetic fiber manufactured from naturally occurring wood pulp cellulose." },
  { n: 8, sec: "Chemistry", q: "Aqueous Hydrolysis of sucrose formed -",
    o: ["Only Lactose","Only Glucose","Glucose and Fructose","Glucose and Lactose"], a: "C",
    e: "Hydrolysis of the disaccharide sucrose yields equimolar quantities of D-glucose and D-fructose, a mixture known as invert sugar." },
  { n: 9, sec: "Chemistry", q: "Which of the following states of matter is also known as the Bose-Einstein Condensate?",
    o: ["Second","Third","Fourth","Fifth"], a: "D",
    e: "The Bose-Einstein Condensate (BEC), formed when dilute bosons are cooled to temperatures near absolute zero, is recognized as the fifth state of matter (after solid, liquid, gas, and plasma)." },
  { n: 10, sec: "Chemistry", q: "Fe has 26 protons in its nucleus. What are the number of electrons in Fe2+(II) ion?",
    o: ["24","26","28","13"], a: "A",
    e: "A neutral iron atom has 26 electrons. Formation of the divalent cation Fe²⁺ involves the loss of two 4s electrons, leaving 24 electrons." },
  { n: 11, sec: "Chemistry", q: "Nitric acid does not react with",
    o: ["Gold","Copper","Zinc","Iron"], a: "A",
    e: "Gold is a noble metal that does not react with concentrated nitric acid alone; it requires aqua regia (a 3:1 mixture of concentrated HCl and HNO₃) to dissolve." },
  { n: 12, sec: "Chemistry", q: "Which element has the highest density?",
    o: ["Mercury","Osmium","Zinc","Nickel"], a: "B",
    e: "Osmium (Os) is the densest naturally occurring element, with a density of approximately 22.59 g/cm³." },
  { n: 13, sec: "Chemistry", q: "Mercury is a",
    o: ["Solid metal","Liquid metal","Solid nonmetal","Liquid nonmetal"], a: "B",
    e: "Mercury (quicksilver, Hg) is the only transition metallic element that exists in the liquid state at standard room temperature and pressure." },
  { n: 14, sec: "Chemistry", q: "Diamond does not conduct electricity, because -",
    o: ["It's structure is very compact","It is of crystalline nature","There are only carbon atoms, present in it","No free electrons are present in it"], a: "D",
    e: "In diamond, each carbon atom is tetrahedrally bonded to four other carbon atoms via sp³ hybridized covalent bonds with no delocalized or free valence electrons to conduct current." },
  { n: 15, sec: "Chemistry", q: "Charcoal is used in water treatment as a/an -",
    o: ["Solvent","Absorbent","Coagulant","Adsorbent"], a: "D",
    e: "Activated charcoal has a high surface area and acts as an adsorbent, trapping organic impurities, chlorine, and toxins on its surface." },
  { n: 16, sec: "Chemistry", q: "Which metal is extracted from Seawater?",
    o: ["Potassium","Aluminium","Magnesium","Beryllium"], a: "C",
    e: "Magnesium is commercially extracted from seawater (Dow process) by precipitating it as magnesium hydroxide using lime or dolime." },
  { n: 17, sec: "Chemistry", q: "Dry powder fire extinguisher contains -",
    o: ["Sand","Sand and sodium carbonate","Sand and potassium carbonate","Sand and sodium bicarbonate"], a: "D",
    e: "Dry chemical extinguishers contain sodium bicarbonate (or potassium bicarbonate) blended with inert silica sand and flowing agents." },
  { n: 18, sec: "Chemistry", q: "________ is associated with edible fats.",
    o: ["Hydrogenation","Haber process","Le Chatelier process","None of these"], a: "A",
    e: "Catalytic hydrogenation of polyunsaturated vegetable oils (using a nickel catalyst) is used commercially to manufacture solid edible fats like vanaspati ghee." },
  { n: 19, sec: "Chemistry", q: "Washing soda is used: I. for removing permanent hardness of water, II. for disinfecting drinking water, III. as a cleaning agent for domestic purpose. Choose the correct answer using the codes given below: Codes:",
    o: ["Only I and II","Only I and III","Only II and III","All I, II and III"], a: "B",
    e: "Washing soda (sodium carbonate) removes permanent water hardness and serves as a domestic cleaning detergent. Disinfection of water is achieved using chlorine or bleaching powder, not washing soda." },
  { n: 20, sec: "Chemistry", q: "PET is a very familiar form of ________. It is used for making bottles.",
    o: ["Nylon","Acrylic","Polyester","Rayon"], a: "C",
    e: "PET stands for Polyethylene Terephthalate, a thermoplastic polymer belonging to the polyester family widely used for making beverage bottles and synthetic textile fibers." },
  { n: 57, sec: "Chemistry", q: "Which of the following is soda lime?",
    o: ["Ca(OH)2 + CaO","CaCl2 + CaO","KOH + CaO","NaOH + CaO"], a: "D",
    e: "Soda lime is a chemical mixture consisting predominantly of sodium hydroxide (NaOH) and calcium oxide (CaO), commonly used in decarboxylation reactions." },
  { n: 58, sec: "Chemistry", q: "Which of the following is commonly known as Quicklime?",
    o: ["CaSO4","CaCl2","Ca(OH)2","CaO"], a: "D",
    e: "Quicklime (burnt lime) is chemically calcium oxide (CaO), produced by thermal calcination of limestone." },

  // ==================================================================
  // 11. BIOLOGY  —  4 questions  (Q29, Q60, Q67, Q70)
  // ==================================================================
  { n: 29, sec: "Biology", q: "World's most problematic aquatic weed is:",
    o: ["Azolla","Eichornia","Trapa","Wolffia"], a: "B",
    e: "Eichhornia crassipes (water hyacinth), nicknamed the 'Terror of Bengal', is an aggressive invasive aquatic weed that clogs water channels and depletes dissolved oxygen." },
  { n: 60, sec: "Biology", q: "Pineapple is a",
    o: ["Single fruit","Stem of the plants","Collection of fruits","Collection of leaves"], a: "C",
    e: "The pineapple (Ananas comosus) is a multiple composite fruit (sorosis) developed from the fusion of an entire spike inflorescence of multiple individual flowers." },
  { n: 67, sec: "Biology", q: "Which of the following can be represented as a funtional unit of nature ?",
    o: ["Vehicles","Ecosystem","Humans","Plants"], a: "B",
    e: "In ecology, an ecosystem is recognized as the structural and functional unit of nature where biotic communities interact dynamically with their abiotic environment." },
  { n: 70, sec: "Biology", q: "Hubbardia heptaneuron, which has become endangered, is a species of which of the following?",
    o: ["Grass","Bamboo","Tiger","Crane"], a: "A",
    e: "Hubbardia heptaneuron is a critically endangered, delicate endemic species of rheophytic grass (Poaceae) discovered in the spray zone of Gersoppa (Jog) Falls in Karnataka." },

  // ==================================================================
  // 12. STATIC GK  —  10 questions  (Q21, Q25, Q26, Q27, Q28, Q51, Q52, Q53, Q59, Q65)
  // ==================================================================
  { n: 21, sec: "Static GK", q: "The gas which leaked from Union Carbide Factory, Bhopal was -",
    o: ["Carbon monoxide","Methane","Methyl isocyanate","Sulpher dioxide"], a: "C",
    e: "The toxic gas that leaked from the Union Carbide pesticide plant in Bhopal on the night of 2–3 December 1984 was Methyl Isocyanate (MIC, CH₃NCO)." },
  { n: 25, sec: "Static GK", q: "For weather science dispatch, which of the following is used to fill balloons?",
    o: ["Oxygen","Carbon dioxide","Methane","Helium"], a: "D",
    e: "Meteorological weather balloons (radiosondes) are filled with helium (or hydrogen) gas due to its low molecular mass, low density, and non-flammable nature." },
  { n: 26, sec: "Static GK", q: "For the betterment of human life, which of the following steps is important?",
    o: ["Afforestation","Bank on mining","Protection of Wildlife","Reduce the use of natural resources"], a: "A",
    e: "The official answer key marks (A) Afforestation; extensive tree planting restores ecological balance, maintains the hydrological cycle, and mitigates climate change." },
  { n: 27, sec: "Static GK", q: "Which of the following is called \"grave yard of Dinosaurs\"?.",
    o: ["China","Montana","Argentina","Brazil"], a: "B",
    e: "Montana in the United States (notably the Hell Creek Formation and Two Medicine Formation) is widely referred to as the 'Graveyard of Dinosaurs' due to its abundance of fossil skeletons." },
  { n: 28, sec: "Static GK", q: "The 'Eco Mark' Scheme was launched in 1991 to encourage consumers to buy products of less harmful environmental impact. Which one of the following consumer products is not notified under this scheme?",
    o: ["Soaps and Detergents","Paper and Plastics","Cosmetics and Aerosols","Drugs and Antibiotics"], a: "D",
    e: "The Eco Mark certification issued by the Bureau of Indian Standards (represented by an earthen pot logo) covers soaps, paper, paints, and cosmetics, but excludes pharmaceutical drugs and antibiotics." },
  { n: 51, sec: "Static GK", q: "Champions Trophy is associated with",
    o: ["Football","Hockey","Cricket","Chess"], a: "B",
    e: "The official answer key marks (B) Hockey (referring to the classic FIH Hockey Champions Trophy founded in 1978 by Pakistan). The term is also prominently associated with ICC Cricket." },
  { n: 52, sec: "Static GK", q: "The Commonwealth games are held once in ________ years.",
    o: ["2","4","6","8"], a: "B",
    e: "The Commonwealth Games are a quadrennial multi-sport event held every 4 years." },
  { n: 53, sec: "Static GK", q: "Venice of the East is",
    o: ["Shillong","Kolkata","Alappuzha","Bengaluru"], a: "C",
    e: "Alappuzha (Alleppey) in Kerala is known as the 'Venice of the East' for its picturesque network of coastal lagoons, canals, and backwaters." },
  { n: 59, sec: "Static GK", q: "The capital of Congo is",
    o: ["Harare","Lusaka","Kinshasa","None of the above"], a: "C",
    e: "Kinshasa is the capital and largest metropolis of the Democratic Republic of the Congo (Brazzaville is the capital of the neighboring Republic of the Congo)." },
  { n: 65, sec: "Static GK", q: "In which year did India make its Olympic debut in hockey?",
    o: ["1936","1932","1924","1928"], a: "D",
    e: "The Indian men's field hockey team made its Olympic debut at the 1928 Amsterdam Summer Olympics, capturing the gold medal without conceding a single goal." },

  // ==================================================================
  // 13. CURRENT AFFAIRS  —  2 questions  (Q74, Q75)
  // ==================================================================
  { n: 74, sec: "Current Affairs", q: "Central Vigilance Commission (CVC) was established in which year?",
    o: ["1962","1963","1964","1965"], a: "C",
    e: "The Central Vigilance Commission (CVC) was set up by the Government of India in February 1964 on the recommendations of the K. Santhanam Committee on Prevention of Corruption." },
  { n: 75, sec: "Current Affairs", q: "Which Bill was passed by Parliament in 2026 to strengthen measures against examination paper leaks and organized cheating in public examinations?",
    o: ["Digital Education Reform Bill","National Recruitment Transparency Bill","Public Examination Regulation Bill","Anti-Paper Leak Amendment Bill"], a: "D",
    e: "The paper's answer key marks (D) Anti-Paper Leak Amendment Bill. The enacted statutory legislation addressing cheating and leaks is the Public Examinations (Prevention of Unfair Means) Act.",
    flag: "Official key marks (D) Anti-Paper Leak Amendment Bill; the central statute is the Public Examinations (Prevention of Unfair Means) Act." },

  // ==================================================================
  // 14. APTITUDE & MENTAL ABILITY  —  25 questions  (Q76 to Q100)
  // ==================================================================
  { n: 76, sec: "Aptitude & Mental Ability", q: "If sin θ + cosec θ = 2, then sin² θ + cosec² θ is equal to",
    o: ["1","4","2","None of the above"], a: "C",
    e: "sin θ + 1/sin θ = 2 => sin² θ - 2 sin θ + 1 = 0 => (sin θ - 1)² = 0 => sin θ = 1, cosec θ = 1. Therefore, sin² θ + cosec² θ = 1² + 1² = 2." },
  { n: 77, sec: "Aptitude & Mental Ability", q: "8 men or 12 women can do a piece of work in 20 days. The number of days needed to complete the job, if 10 men and 15 women are employed to do the same piece of work is",
    o: ["10 days","15 days","8 days","20 days"], a: "C",
    e: "8 men = 12 women => 1 man = 1.5 women. Total work = 12 women × 20 days = 240 woman-days. Workforce = 10 men + 15 women = 10(1.5) + 15 = 30 women. Days needed = 240 / 30 = 8 days." },
  { n: 78, sec: "Aptitude & Mental Ability", q: "The difference between a two-digit number and the number obtained by interchanging the positions of its digits is 36. What is the difference between the two digits of that number?",
    o: ["3","4","9","cannot be determined"], a: "B",
    e: "(10x + y) - (10y + x) = 9(x - y) = 36 => x - y = 36 / 9 = 4." },
  { n: 79, sec: "Aptitude & Mental Ability", q: "The unit's digit present in the product 274 x 318 x 577 x 313 is",
    o: ["2","3","4","5"], a: "A",
    e: "Multiplying the units digits sequentially: 4 × 8 = 32 (unit 2); 2 × 7 = 14 (unit 4); 4 × 3 = 12 (unit 2)." },
  { n: 80, sec: "Aptitude & Mental Ability", q: "A man buys milk at Rs. 60 per litre, adds water to it and then sells it at Rs. 50 per litre. What is the ratio of milk and water if his profit in the deal is 20%?",
    o: ["5:9","25: 11","16:19","13:16"], a: "B",
    e: "SP of mixture = ₹50/L with 20% profit => CP of mixture = 50 / 1.20 = ₹125/3 per litre. Using alligation between pure milk (60) and free water (0): Ratio of milk to water = (125/3 - 0) : (60 - 125/3) = (125/3) : (55/3) = 125 : 55 = 25 : 11." },
  { n: 81, sec: "Aptitude & Mental Ability", q: "While preparing mixture of tea, 5% tea is lost. In what ratio a trader should mix two kinds of tea costing Rs. 600/kg and Rs. 450/kg respectively so that he might gain 25% on selling the mixed tea at Rs. 625 kg?",
    o: ["3:5","4:5","5:2","1:5"], a: "D",
    e: "Effective selling price per kg mixed = 625 × 0.95 = ₹593.75. CP of mixture for 25% gain = 593.75 / 1.25 = ₹475. Ratio = (475 - 450) : (600 - 475) = 25 : 125 = 1 : 5." },
  { n: 82, sec: "Aptitude & Mental Ability", q: "A man travels three-fifths of a distance AB at a speed of 3x and the remaining at a speed 2y. If he goes from B to A and returns at a speed 5z in the same time, then which one is correct?",
    o: ["1/x + 1/y = 1/z","x + y = z","1/x + 1/y = 2/z","x + z = y"], a: "C",
    e: "Let distance AB = d. Time taken = (3d/5)/(3x) + (2d/5)/(2y) = d/(5x) + d/(5y). Round trip return time = (2d)/(5z). Equating times: d/(5x) + d/(5y) = (2d)/(5z) => 1/x + 1/y = 2/z." },
  { n: 83, sec: "Aptitude & Mental Ability", q: "A person walks from his house at a speed of 4 km/hour and reaches his school 5 minutes late. If this speed has been 5 km/hour, he would have reached 10 minutes earlier. The distance of the school from his house is",
    o: ["5 km","6 km","7 km","8 km"], a: "A",
    e: "Difference in travel times = 5 - (-10) = 15 minutes = 1/4 hour. d/4 - d/5 = 1/4 => d/20 = 1/4 => d = 5 km." },
  { n: 84, sec: "Aptitude & Mental Ability", q: "What fraction of an hour is a second?",
    o: ["1/24","1/60","1/120","1/3600"], a: "D",
    e: "1 hour = 60 minutes = 3600 seconds. Thus, 1 second = 1/3600 of an hour." },
  { n: 85, sec: "Aptitude & Mental Ability", q: "The current population of a town is 120000. If the population increases by 10% every year, then the population of the town after three years will be",
    o: ["125550","162900","134650","159720"], a: "D",
    e: "Population after 3 years = 120000 × (1 + 0.10)³ = 120000 × 1.331 = 159,720." },
  { n: 86, sec: "Aptitude & Mental Ability", q: "Amal invests 1/4 of his capital at 8% p.a., 1/5 at 10% p.a. and the remainder at 7% p.a. If his annual income is Rs. 628, then the capital is",
    o: ["Rs. 7500","Rs. 7700","Rs. 8000","Rs. 8500"], a: "C",
    e: "Let total capital be C. Remainder = 1 - (1/4 + 1/5) = 1 - 9/20 = 11/20. Income = C × [(1/4 × 0.08) + (1/5 × 0.10) + (11/20 × 0.07)] = C × [0.02 + 0.02 + 0.0385] = C × 0.0785 = 628 => C = 628 / 0.0785 = ₹8000." },
  { n: 87, sec: "Aptitude & Mental Ability", q: "A merchant purchased 11 toys for Rs. 10 and sold 10 toys for Rs. 11. His profit is",
    o: ["15%","20%","21%","25%"], a: "C",
    e: "CP per toy = ₹10/11; SP per toy = ₹11/10. Profit % = [(11/10 - 10/11) / (10/11)] × 100 = [(121 - 100) / 100] × 100 = 21%." },
  { n: 88, sec: "Aptitude & Mental Ability", q: "A man buys two types of oranges in equal number one at 5 for a rupee and the other at 3 for a rupee and sells the whole at 6 for Rs. 2, then his gain or loss per cent is",
    o: ["25% gain","20% loss","10% gain","25% loss"], a: "A",
    e: "Let he buys 15 of each (total 30 oranges). Cost = 15/5 + 15/3 = 3 + 5 = ₹8. SP of 30 oranges = (30/6) × 2 = ₹10. Profit = 10 - 8 = ₹2. Profit % = (2/8) × 100 = 25% gain." },
  { n: 89, sec: "Aptitude & Mental Ability", q: "Six years hence, a man's age will be three times the age of his son and three years ago he was nine times as old as his son. The present age of the man is",
    o: ["28 yrs","30 yrs","32 yrs","34 yrs"], a: "B",
    e: "Let present ages be M and S. (M + 6) = 3(S + 6) => M - 3S = 12. (M - 3) = 9(S - 3) => M - 9S = -24. Subtracting equations: 6S = 36 => S = 6. M = 3(6) + 12 = 30 years." },
  { n: 90, sec: "Aptitude & Mental Ability", q: "Average age of 8 sons of a family is 12 years. Average age of the sons together with their parents is 21 years. If the father is older than the mother by 8 years, then the age of the mother is",
    o: ["48 years","53 years","60 years","62 years"], a: "B",
    e: "Total age of 8 sons = 8 × 12 = 96. Total age of family (10 members) = 10 × 21 = 210. Total age of parents = 210 - 96 = 114. Father (F) = Mother (M) + 8 => 2M + 8 = 114 => 2M = 106 => M = 53 years." },
  { n: 91, sec: "Aptitude & Mental Ability", q: "Pipe A can fill a tank in 3 hours and pipe B can fill it in 4 hours. If they are opened at alternate hours and if pipe A is opened first, in how many hours will the tank gets filled?",
    o: ["3 1/4 hours","4 hours","4 1/2 hours","3 1/3 hours"], a: "D",
    e: "Total capacity = 12 units. In hour 1, A does 4 units; in hour 2, B does 3 units. In 2 hours, 7 units are filled. In 3rd hour, A fills 4 units (total 11 units). Remaining 1 unit filled by B in 1/3 hour. Total time = 3 1/3 hours." },
  { n: 92, sec: "Aptitude & Mental Ability", q: "A man invests Rs. 5000 at a rate of 6% per annum. How much more should he invest at a rate of 9%, so that he can earn a total of 7% per annum?",
    o: ["Rs. 5000","Rs. 2500","Rs. 3000","Rs. 4500"], a: "B",
    e: "Using alligation: 6% vs 9% with mean 7% yields ratio (9 - 7) : (7 - 6) = 2 : 1. If 2 parts = ₹5000, 1 part = 5000 / 2 = ₹2500." },
  { n: 93, sec: "Aptitude & Mental Ability", q: "The difference between simple interest and compound interest on a sum for 3 years at 10% when the interest is compounded annually is Rs. 155. Then the principal value is",
    o: ["Rs. 4000","Rs. 5000","Rs. 5500","Rs. 6000"], a: "B",
    e: "Difference for 3 years = P(r/100)² × (3 + r/100) => 155 = P(10/100)² × (3 + 0.10) = P(0.01) × 3.10 = 0.031 P => P = 155 / 0.031 = ₹5000." },
  { n: 94, sec: "Aptitude & Mental Ability", q: "A man rows downstream 32 km and 14 km upstream. If he takes 6 hours to cover each distance, then the velocity (in kmph) of the current kmph is",
    o: ["1/2","1","3/2","2"], a: "C",
    e: "Downstream speed = 32 / 6 km/h. Upstream speed = 14 / 6 km/h. Velocity of current = (32/6 - 14/6) / 2 = (18/6) / 2 = 3 / 2 km/h." },
  { n: 95, sec: "Aptitude & Mental Ability", q: "The areas of two similar triangles are 36 sq. cm and 81 sq. cm respectively. If the median of smaller triangle is 12 cm then the corresponding median of the larger triangle is",
    o: ["12 cm","18 cm","24 cm","10 cm"], a: "B",
    e: "Ratio of areas = (Ratio of medians)² => 36 / 81 = (12 / m)² => 6 / 9 = 12 / m => m = (12 × 9) / 6 = 18 cm." },
  { n: 96, sec: "Aptitude & Mental Ability", q: "The lengths of two parallel chords of a circle are 6 cm and 8 cm. If the smaller chord is at distance 4 cm from the centre, then the distance of the other chord from the centre is",
    o: ["5 cm","4 cm","3 cm","2 cm"], a: "C",
    e: "Half chord lengths are 3 cm and 4 cm. Radius r = √(3² + 4²) = √(9 + 16) = 5 cm. For the 8 cm chord, half length is 4 cm, so distance = √(5² - 4²) = √(25 - 16) = 3 cm." },
  { n: 97, sec: "Aptitude & Mental Ability", q: "If the semi perimeter of a right-angle triangle be s cm and hypotenuse be c cm, then the area of the triangle is",
    o: ["s / (s - c) sq.cm","sc sq.cm","s(s-c) sq.cm","None of the above."], a: "C",
    e: "Let sides be a, b, c. a + b + c = 2s => a + b = 2s - c. (a + b)² = a² + b² + 2ab = c² + 4 × Area => (2s - c)² - c² = 4 × Area => 4s² - 4sc = 4 × Area => Area = s(s - c) sq.cm." },
  { n: 98, sec: "Aptitude & Mental Ability", q: "Three cubes of edges 6 cm, 8 cm and 10 cm are melted without loss of metal into a single cube. The edge of the new cube will be:",
    o: ["16 cm","14 cm","12 cm","8 cm"], a: "C",
    e: "Total volume = 6³ + 8³ + 10³ = 216 + 512 + 1000 = 1728 cm³. Edge of new cube = ∛1728 = 12 cm." },
  { n: 99, sec: "Aptitude & Mental Ability", q: "ΔABC is a triangle whose ∠C = 90°. If p is the length of the perpendicular from C to AB, then 1/BC² + 1/AC² =",
    o: ["p²","2p²","1/p²","2/p²"], a: "C",
    e: "Area = (1/2)ab = (1/2)cp => ab = cp => p = ab/c. 1/p² = c²/(a²b²) = (a² + b²)/(a²b²) = 1/b² + 1/a² = 1/AC² + 1/BC²." },
  { n: 100, sec: "Aptitude & Mental Ability", q: "ΔABC has sides 5 cm, 6 cm and 7 cm. AB extended touches a circle at P and AC extended touches the same circle at Q. Find the length (in cm) of AQ.",
    o: ["13","12","9","11"], a: "C",
    e: "Tangents from A are equal: AP = AQ = Semi-perimeter of ΔABC = (5 + 6 + 7) / 2 = 18 / 2 = 9 cm." },

]);