/* =====================================================================
   questions/set-14.js  —  SET-14
   ---------------------------------------------------------------------
   Add this set's questions inside the [ ... ] below, one block per question:

     { n: 1, sec: "Modern History", q: "Question text?",
       o: ["Option A", "Option B", "Option C", "Option D"],
       a: "B",                 // correct letter: A, B, C or D
       e: "Explanation text." },

   n = original question number · sec = one of the 14 section names in data.js
   (copy exactly) · e = explanation (optional) · d = "Easy"/"Medium"/"Hard" (optional)
   flag = optional warning shown in review, e.g. "Answer may be outdated"
   ===================================================================== */
// Source: West Bengal Urdu Academy Pre-Recruitment Coaching (WBUA MISC-2024 PH-I VST-2, Date: 03.09.2026). Complete: 100 questions.
// Questions with a "flag" highlight official answer key discrepancies or physics inaccuracies (Q35, Q53, Q84).

registerSet("SET-14", [

  // ==================================================================
  // 01. ANCIENT HISTORY  —  2 questions  (Q22, Q23)
  // ==================================================================
  { n: 22, sec: "Ancient History", q: "Which of the following kingdoms was divided into sub-divisions called Aharas or Rashtras that meant districts?",
    o: ["Kushana","Parthian","Satavahana","Shaka"], a: "C",
    e: "The administrative structure of the Satavahana dynasty divided their provinces into districts designated as 'Aharas' or 'Rashtras', headed by Amatyas or Mahamatras." },
  { n: 23, sec: "Ancient History", q: "________ authored by Tolkappiyar is the earliest Tamil literature.",
    o: ["Tolkappiyam","Ettutogai","Kalittogai","Narrinai"], a: "A",
    e: "Tolkappiyam, composed by Tolkappiyar during the Second Sangam, is the oldest extant work of Tamil literature and grammar." },

  // ==================================================================
  // 02. MEDIEVAL HISTORY  —  2 questions  (Q42, Q49)
  // ==================================================================
  { n: 42, sec: "Medieval History", q: "Vindhyashakti was the founder of which of the following dynasties?",
    o: ["Pallava","Maukhari","Vakataka","Chalukya"], a: "C",
    e: "Vindhyashakti (c. 250–270 CE) founded the Vakataka dynasty in the Deccan region." },
  { n: 49, sec: "Medieval History", q: "Ibn Battuta's book of travels, called Rihla was originally written in:",
    o: ["Persian","Prakrit","Arabic","Urdu"], a: "C",
    e: "The 14th-century Moroccan explorer Ibn Battuta authored his celebrated travelogue, Rihla, in the Arabic language." },

  // ==================================================================
  // 03. MODERN HISTORY  —  3 questions  (Q18, Q26, Q44)
  // ==================================================================
  { n: 18, sec: "Modern History", q: "The Daroga system in 1792 was introduced by whom among the following Governor-Generals in India?",
    o: ["Lord Cornwallis","Lord Minto","Lord Mayo","Lord William Bentinck"], a: "A",
    e: "Lord Cornwallis introduced the Daroga system in 1792, establishing police circles (thanas) headed by an Indian official known as the Daroga under the District Magistrate." },
  { n: 26, sec: "Modern History", q: "The Doctrine of Lapse was an annexation policy devised by which of the following Governor-Generals of India?",
    o: ["Lord Wellesley","Lord Dalhousie","Lord Mayo","Lord Canning"], a: "B",
    e: "Lord Dalhousie (Governor-General from 1848 to 1856) vigorously enforced the Doctrine of Lapse to annex Indian princely states lacking direct natural heirs." },
  { n: 44, sec: "Modern History", q: "In which of the following areas did the Uprising of Khurda in 1817 take place?",
    o: ["United Province","Odisha","Madras","Bengal"], a: "B",
    e: "The Khurda Uprising (Paika Rebellion) of 1817 broke out in Odisha against British East India Company rule under the leadership of Bakshi Jagabandhu." },

  // ==================================================================
  // 04. INDIAN GEOGRAPHY  —  5 questions  (Q5, Q17, Q30, Q38, Q39)
  // ==================================================================
  { n: 5, sec: "Indian Geography", q: "Which of the following is an example of major industrial region of India?",
    o: ["Chota Nagpur region","Bhojpur-Munger","Jaipur-Ajmer","Bilaspur-Korba"], a: "A",
    e: "The Chota Nagpur industrial region is one of India's major industrial concentrations, renowned for heavy mineral, coal, and metallurgical plants." },
  { n: 17, sec: "Indian Geography", q: "Which of the following rivers is an East flowing river?",
    o: ["Mahi river","Narmada river","Godavari river","Tapi river"], a: "C",
    e: "The Godavari originates at Trimbakeshwar in Maharashtra and flows eastward across the Deccan Plateau into the Bay of Bengal, whereas the Narmada, Tapi, and Mahi flow west into the Arabian Sea." },
  { n: 30, sec: "Indian Geography", q: "Which region in India receives less rainfall in summer, but heavy rainfall in winter season due to the retreating North-Easterly winds?",
    o: ["Southern coastal region","Western coastal region","Northern coastal region","Eastern coastal region"], a: "D",
    e: "The eastern coastal plain (Coromandel Coast of Tamil Nadu and southern Andhra Pradesh) receives the majority of its annual precipitation from the retreating North-East monsoon during winter." },
  { n: 38, sec: "Indian Geography", q: "Which of the following statements is correct about the composition of the agriculture sector and employment in GDP post-independence?",
    o: ["The proportion of employment has declined significantly but not the share of the agriculture sector in GDP.","The proportion of both the agriculture sector and employment in GDP has increased significantly.","The proportion of both the agriculture sector and employment in GDP has declined significantly.","The proportion of GDP contributed by the agricultural sector declined significantly but not the employment depending on the agriculture sector."], a: "D",
    e: "Since 1947, agriculture's percentage contribution to India's gross domestic product (GDP) has plummeted significantly, whereas the proportion of the workforce dependent on it declined much more slowly." },
  { n: 39, sec: "Indian Geography", q: "Which port is developed as a satellite port?",
    o: ["Mormugao","Jawaharlal Nehru","Haldia","New Mangalore"], a: "B",
    e: "Jawaharlal Nehru Port (Nhava Sheva) in Navi Mumbai was commissioned in 1989 as a satellite port to decongest the Mumbai Port." },

  // ==================================================================
  // 05. WEST BENGAL GEOGRAPHY  —  0 questions
  // ==================================================================
  // (no questions from this section in this set)

  // ==================================================================
  // 06. ARTS AND CULTURE  —  6 questions  (Q2, Q7, Q19, Q36, Q41, Q48)
  // ==================================================================
  { n: 2, sec: "Arts and Culture", q: "'Padayani', a local dance form primarily performed in ________ to please Goddess Bhadrakali.",
    o: ["Assam","Kerala","Odisha","West Bengal"], a: "B",
    e: "Padayani is a ritualistic theatre dance performed in central Kerala (predominantly Pathanamthitta and Kottayam) dedicated to Goddess Bhadrakali." },
  { n: 7, sec: "Arts and Culture", q: "The renowned ghazal singer Girija Devi was born in",
    o: ["Karnataka","Bihar","Uttar Pradesh","Punjab"], a: "C",
    e: "Girija Devi, a legendary classical and semi-classical vocalist of the Benaras and Seniya gharanas, was born in Varanasi, Uttar Pradesh." },
  { n: 19, sec: "Arts and Culture", q: "Chariot festival is dedicated to Lord Jagannath along with Subhadra and",
    o: ["Balabhadra","Sudama","Hanuman","Arjuna"], a: "A",
    e: "The Puri Rath Yatra (Chariot Festival) features three grand chariots for Lord Jagannath, his elder brother Balabhadra (Balarama), and their sister Subhadra." },
  { n: 36, sec: "Arts and Culture", q: "Ranjana Gauhar was awarded the Padma Shri Award (2003) for her contribution to which of the following Indian dance forms?",
    o: ["Kuchipudi","Sattriya","Odissi","Manipuri"], a: "C",
    e: "Ranjana Gauhar is a celebrated Odissi dancer and choreographer honoured with the Padma Shri in 2003." },
  { n: 41, sec: "Arts and Culture", q: "Chhath Puja is the main festival of which state?",
    o: ["Bihar","Tamil Nadu","Karnataka","Assam"], a: "A",
    e: "Chhath Puja is an ancient Vedic festival dedicated to Surya (the Sun God) and Shashthi Devi, celebrated with immense fervour in Bihar and eastern Uttar Pradesh." },
  { n: 48, sec: "Arts and Culture", q: "'Margomkali', a ritual folk art form, is from the sate of",
    o: ["Assam","Kerala","Nagaland","Punjab"], a: "B",
    e: "Margamkali is an ancient performance and ritual folk art practiced by the Saint Thomas Christian community in Kerala." },

  // ==================================================================
  // 07. INDIAN POLITY  —  5 questions  (Q8, Q10, Q24, Q34, Q35)
  // ==================================================================
  { n: 8, sec: "Indian Polity", q: "Which of the following statements is correct with respect to the political parties in India?",
    o: ["A political party symbol is assigned by the President of India.","India has a multi-party system classified as national, state or regional level.","All parties are registered with the Supreme Court of India.","Status of party is accorded by the Parliament."], a: "B",
    e: "India maintains a multi-party democratic system where political outfits are recognized and registered by the Election Commission of India as National or State/Regional parties." },
  { n: 10, sec: "Indian Polity", q: "Which of the following is not a feature of the Constitution of India?",
    o: ["Universal Adult Franchise","Independent Judiciary","Dual Citizenship","Blend of rigidity and flexibility"], a: "C",
    e: "The Indian Constitution establishes single citizenship for all citizens across the entire union; dual citizenship is not recognized." },
  { n: 24, sec: "Indian Polity", q: "Which Indian political leader was called as Lok Nayak?",
    o: ["Ram Manohar Lohia","Jai Prakash Narayan","Bal Gangadhar Tilak","Subhas Chandra Bose"], a: "B",
    e: "Jayaprakash Narayan, leader of the Total Revolution movement, was affectionately conferred the title 'Lok Nayak' (Leader of the People)." },
  { n: 34, sec: "Indian Polity", q: "Which of the following features of the Indian Constitution was borrowed from Irish Constitution?",
    o: ["Directive Principles of State Policy","Concurrent List","Fundamental Rights","Rule of Law"], a: "A",
    e: "The Directive Principles of State Policy (DPSP) embodied in Part IV were adopted from the Constitution of Ireland." },
  { n: 35, sec: "Indian Polity", q: "The Supreme Court of India comprises the Chief Justice and not more than ________ other Judges appointed by the President of India.",
    o: ["37","35","38","33"], a: "D",
    e: "Under the Supreme Court (Number of Judges) Amendment Act, 2019, the sanctioned judicial strength is 34 (Chief Justice of India plus not more than 33 other judges). The official key marked (A) 37 in error.",
    flag: "The official answer key marks (A) 37; however, the actual statutory strength of the Supreme Court is the CJI + 33 judges (total 34)." },

  // ==================================================================
  // 08. INDIAN ECONOMY  —  3 questions  (Q1, Q9, Q20)
  // ==================================================================
  { n: 1, sec: "Indian Economy", q: "The Drought Prone Area Programme (DPAP) for providing employment to people in drought prone areas was started by the Government of India during the",
    o: ["Fourth Five-Year Plan","Sixth Five-Year Plan","Third Five-Year Plan","Seventh Five-Year Plan"], a: "A",
    e: "The Drought Prone Areas Programme (DPAP) was initiated during 1973–74 under the Fourth Five-Year Plan (1969–1974) to mitigate the adverse effects of drought." },
  { n: 9, sec: "Indian Economy", q: "How was the growth in all food grains after the Green Revolution?",
    o: ["Unitary","Proportionate","Unpredictable","Disproportionate"], a: "D",
    e: "The Green Revolution brought massive surges in wheat and rice production, while coarse cereals, millets, and pulses experienced much slower growth, resulting in disproportionate overall growth." },
  { n: 20, sec: "Indian Economy", q: "What correctly defines change of inventories of a firm during a year?",
    o: ["Production of the firm during the year - Sale of the firm during the year","Production of the firm during the previous year - Sale of the firm during the year","Sale of the firm during the year - Production of the firm during the year","Production of the firm during the year - Sale of the firm during the previous year"], a: "A",
    e: "In national income accounting, the change in inventories over an accounting period equals total production minus total sales during that year." },

  // ==================================================================
  // 09. PHYSICS  —  15 questions  (Q25, Q51, Q52, Q53, Q54, Q55, Q56, Q57, Q59, Q60, Q62, Q63, Q64, Q65, Q66, Q67)
  // ==================================================================
  { n: 25, sec: "Physics", q: "Which of the following two quantities have the same dimensions?",
    o: ["Work and torque","Power and moment of inertia","Work and angular displacement","Power and radius of circular motion"], a: "A",
    e: "Both work and torque share the dimensional formula [M L² T⁻²]." },
  { n: 51, sec: "Physics", q: "In the absence of earth's atmosphere sky would appear",
    o: ["Blue","Deep Red","White","Black"], a: "D",
    e: "Without an atmosphere, Rayleigh scattering of sunlight would not occur, making the sky appear completely black." },
  { n: 52, sec: "Physics", q: "Which is the phenomenon which established the transverse nature of light?",
    o: ["Reflection","Refraction","Diffraction","Polarization"], a: "D",
    e: "Only transverse waves can be polarized; longitudinal waves (like sound) cannot undergo polarization." },
  { n: 53, sec: "Physics", q: "Convex mirrors are used as a rear view mirror in motor cycles because--",
    o: ["It forms real image","It forms erect image","It forms smaller image as compared with object","All of the above"], a: "D",
    e: "The paper's key selects (D) All of the above, though convex mirrors always produce virtual, erect, and diminished images.",
    flag: "Official key gives (D) All of the above; note that statement (a) is technically incorrect as convex mirrors form virtual, not real images." },
  { n: 54, sec: "Physics", q: "Magnifying Glass is basically a-",
    o: ["Plano-concave lens","Concave lens","Convex lens","Cylindrical lens"], a: "C",
    e: "A simple magnifying glass consists of a biconvex lens of short focal length producing an erect, magnified, virtual image." },
  { n: 55, sec: "Physics", q: "The velocity of sound in a gas depends on-",
    o: ["Wavelength only","Density and elasticity of gas","Intensity only","Amplitude and frequency"], a: "B",
    e: "The velocity of sound in a gas is governed by Newton-Laplace formula: v = √(γP/ρ), depending directly on the elasticity and density of the medium." },
  { n: 56, sec: "Physics", q: "When a body is immersed in a fluid, then force acting on it-",
    o: ["Upward thrust","Weight","Mass","Both (a) and (b)"], a: "D",
    e: "An immersed body experiences two primary forces: its downward gravitational weight and an upward buoyant force (thrust)." },
  { n: 57, sec: "Physics", q: "Cream gets separated out from milk when it is churned. This is due to-",
    o: ["Gravitational Force","Centripetal Force","Centrifugal Force","Frictional Force"], a: "C",
    e: "Churning creates circular motion where the denser milk components are pushed outward by inertia while less dense cream particles migrate toward the center under centrifugal effects." },
  { n: 59, sec: "Physics", q: "In a rechargeable cell what kind of energy is stored within the cell?",
    o: ["Electrical energy","Potential energy","Chemical energy","Kinetic energy"], a: "C",
    e: "During charging, electrical energy is converted and stored in the form of chemical energy inside the cell's active materials." },
  { n: 60, sec: "Physics", q: "For which of the following game, players must have the knowledge of Pascal's law?",
    o: ["Climbing","Paragliding","Rafting","Scuba diving"], a: "D",
    e: "Scuba divers operate in environments governed by hydrostatic pressure principles and Pascal's law to manage equalization and lung volume." },
  { n: 62, sec: "Physics", q: "The abbreviation LHC stands for which machine?",
    o: ["Light Heat Collider","Large Hadron Collider","Long Heavy Collider","Large High Collider"], a: "B",
    e: "LHC stands for the Large Hadron Collider, the world's most powerful particle accelerator operated by CERN." },
  { n: 63, sec: "Physics", q: "Nm²kg⁻² is S.I. unit of -",
    o: ["Pressure","Momentum","Acceleration","Universal constant of gravitation"], a: "D",
    e: "From Newton's law of gravitation F = G(m1·m2)/r², the universal gravitational constant G has units of N·m²/kg²." },
  { n: 64, sec: "Physics", q: "Which instrurnent is used to detect the presence of electric charge on an object?",
    o: ["Multimeter","Electroscope","Amperemeter","Ohmmeter"], a: "B",
    e: "A gold-leaf electroscope is a classic scientific instrument used to detect the presence and sign of electrostatic charge on a body." },
  { n: 65, sec: "Physics", q: "A force of 20 N displaces an object through 2 m and does a work of 20 J. The angle between force and displacement is:",
    o: ["60°","30°","90°","0°"], a: "A",
    e: "Work = F · d · cos θ => 20 = 20 × 2 × cos θ => cos θ = 20 / 40 = 0.5 => θ = 60°." },
  { n: 66, sec: "Physics", q: "A moving car faces the wind in the opposite direction. What will be the work done by the wind on the car?",
    o: ["Negative","Zero","Infinite","Positive"], a: "A",
    e: "Because the resisting aerodynamic drag acts opposite to the direction of motion (θ = 180°), the work done by the wind is negative (cos 180° = -1)." },
  { n: 67, sec: "Physics", q: "If the work done is negative, then what will be the angle between the force and displacement?",
    o: ["45°","0°","90°","180°"], a: "D",
    e: "Work is given by W = F · s · cos θ. When θ = 180°, cos 180° = -1, yielding maximum negative work." },

  // ==================================================================
  // 10. CHEMISTRY  —  5 questions  (Q3, Q14, Q40, Q72, Q75)
  // ==================================================================
  { n: 3, sec: "Chemistry", q: "Which of the following statements are true based on 4NH₃(g) + 5O₂(g) → 4NO(g) + 6H₂O(g)? (A) N gets oxidised. (B) O gets oxidised. (C) N gets reduced. (D) O gets reduced.",
    o: ["(A) and (D)","(A) and (B)","(C) and (D)","(B) and (C)"], a: "A",
    e: "The oxidation state of nitrogen changes from -3 in NH₃ to +2 in NO (oxidation), and oxygen goes from 0 in O₂ to -2 in NO and H₂O (reduction)." },
  { n: 14, sec: "Chemistry", q: "Which number is called Avogadro's constant, named after the 19th century scientist Amedeo Avogadro?",
    o: ["6.022 × 10²³","6.020 × 10²⁰","6.032 × 10¹⁹","6.012 × 10²¹"], a: "A",
    e: "Avogadro's number represents the number of constituent particles per mole of substance, defined as 6.022 × 10²³ mol⁻¹." },
  { n: 40, sec: "Chemistry", q: "Which polyatomic ionic compound is a white, crystalline powder used in fire extinguishers and to neutralise acids and bases?",
    o: ["Sodium Bisulphite","Sodium Thiosulphate","Sodium Chromate","Sodium Bicarbonate"], a: "D",
    e: "Sodium bicarbonate (baking soda, NaHCO₃) releases carbon dioxide when heated, smothering flames in fire extinguishers, and functions as an effective buffer." },
  { n: 72, sec: "Chemistry", q: "Which of the following is/are NOT true for ionic compounds? (i) Ionic compounds have low melting and boiling points. (ii) Ionic compounds are brittle and break into pieces when pressure is applied. (iii) Ionic compounds are solids and are somewhat hard because of the strong attraction between the positive and negative ions. (iv) Ionic compounds conduct electricity in the molten state.",
    o: ["i and ii","i and iii","i and iv","Only i"], a: "D",
    e: "Statement (i) is false because ionic compounds exhibit high melting and boiling points due to strong electrostatic attractions. Statements (ii), (iii), and (iv) are true." },
  { n: 75, sec: "Chemistry", q: "Atoms / molecules / ions with equal number of electrons are called....",
    o: ["Isotonous","Isotope","Isoelectronic","Valence isoelectronic"], a: "C",
    e: "Chemical species sharing the exact same total number of electrons and identical electronic configurations are called isoelectronic species." },

  // ==================================================================
  // 11. BIOLOGY  —  8 questions  (Q13, Q15, Q27, Q32, Q58, Q68, Q69, Q70, Q71)
  // ==================================================================
  { n: 13, sec: "Biology", q: "Filtration of waste products in human happens in the kidneys. There is a large number of filtration units present inside the kidneys to help them in doing this job. These filtration units are called",
    o: ["Bowman's capsules","nephrons","capillaries","alveoli"], a: "B",
    e: "The functional microscopic structural and filtration units of the human kidney are the nephrons." },
  { n: 15, sec: "Biology", q: "Which branch of ecology deals with the characteristics of ancient environment and their relationship with ancient plants and animals?",
    o: ["Demecology","Ichthyology","Paleoecology","Mycology"], a: "C",
    e: "Paleoecology investigates the relationships between ancient organisms and the environmental conditions under which they lived using fossil records." },
  { n: 27, sec: "Biology", q: "Which of the following is a man-made ecosystem?",
    o: ["Aquarium","Dessert","Forest","Grassland"], a: "A",
    e: "An aquarium is an artificial, human-engineered aquatic ecosystem, whereas deserts, forests, and grasslands are natural ecosystems." },
  { n: 32, sec: "Biology", q: "Which of the following are the two basic categories of an ecosystem?",
    o: ["Forest and Aquatic","Terrestrial and Aquatic","Lakes and Ponds","Forest and Rivers"], a: "B",
    e: "Biosphere ecosystems are broadly classified into two main structural realms: terrestrial (land-based) and aquatic (water-based)." },
  { n: 58, sec: "Biology", q: "Solar energy is converted into chemical energy during-",
    o: ["Transpiration","Photosynthesis","Diffusion","Osmosis"], a: "B",
    e: "During photosynthesis, green plants convert radiant solar energy into chemical energy stored within glucose molecules." },
  { n: 68, sec: "Biology", q: "What type of cell division is used to repair injury in the body?",
    o: ["Mitosis only","Meiosis only","Both Mitosis and Meiosis","Neither Mitosis nor Meiosis"], a: "A",
    e: "Somatic tissue growth, wound healing, and cellular repair are accomplished exclusively through mitotic cell division (mitosis)." },
  { n: 69, sec: "Biology", q: "Which of the following stores starch, proteins and oil granules in a plant cell?",
    o: ["Protoplast","Chromoplast","Leucoplast","Chloroplast"], a: "C",
    e: "Leucoplasts are non-pigmented plastids specialized for nutrient storage: amyloplasts store starch, aleuroplasts store protein, and elaioplasts store lipids." },
  { n: 70, sec: "Biology", q: "Why do plants have low energy needs?",
    o: ["Because they produce oxygen","Because they only increase in height","Because they are self-sufficient in terms of food","Because they have a lot of dead cells"], a: "D",
    e: "Plants do not exhibit locomotion and a vast proportion of their structural supportive tissues (such as sclerenchyma, xylem tracheids, and vessels) consist of dead cells." },
  { n: 71, sec: "Biology", q: "Identify an example of a connective tissue in humans -",
    o: ["Muscles","Cells","Bones","Fibres"], a: "C",
    e: "Bone is a rigid, specialized connective tissue comprising a calcified collagenous extracellular matrix." },

  // ==================================================================
  // 12. STATIC GK  —  12 questions  (Q6, Q16, Q21, Q43, Q45, Q46, Q47, Q50, Q61, Q73, Q74)
  // ==================================================================
  { n: 6, sec: "Static GK", q: "Raja Bhalindra Singh trophy is associated with which of the following national sports events?",
    o: ["Khelo India Youth Games","Khelo India Winter Games","Khelo India University Games","National Games of India"], a: "D",
    e: "The Raja Bhalindra Singh Trophy is presented to the overall champion state contingent at the National Games of India." },
  { n: 16, sec: "Static GK", q: "Which of the following is a landlocked Salt Lake in South-West Asia between Israel and Jordan?",
    o: ["Don Juan Pond","Aral Sea","Caspian Sea","Dead Sea"], a: "D",
    e: "The Dead Sea is a hypersaline terminal lake bordered by Jordan to the east and Israel and the West Bank to the west." },
  { n: 21, sec: "Static GK", q: "Sports Authority of India comes under which ministry?",
    o: ["Ministry of Education","Ministry of Social Justice","Ministry of Health and Family Welfare","Ministry of Youth Affairs and Sports"], a: "D",
    e: "The Sports Authority of India (SAI) operates as the apex national sports body under the Ministry of Youth Affairs and Sports." },
  { n: 43, sec: "Static GK", q: "Which Indian singer wrote 'Raag Sarita'?",
    o: ["Kesarbai Kerkar","Balasaheb Poonchwale","Kumar Gandharva","Chintaman Raghunath Vyas"], a: "D",
    e: "Pandit Chintaman Raghunath Vyas (Pandit C. R. Vyas), a prominent Hindustani classical vocalist, authored the book 'Raag Sarita'." },
  { n: 45, sec: "Static GK", q: "In which of the following games is the term 'Dribbling' used?",
    o: ["Basketball","Cricket","Baseball","Volleyball"], a: "A",
    e: "Dribbling refers to the continuous bouncing or maneuvering of the ball with one hand while advancing along the court in basketball." },
  { n: 46, sec: "Static GK", q: "In which year was the Department of sports transformed into the Department of Youth Affairs and Sports?",
    o: ["1983","1982","1985","1984"], a: "C",
    e: "Initially created as the Department of Sports during the 1982 Asian Games, its designation was altered to the Department of Youth Affairs and Sports in 1985." },
  { n: 47, sec: "Static GK", q: "The number of players in baseball is:",
    o: ["8","6","9","7"], a: "C",
    e: "A standard baseball team fields 9 players on the diamond during an inning." },
  { n: 50, sec: "Static GK", q: "The much-loved English novel, 'Alice's Adventures in Wonderland' was written by which of the following authors?",
    o: ["Herman Melville","Edgar Allan Poe","Lewis Carroll","Mary Shelly"], a: "C",
    e: "The 1865 fantasy novel 'Alice's Adventures in Wonderland' was written by Charles Lutwidge Dodgson under the pseudonym Lewis Carroll." },
  { n: 61, sec: "Static GK", q: "Flight Recorder is technically called",
    o: ["Dark box","Blind box","Black box","Altitude meter"], a: "C",
    e: "An aviation flight data and cockpit voice recorder is popularly referred to as a 'black box', although it is painted bright orange for post-crash recovery." },
  { n: 73, sec: "Static GK", q: "Henri Becquerel is associated with the discovery of-",
    o: ["Genetics","Radioactivity","Inductance","Conductivity"], a: "B",
    e: "Antoine Henri Becquerel discovered spontaneous radioactivity in 1896 while investigating uranium salts, sharing the 1903 Nobel Prize in Physics." },
  { n: 74, sec: "Static GK", q: "What is Pitchblende related to?",
    o: ["Radium","Uranium","Thorium","Plutonium"], a: "B",
    e: "Pitchblende (uraninite) is a primary uranium mineral and radioactive ore consisting mainly of UO₂." },

  // ==================================================================
  // 13. CURRENT AFFAIRS  —  7 questions  (Q4, Q11, Q12, Q28, Q29, Q31, Q33, Q37)
  // ==================================================================
  { n: 4, sec: "Current Affairs", q: "Which Indian musician from Maharashtra received the Padma Vibhushan 2023?",
    o: ["Ramdas Palsule","Bharat Kamat","Zakir Hussain","Milind Date"], a: "C",
    e: "Legendary tabla maestro Ustad Zakir Hussain was conferred the Padma Vibhushan, India's second-highest civilian award, in 2023." },
  { n: 11, sec: "Current Affairs", q: "The Epidemic Diseases (Amendment) Ordinance, 2020 amended which of the following Acts?",
    o: ["The Epidemic Diseases Act, 1892","The Epidemic Diseases Act, 1895","The Epidemic Diseases Act, 1890","The Epidemic Diseases Act, 1897"], a: "D",
    e: "The Central Government promulgated the Epidemic Diseases (Amendment) Ordinance, 2020 to amend the colonial Epidemic Diseases Act, 1897 to protect healthcare personnel." },
  { n: 12, sec: "Current Affairs", q: "Under the 'Mero Rukh Mero Santati' initiative launched by the Sikkim Chief Minister Prem Singh Tamang in 2023, how many trees will be planted for every child born in Sikkim?",
    o: ["50","150","100","200"], a: "C",
    e: "Sikkim Chief Minister Prem Singh Tamang launched 'Mero Rukh Mero Santati' (Plant a Tree, Leave a Legacy), pledging to plant 100 saplings for every newborn child." },
  { n: 28, sec: "Current Affairs", q: "Who among the following famous Indian women cricketers announced retirement in June 2022?",
    o: ["Smriti Mandhana","Jhulan Goswami","Anjum Chopra","Mithali Raj"], a: "D",
    e: "Former Indian women's cricket team captain Mithali Raj announced her retirement from all formats of international cricket on June 8, 2022." },
  { n: 29, sec: "Current Affairs", q: "Which State Government honoured Vani Jairam with the MS Subbulakshmi Award for 2019?",
    o: ["Maharashtra","Karnataka","Odisha","Tamil Nadu"], a: "D",
    e: "Veteran playback singer Vani Jairam was bestowed with the M.S. Subbulakshmi Award by the state of Tamil Nadu." },
  { n: 31, sec: "Current Affairs", q: "Match the sports in List I with the sports person in List II who were in news for their sports achievement in 2022. List-I: A. Lakshya Sen, B. Rameshbabu Praggnanandhaa, C. Nikhat Zareen, D. Rudrankksh Patil. List-II: 1. Boxing, 2. Badminton, 3. Shooting, 4. Chess.",
    o: ["A-4, B-2, C-1, D-3","A-3, B-4, C-1, D-2","A-1, B-4, C-2, D-3","A-2, B-4, C-1, D-3"], a: "D",
    e: "Lakshya Sen is associated with Badminton (2), Rameshbabu Praggnanandhaa with Chess (4), Nikhat Zareen with Boxing (1), and Rudrankksh Patil with Shooting (3)." },
  { n: 33, sec: "Current Affairs", q: "For which of the following states was the Constitution (Scheduled Castes and Scheduled Tribes) Orders (Second Amendment) Bill, 2022, introduced in the Parliament?",
    o: ["Odisha","Bihar","Uttar Pradesh","Madhya Pradesh"], a: "C",
    e: "The Constitution (SC and ST) Orders (Second Amendment) Bill, 2022 was passed to recognize the Gond community and its sub-castes across four districts of Uttar Pradesh under the ST category." },
  { n: 37, sec: "Current Affairs", q: "Who won the paralympic bronze medal in archery for India at Tokyo in 2020?",
    o: ["Atanu Das","Pravin Jadhav","Deepika Kumari","Harvinder Singh"], a: "D",
    e: "Harvinder Singh created history by winning India's first-ever Paralympic medal (bronze) in archery at the Tokyo 2020 Paralympic Games." },

  // ==================================================================
  // 14. APTITUDE & MENTAL ABILITY  —  25 questions  (Q76 to Q100)
  // ==================================================================
  { n: 76, sec: "Aptitude & Mental Ability", q: "Ram and Shyam work on a job together for four days and complete 60% of it. Ram takes leave then and Shyam works for eight more days to complete the job. How long would Ram take to complete the entire job alone?",
    o: ["6 days","8 days","10 days","11 days"], a: "C",
    e: "Shyam completes remaining 40% in 8 days => Shyam does 5% per day. Together they did 60% in 4 days => 15% per day. Hence Ram alone does 15% - 5% = 10% per day. Ram needs 100/10 = 10 days." },
  { n: 77, sec: "Aptitude & Mental Ability", q: "If sin θ + cosec θ = 2, then the value of sin⁵ θ + cosec⁵ θ is",
    o: ["1/2","1","0","2"], a: "D",
    e: "sin θ + 1/sin θ = 2 => (sin θ - 1)² = 0 => sin θ = 1, cosec θ = 1. Therefore, 1⁵ + 1⁵ = 2." },
  { n: 78, sec: "Aptitude & Mental Ability", q: "W can do 25% of a work in 30 days, X can do 1/4 of the work in 10 days, Y can do 40% of the work in 40 days and Z can do 1/3 of the work in 13 days. Who will complete the work first?",
    o: ["W","X","Y","Z"], a: "D",
    e: "Total time needed: W = 30 / 0.25 = 120 days; X = 10 × 4 = 40 days; Y = 40 / 0.40 = 100 days; Z = 13 × 3 = 39 days. Z takes the least time (39 days)." },
  { n: 79, sec: "Aptitude & Mental Ability", q: "The average monthly income of a person in a certain family of 5 is Rs. 10,000. What will be the average monthly income of a person in the same family if the income of one person increased by Rs. 1,20,000 per year?",
    o: ["Rs. 12,000","Rs. 16,000","Rs. 20,000","Rs. 34,000"], a: "A",
    e: "Monthly increment to family = ₹1,20,000 / 12 = ₹10,000. Increase in per-person average = ₹10,000 / 5 = ₹2,000. New average monthly income = ₹10,000 + ₹2,000 = ₹12,000." },
  { n: 80, sec: "Aptitude & Mental Ability", q: "A person allows 10% discount for cash payment from the marked price of a toy and still he makes a 10% gain. What is the cost price of the toy which is marked Rs. 770?",
    o: ["Rs. 610","Rs. 620","Rs. 630","Rs. 640"], a: "C",
    e: "Selling Price = 90% of ₹770 = ₹693. Since SP represents a 10% profit over CP: CP = 693 / 1.10 = ₹630." },
  { n: 81, sec: "Aptitude & Mental Ability", q: "A class starts at 11:00 am and lasts till 2:27 pm. Four periods of equal duration are held during this interval. After every period, a rest of 5 minutes is given to the students. The exact duraton of each period is:",
    o: ["48 minutes","50 minutes","51 minutes","53 minutes"], a: "A",
    e: "Total elapsed time from 11:00 am to 2:27 pm = 3 hours 27 minutes = 207 minutes. There are 3 intervals between 4 periods = 3 × 5 = 15 minutes of rest. Teaching time = 207 - 15 = 192 minutes. Period length = 192 / 4 = 48 minutes." },
  { n: 82, sec: "Aptitude & Mental Ability", q: "In a class, there are 18 very tall boys. If these constitute three-fourths of the boys and the total number of boys is two-thirds of the total number of students in the class, what is the number of girls in the class?",
    o: ["6","12","18","21"], a: "B",
    e: "Number of boys = 18 / (3/4) = 24. Since boys are 2/3 of total students, total students = 24 / (2/3) = 36. Number of girls = 36 - 24 = 12." },
  { n: 83, sec: "Aptitude & Mental Ability", q: "The monthly average salary paid to all the employees of a company was Rs. 5000. The monthly average salary paid to male and female employees was Rs. 5200 and Rs. 4200 respectively. Then the percentage of males employed in the company is",
    o: ["75%","80%","85%","90%"], a: "B",
    e: "By alligation: Male (5200) vs Female (4200) with mean (5000) gives ratio (5000 - 4200) : (5200 - 5000) = 800 : 200 = 4 : 1. Male percentage = 4 / (4 + 1) × 100 = 80%." },
  { n: 84, sec: "Aptitude & Mental Ability", q: "A clock strikes once at 1o'clock, twice at 2 o'clock and thrice at 3 o'clock, and so on. If it takes 12 seconds to strike at 5 o'clock, what is the time taken by it to strike at 10 o'clock?",
    o: ["20 seconds","24 seconds","28 seconds","30 seconds"], a: "B",
    e: "The paper's key marks (B) 24 seconds assuming linear proportionality of hours (12 × 10/5 = 24 s). Technically, striking times depend on intervals: 4 intervals take 12 s (3 s/interval), so 9 intervals at 10 o'clock take 27 s.",
    flag: "Official key gives (B) 24 seconds (calculated as 12/5 × 10). Interval-based physics gives 27 seconds." },
  { n: 85, sec: "Aptitude & Mental Ability", q: "P works thrice as fast as Q, whereas P and Q together can work four times as fast as R. If P, Q and R together work on a job, in what ratio should they share the earnings?",
    o: ["3:1:1","3:2:4","4:3:4","3:1:4"], a: "A",
    e: "Let Q's rate = 1 unit/day => P's rate = 3 units/day. Combined P + Q = 4 units/day. Since P + Q = 4 × R, R's rate = 1 unit/day. Earnings ratio = 3 : 1 : 1." },
  { n: 86, sec: "Aptitude & Mental Ability", q: "A lift has the capacity of 18 adults or 30 children. How many children can board the lift with 12 adults?",
    o: ["6","10","12","15"], a: "B",
    e: "18 adults = 30 children => 1 adult = 30/18 = 5/3 children. Remaining capacity with 12 adults = 18 - 12 = 6 adults. 6 adults = 6 × (5/3) = 10 children." },
  { n: 87, sec: "Aptitude & Mental Ability", q: "A shopkeeper sells an article at Rs. 40 and gets x% profit. However, when he sells it at Rs. 20, he faces same percentage of loss. What is the original cost of the article?",
    o: ["Rs.10","Rs. 20","Rs. 30","Rs. 40"], a: "C",
    e: "Since profit % equals loss %: 40 - CP = CP - 20 => 2 CP = 60 => CP = ₹30." },
  { n: 88, sec: "Aptitude & Mental Ability", q: "A student has to get 40% marks to pass in an examination. Suppose he gets 30 marks and fails by 30 marks, then what are the maximum marks in the examination?",
    o: ["100","120","150","300"], a: "C",
    e: "Passing marks = 30 + 30 = 60. 40% of Maximum Marks = 60 => Maximum Marks = 60 / 0.40 = 150." },
  { n: 89, sec: "Aptitude & Mental Ability", q: "If √x - 1/√x = √6, then x² + 1/x² is equal to",
    o: ["62","14","16","36"], a: "A",
    e: "Squaring both sides: x + 1/x - 2 = 6 => x + 1/x = 8. Squaring again: x² + 1/x² + 2 = 64 => x² + 1/x² = 62." },
  { n: 90, sec: "Aptitude & Mental Ability", q: "If a - b = 2 and ab = 24, then what is the value of a³ - b³?",
    o: ["280","124","140","152"], a: "D",
    e: "a³ - b³ = (a - b)³ + 3ab(a - b) = (2)³ + 3(24)(2) = 8 + 144 = 152." },
  { n: 91, sec: "Aptitude & Mental Ability", q: "What is the value of sin 30° + cos 30° - tan 45°?",
    o: ["(√3 - 1) / 2","(√2 + 1) / √2","(√3 + 1) / 2","(1 - √3) / -2"], a: "A",
    e: "sin 30° = 1/2, cos 30° = √3/2, tan 45° = 1. Value = 1/2 + √3/2 - 1 = (1 + √3 - 2) / 2 = (√3 - 1) / 2." },
  { n: 92, sec: "Aptitude & Mental Ability", q: "Ms Jhulan Goswami scores 102 runs in the 18th innings of her career and thus increases her average by 5. After the 18th innings, her average is:",
    o: ["17","21","26","28"], a: "A",
    e: "Let her previous average be A. New total = 17A + 102 = 18(A + 5) => 17A + 102 = 18A + 90 => A = 12. Her new average after 18 innings = 12 + 5 = 17." },
  { n: 93, sec: "Aptitude & Mental Ability", q: "The average age of 29 boys of a class is equal to 14 years. When the age of the class teacher is included the average becomes 15 years. Find the age of the class teacher.",
    o: ["44 years","40 years","52 years","66 years"], a: "A",
    e: "Teacher's age = New total age - Previous total age = (30 × 15) - (29 × 14) = 450 - 406 = 44 years." },
  { n: 94, sec: "Aptitude & Mental Ability", q: "10 sheep and 5 pigs were brought for Rs. 6000. If the average price of a sheep is Rs. 450, find the average price of pig.",
    o: ["Rs. 380","Rs. 410","Rs. 340","Rs. 300"], a: "D",
    e: "Total cost of 10 sheep = 10 × 450 = ₹4500. Total cost of 5 pigs = 6000 - 4500 = ₹1500. Average price of a pig = 1500 / 5 = ₹300." },
  { n: 95, sec: "Aptitude & Mental Ability", q: "Of the three numbers, the first is one third of the second and twice the third. The average of these numbers is 27. The largest of these numbers is",
    o: ["18","36","54","108"], a: "C",
    e: "Let third number = x => first = 2x, second = 6x. Sum = x + 2x + 6x = 9x. Average = 9x / 3 = 3x = 27 => x = 9. Largest number = 6x = 6 × 9 = 54." },
  { n: 96, sec: "Aptitude & Mental Ability", q: "If a/b = 1/3, b/c = 1/2 and a = 2, then the value of c is-",
    o: ["8","10","12","16"], a: "C",
    e: "a/b = 1/3 with a = 2 gives b = 6. Then b/c = 1/2 with b = 6 gives c = 12." },
  { n: 97, sec: "Aptitude & Mental Ability", q: "If x/3 = y/5 = z/7, then (z² - x² + y²) / 2y² = ?",
    o: ["1.2","1.1","1.7","1.3"], a: "D",
    e: "Let x = 3k, y = 5k, z = 7k. Expression = [(7k)² - (3k)² + (5k)²] / [2(5k)²] = (49 - 9 + 25) / (2 × 25) = 65 / 50 = 1.3." },
  { n: 98, sec: "Aptitude & Mental Ability", q: "If a² + b² = 25 and ab = 12, then (a + b) / (a - b) is-",
    o: ["4","5","6","7"], a: "D",
    e: "(a + b)² = a² + b² + 2ab = 25 + 24 = 49 => a + b = 7. (a - b)² = a² + b² - 2ab = 25 - 24 = 1 => a - b = 1. Ratio = 7 / 1 = 7." },
  { n: 99, sec: "Aptitude & Mental Ability", q: "Value of (√7 - √3)(√7 + √3) is",
    o: ["2√3","3√7","4","3"], a: "C",
    e: "Using the algebraic formula (a - b)(a + b) = a² - b²: (√7)² - (√3)² = 7 - 3 = 4." },
  { n: 100, sec: "Aptitude & Mental Ability", q: "The ratio of present age of a father and his son is 7 : 2. After 5 years the age of Son will be 37.5% of that of his father. The present age of the father is-",
    o: ["35 years","42 years","49 years","28 years"], a: "A",
    e: "Let ages be 7x and 2x. (2x + 5) / (7x + 5) = 37.5 / 100 = 3/8 => 16x + 40 = 21x + 15 => 5x = 25 => x = 5. Father's present age = 7 × 5 = 35 years." },

]);