/* =====================================================================
   questions/set-03.js  —  SET-03
   ---------------------------------------------------------------------
   Add this set's questions inside the [ ... ] below, one block per question:

     { n: 1, sec: "Modern History", q: "Question text?",
       o: ["Option A", "Option B", "Option C", "Option D"],
       a: "B",                 // correct letter: A, B, C or D
       e: "Explanation text." },

   n = original question number · sec = one of the 14 section names in data.js
   (copy exactly) · e = explanation (optional) · d = "Easy"/"Medium"/"Hard" (optional)
   flag = optional warning shown in review, e.g. "Answer may be outdated"
   ===================================================================== */
// Source: West Bengal Urdu Academy Pre-Recruitment Coaching (WBUA MISC-2024 PH-I VST-3, Date: 10.09.2026). Complete: 100 questions.
// Questions with a "flag" highlight official answer key discrepancies or biological inaccuracies (Q9, Q37, Q59, Q82, Q92).

registerSet("SET-03", [

  // ==================================================================
  // 01. ANCIENT HISTORY  —  5 questions  (Q8, Q11, Q15, Q33, Q41)
  // ==================================================================
  { n: 8, sec: "Ancient History", q: "Who among the following published a set of Ashokan inscriptions in the year 1877?",
    o: ["DC Sircar","Colin Mackenzie","MS Vats","Alexander Cunningham"], a: "D",
    e: "Sir Alexander Cunningham, the first Director-General of the Archaeological Survey of India, published a comprehensive corpus of Ashokan inscriptions in 1877 under 'Corpus Inscriptionum Indicarum' (Vol. I)." },
  { n: 11, sec: "Ancient History", q: "Si-yu-ki or 'The Records of the Western World' was written by:",
    o: ["Marco Polo","Fa-Hien","Abdur Razzak","Hiuen Tsing"], a: "D",
    e: "The Buddhist pilgrim monk Hiuen Tsang (Xuanzang), who visited India during the reign of King Harshavardhana, authored 'Si-Yu-Ki'." },
  { n: 15, sec: "Ancient History", q: "The Brihadeshwara temple at Tanjore was built by ________ rulers.",
    o: ["Chola","Chandella","Pallava","Solanki"], a: "A",
    e: "The grand Brihadisvara Temple at Thanjavur (Tanjore), dedicated to Lord Shiva, was commissioned by the Chola emperor Rajaraja I and completed around 1010 CE." },
  { n: 33, sec: "Ancient History", q: "On the bank of now dry course of which river, the ancient city of Harappa was built?",
    o: ["Gandak","Ravi","Kosi","Yamuna"], a: "B",
    e: "The Indus Valley site of Harappa (now in the Sahiwal district of Punjab, Pakistan) was situated along the former course of the Ravi River." },
  { n: 41, sec: "Ancient History", q: "Who among the following was a contributor to the subject of medicine in ancient India?",
    o: ["Harsha","Bhasa","Charaka","Panini"], a: "C",
    e: "Maharshi Charaka was the ancient physician who authored the foundational medical treatise 'Charaka Samhita', dealing with internal medicine (Kayachikitsa)." },

  // ==================================================================
  // 02. MEDIEVAL HISTORY  —  4 questions  (Q32, Q68, Q69, Q73)
  // ==================================================================
  { n: 32, sec: "Medieval History", q: "Sultan Mahmud of Ghazni was a contemporary of which Chola king?",
    o: ["Rajaraja I","Rajendra II","Rajadhiraja","Rajendra I"], a: "D",
    e: "Sultan Mahmud of Ghazni (reigned 998–1030 CE) was a contemporary of the Chola king Rajendra I (reigned 1014–1044 CE)." },
  { n: 68, sec: "Medieval History", q: "Who among the following was the Vakil under the reign of Mughal Emperor, Akbar, who received the title of Khan-i-Khanan?",
    o: ["Bairam Khan","Mulla do-Piyaza","Birbal","Raja Todar Mal"], a: "A",
    e: "Bairam Khan served as the Vakil (regent and prime minister) during Akbar's minority and was honoured with the supreme title of Khan-i-Khanan." },
  { n: 69, sec: "Medieval History", q: "Who among the following was the successor of Mughal Emperor, Babur?",
    o: ["Aurangzeb","Shahjahan","Jahangir","Humayun"], a: "D",
    e: "Nasir-ud-Din Muhammad Humayun succeeded his father Babur as the second Mughal emperor in December 1530." },
  { n: 73, sec: "Medieval History", q: "The Jain temple at Pattadakal was built by",
    o: ["Chalukyas","Cholas","Rashtrakutas","Hoyasalas"], a: "C",
    e: "The 9th-century Jain Narayana temple at Pattadakal was constructed during the rule of the Rashtrakutas (attributed to the reign of Amoghavarsha I or Krishna II)." },

  // ==================================================================
  // 03. MODERN HISTORY  —  8 questions  (Q2, Q12, Q28, Q29, Q30, Q31, Q34, Q35)
  // ==================================================================
  { n: 2, sec: "Modern History", q: "Vasco da Gama, who discovered the sea route from Europe to India, belonged to which nation?",
    o: ["England","Portugal","Spain","Germany"], a: "B",
    e: "The Portuguese explorer Vasco da Gama discovered the ocean route to India, landing at Calicut (Kozhikode) in May 1498." },
  { n: 12, sec: "Modern History", q: "In which of the following languages did Jyotiba Phule write 'Gulamgiri' in 1873?",
    o: ["English","Marathi","Hindi","Gujarati"], a: "B",
    e: "Jyotirao Govindrao Phule wrote 'Gulamgiri' (Slavery) in Marathi in 1873, dedicating the work to the American abolitionist movement." },
  { n: 28, sec: "Modern History", q: "Shyamji Krishna Varma established India House at ________ in 1905.",
    o: ["New York","Bombay","Paris","London"], a: "D",
    e: "Shyamji Krishna Varma founded India House at Highgate, North London, in 1905 as a student residence and hub for Indian nationalist activities in the UK." },
  { n: 29, sec: "Modern History", q: "Who among the following was the only martyr of the Quit India phase of the freedom movement who was hanged?",
    o: ["Potti Sreeramulu","Senapati Bapat","Kushal Konwar","Kanaiyalal Maneklal Munshi"], a: "C",
    e: "Kushal Konwar, a prominent freedom fighter from Assam, was falsely implicated in a train derailment near Sarupathar and hanged on 15 June 1943 during the Quit India movement." },
  { n: 30, sec: "Modern History", q: "Who was the President of the Board of Trade when the Cabinet Mission visited India?",
    o: ["AV Alexander","Lord Wavell","Stafford Cripps","Pethick Lawrence"], a: "C",
    e: "The Cabinet Mission of 1946 consisted of three British cabinet members: Lord Pethick-Lawrence (Secretary of State for India), Sir Stafford Cripps (President of the Board of Trade), and A.V. Alexander (First Lord of the Admiralty)." },
  { n: 31, sec: "Modern History", q: "Who among the following viceroys of India made the declaration known as 'August Offer'?",
    o: ["Lord Chelmsford","Lord Linlithgow","Lord Willingdon","Lord Reading"], a: "B",
    e: "Viceroy Lord Linlithgow announced the 'August Offer' on 8 August 1940, proposing an expanded Governor-General's Executive Council and a post-war constituent body." },
  { n: 34, sec: "Modern History", q: "Tattvabodhini Patrika promoted the study of India's past in which language?",
    o: ["Sanskrit","Hindi","English","Bengali"], a: "D",
    e: "Established in 1843 by Debendranath Tagore as the mouthpiece of the Tattwabodhini Sabha, the journal was published in Bengali to foster vernacular study of India's philosophical heritage." },
  { n: 35, sec: "Modern History", q: "Who among the following stated in 1902, India was not ruled for its benefit, but rather for the benefit of its conquerors?",
    o: ["Bal Gangadhar Tilak","Lala Lajpat Rai","Annie Besant","Sarojini Naidu"], a: "C",
    e: "In 1902, Annie Besant stated during her address: 'India was not ruled for its benefit, but rather for the benefit of its conquerors'." },

  // ==================================================================
  // 04. INDIAN GEOGRAPHY  —  6 questions  (Q20, Q21, Q22, Q23, Q24, Q25)
  // ==================================================================
  { n: 20, sec: "Indian Geography", q: "Which is the colloquial term to describe the occurrence of pre-monsoon rains in India especially in parts of Kerala, Karnataka and Tamil Nadu?",
    o: ["Nor Westers","Kalbaisakhi","Orange showers","Mango showers"], a: "D",
    e: "Pre-monsoon showers across Kerala and coastal Karnataka are popularly called 'Mango Showers' because they help in the early ripening of mangoes." },
  { n: 21, sec: "Indian Geography", q: "As the river enters the plain it twists and turns forming large bends known as",
    o: ["ox-bow","levees","floodplains","meanders"], a: "D",
    e: "Upon reaching flat plains, lateral erosion causes a river to swing in sinuous, looping bends termed meanders." },
  { n: 22, sec: "Indian Geography", q: "What is the name of the river formed by the confluence of Sankh River and South Koel River at Vedvyas in Odisha?",
    o: ["Pennar","Sabarmati","Subarnarekha","Brahmani"], a: "D",
    e: "The confluence of the Sankh and South Koel rivers at Vedvyas near Rourkela forms the Brahmani River." },
  { n: 23, sec: "Indian Geography", q: "The Rabi season of agriculture begins in October-November and ends in",
    o: ["June -July","March-April","January - February","May-June"], a: "B",
    e: "Rabi crops (such as wheat, mustard, and gram) are sown during winter (October–November) and harvested in spring (March–April)." },
  { n: 24, sec: "Indian Geography", q: "Which of the following is an agro based industry?",
    o: ["Cement","Iron and Steel","Silk textile","Petrochemicals"], a: "C",
    e: "Agro-based industries derive their primary raw materials from agriculture; silk textile depends on sericulture (mulberry and silkworms)." },
  { n: 25, sec: "Indian Geography", q: "Which of the following states in India has gold deposits?",
    o: ["Karnataka","Madhya Pradesh","Tamil Nadu","Andhra Pradesh"], a: "A",
    e: "Karnataka is India's leading producer of gold, home to the Kolar Gold Fields (KGF) and the functional Hutti Gold Mines in Raichur district." },

  // ==================================================================
  // 05. WEST BENGAL GEOGRAPHY  —  1 question  (Q66)
  // ==================================================================
  { n: 66, sec: "West Bengal Geography", q: "Which of the following dams is a part of the Damodar Valley Corporation?",
    o: ["Maithon","Rihand","Koyna","Salal"], a: "A",
    e: "Maithon Dam, built across the Barakar River (a principal tributary of the Damodar), was constructed under the Damodar Valley Corporation (DVC) project." },

  // ==================================================================
  // 06. ARTS AND CULTURE  —  5 questions  (Q14, Q16, Q71, Q72, Q74)
  // ==================================================================
  { n: 14, sec: "Arts and Culture", q: "Nati is a folk dance of which of the following states?",
    o: ["Himachal Pradesh","Madhya Pradesh","Arunachal Pradesh","Andhra Pradesh"], a: "A",
    e: "Nati is the traditional group folk dance of Himachal Pradesh (notably Kullu, Kinnaur, and Shimla districts), recognized in the Guinness World Records as the largest folk dance." },
  { n: 16, sec: "Arts and Culture", q: "The festival of Navroz or nowroj is celebrated as new year of which community?",
    o: ["Buddhist","Parsi","Sindhi","Jainism"], a: "B",
    e: "Navroz (Nowruz) marks the Iranian and Zoroastrian New Year, celebrated by the Parsi community to commemorate the spring equinox." },
  { n: 71, sec: "Arts and Culture", q: "Ustad Shafaat Ahmed Khan was best known for which of the following instrument?",
    o: ["Tabla","Rudra Veena","Violin","Harmonium"], a: "A",
    e: "Ustad Shafaat Ahmed Khan was a renowned tabla maestro belonging to the Dilli gharana." },
  { n: 72, sec: "Arts and Culture", q: "Bahmani Monuments at Gulbarga, Karnataka represent ________ style of architecture.",
    o: ["Mameluke","Sikh","Deccan","Nagara"], a: "C",
    e: "The monuments erected by the Bahmani Sultanate at Gulbarga (Kalaburagi), such as the Gulbarga Fort and Jama Masjid, exemplify the Deccan style of Indo-Islamic architecture." },
  { n: 74, sec: "Arts and Culture", q: "The first printed edition of the Ramcharitmanas by Tulsidas was published from ________ in 1810.",
    o: ["Delhi","Calcutta/Kolkata","Madras/Chennai","Bombay/Mumbai"], a: "B",
    e: "The first printed illustrated edition of Goswami Tulsidas's 'Ramcharitmanas' was published from Calcutta (Kolkata) in 1810 by Babu Ram at the Sanskrit Press." },

  // ==================================================================
  // 07. INDIAN POLITY  —  3 questions  (Q44, Q49, Q70)
  // ==================================================================
  { n: 44, sec: "Indian Polity", q: "Who among the following was the first Home Minister of Independent india?",
    o: ["Sardar Vallabh Bhai Patel","Humayun Kabir","Maulana Abul Kalam Azad","Baldev Singh"], a: "A",
    e: "Sardar Vallabhbhai Patel served as the first Deputy Prime Minister and Home Minister of independent India." },
  { n: 49, sec: "Indian Polity", q: "Biological Diversity Act 2002 was passed by the Government of India. It fulfilled ideals of which article of Directive Principles of State Policy in the Constitution of India?",
    o: ["Article 49","Article 48A","Article 48","Article 47"], a: "B",
    e: "Article 48A of the Directive Principles instructs the State to protect and improve the environment and safeguard the forests and wildlife of the country." },
  { n: 70, sec: "Indian Polity", q: "Lucknow Pact was signed between :",
    o: ["the Muslim League and Mahatma Gandhi","the Indian national Congress and Arya Samaj","the Indian National Congress and the Muslim League","the Muslim League and Arya Samaj"], a: "C",
    e: "The historic Lucknow Pact of December 1916 was a joint political agreement reached between the Indian National Congress and the All-India Muslim League." },

  // ==================================================================
  // 08. INDIAN ECONOMY  —  4 questions  (Q1, Q17, Q18, Q19)
  // ==================================================================
  { n: 1, sec: "Indian Economy", q: "In which year was the Foreign Investment Board established?",
    o: ["1960","1968","1965","1991"], a: "B",
    e: "The Foreign Investment Board (FIB) was established by the Government of India in 1968 to regulate and approve foreign collaborations and investment proposals." },
  { n: 17, sec: "Indian Economy", q: "The number of deaths during the first 28 completed days of life per 1000 live births in a given year or period is defined as",
    o: ["neonatal mortality rate","age-specific mortality rate","crude mortality rate","infant mortality rate"], a: "A",
    e: "Neonatal mortality rate (NMR) is defined as the number of neonatal deaths (dying before 28 days of age) per 1,000 live births in a given period." },
  { n: 18, sec: "Indian Economy", q: "How many engines drive 'PM Gati Shakti', a project launched by the central government to revolutionise infrastructure in India?",
    o: ["Two","Seven","Nine","Four"], a: "B",
    e: "PM Gati Shakti National Master Plan is powered by seven distinct engines of growth: Roads, Railways, Airports, Ports, Mass Transport, Waterways, and Logistics Infrastructure." },
  { n: 19, sec: "Indian Economy", q: "Which of the following was the first Regional Rural Bank of India?",
    o: ["Utkarsh Bank","Vishwas Bank","Pratham Bank","Bandhan Bank"], a: "C",
    e: "Prathama Bank, established on 2 October 1975 with its head office at Moradabad (Uttar Pradesh) and sponsored by Syndicate Bank, was India's first Regional Rural Bank (RRB)." },

  // ==================================================================
  // 09. PHYSICS  —  6 questions  (Q36, Q50, Q61, Q62, Q63, Q64, Q65)
  // ==================================================================
  { n: 36, sec: "Physics", q: "Which device is used to either break electric circuit or to complete it?",
    o: ["Insulators","Wires","Switch","Bulb"], a: "C",
    e: "An electric switch is a mechanical control device that interrupts the current or diverts it from one conductor to another." },
  { n: 50, sec: "Physics", q: "The zone where the earthquake waves are not observed is called:",
    o: ["Benthic Zone","Hypocentre","Shadow Zone","Epicentre"], a: "C",
    e: "The earthquake shadow zone is an area of the Earth's surface where seismographs cannot detect direct P-waves or S-waves (e.g., S-wave shadow zone beyond 103°)." },
  { n: 61, sec: "Physics", q: "In the absence of the earth's atmosphere sky would appear",
    o: ["Blue","Deep Red","White","Black"], a: "D",
    e: "In the absence of an atmosphere, there would be no particles to scatter sunlight (Rayleigh scattering), making the sky appear completely black." },
  { n: 62, sec: "Physics", q: "A soap bubble shows colours when illuminated with white light. The is due to",
    o: ["Diffraction","Polarisation","Interference","Reflection"], a: "C",
    e: "The brilliant colours exhibited by a soap film arise from thin-film wave interference between light waves reflected from the top and bottom surfaces of the film." },
  { n: 63, sec: "Physics", q: "The Rainbow has: (Choose incorrect statement)",
    o: ["Violet light as its innermost colour towards earth","Its curvature bends towards earth","Red light as its outermost colour toward sky","Red light as its innermost colour towards earth"], a: "D",
    e: "In a primary rainbow, red light forms the outermost arc (with an angle of ~42°) and violet light forms the innermost arc (~40°). Hence statement (D) is incorrect." },
  { n: 64, sec: "Physics", q: "For a person having hypermetropia, the near point is-",
    o: ["Greater than 25 cm","Greater than 50 cm","Less than 25 cm","Infinity"], a: "A",
    e: "In hypermetropia (farsightedness), close objects cannot be seen clearly because the near point recedes farther than the normal 25 cm." },
  { n: 65, sec: "Physics", q: "A man can not see clearly beyond 10 meters. The disease he suffers from",
    o: ["Far sight","Myopia","Cataract","Hypermetropia"], a: "B",
    e: "Myopia (nearsightedness) is a refractive defect wherein distant objects appear blurred because light rays focus in front of the retina." },

  // ==================================================================
  // 10. CHEMISTRY  —  3 questions  (Q37, Q38, Q39)
  // ==================================================================
  { n: 37, sec: "Chemistry", q: "Non-polar molecules possess",
    o: ["permanent dipole moment","partial charge","no dipole moment","instantaneous dipole moment"], a: "D",
    e: "The official answer key marks (D) instantaneous dipole moment (referring to London dispersion phenomena). Non-polar molecules have zero permanent dipole moment.",
    flag: "Official key gives (D) instantaneous dipole moment (which induces London dispersion forces); classically, non-polar molecules possess no net permanent dipole moment." },
  { n: 38, sec: "Chemistry", q: "Helium gas can be converted to the liquid form by",
    o: ["hydrogen bonding interaction","London forces of attraction","dipole-induced dipole forces of attraction","dipole-dipole forces of attraction"], a: "B",
    e: "Helium atoms are non-polar noble gas atoms held together exclusively by weak London dispersion forces (induced dipole–induced dipole attractions)." },
  { n: 39, sec: "Chemistry", q: "Identify the correct chemical formula of chloroform",
    o: ["CHCl3","CH3Cl","CHCl2","CH2Cl2"], a: "A",
    e: "Chloroform is trichloromethane, possessing the chemical formula CHCl₃." },

  // ==================================================================
  // 11. BIOLOGY  —  13 questions  (Q4, Q5, Q40, Q42, Q43, Q51, Q52, Q53, Q54, Q55, Q56, Q57, Q58, Q59, Q60)
  // ==================================================================
  { n: 4, sec: "Biology", q: "________ is a practice of establishing and managing individual trees generally for amenity purposes.",
    o: ["Arboriculture","Viniculture","Floriculture","Silviculture"], a: "A",
    e: "Arboriculture is the cultivation, management, and study of individual trees, shrubs, and woody perennial plants for amenity and landscape value." },
  { n: 5, sec: "Biology", q: "What is the nut of an oak tree called?",
    o: ["Kola nut","Acorn","macadamia","Chestnut"], a: "B",
    e: "The acorn (oaknut) is the nut-like fruit of the oak tree (Quercus spp.), typically containing a single seed enclosed in a tough leathery shell." },
  { n: 40, sec: "Biology", q: "The branch of horticulture which deals with the production, storage, processing and marketing of vegetables is called",
    o: ["pomology","agronomy","olericulture","apiculture"], a: "C",
    e: "Olericulture is the science and practice of vegetable production and management. Pomology deals with fruits." },
  { n: 42, sec: "Biology", q: "What is pro-vitamin A or the anti-cancer compound present in carrots called?",
    o: ["Beta-carotene","Alpha-resins","Delta-terpenes","Alpha-terpenoid"], a: "A",
    e: "Beta-carotene is an organic orange-red carotenoid pigment abundant in carrots that serves as the dietary provitamin A precursor." },
  { n: 43, sec: "Biology", q: "The red colour of tomatoes is due to the presence of",
    o: ["limonene","lycopene","beta carotene","alizarin"], a: "B",
    e: "Lycopene is a bright red carotenoid pigment responsible for the characteristic red colour of mature tomatoes." },
  { n: 51, sec: "Biology", q: "The branch of biology dealing with the study of cells is known as-",
    o: ["Cytology","Histology","Psychology","Physiology"], a: "A",
    e: "Cytology (cellular biology) is the discipline of biological science that investigates cell structure, function, and life cycle." },
  { n: 52, sec: "Biology", q: "'Darwin finches' refers to a group of-",
    o: ["Fishes","Lizards","Birds","Amphibians"], a: "C",
    e: "Darwin's finches are a group of roughly 15 species of passerine birds endemic to the Galápagos Islands, illustrating adaptive radiation." },
  { n: 53, sec: "Biology", q: "Carbohydrate is stored in the body as-",
    o: ["Glucose","Starch","Glycogen","Sucrose"], a: "C",
    e: "In humans and animals, excess carbohydrates are stored primarily in the liver and skeletal muscles in the form of glycogen." },
  { n: 54, sec: "Biology", q: "The source of the enzyme, diastase is-",
    o: ["Salivary gland","Stomach","Liver","Pancreas"], a: "A",
    e: "Diastase (amylase), an enzyme that hydrolyzes starch into maltose, is secreted in humans by the salivary glands and the pancreas." },
  { n: 55, sec: "Biology", q: "Nitrification is the biological process of converting",
    o: ["N2 into nitrate","N2 into nitrite","Ammonia into nitrite","Ammonia into N2O"], a: "C",
    e: "Nitrification is a two-step aerobic process where ammonia is first oxidized to nitrite (by Nitrosomonas) and subsequently to nitrate (by Nitrobacter)." },
  { n: 56, sec: "Biology", q: "Which of the following statements about blood pressure is correct?",
    o: ["The normal systolic pressure is about 80 mm of Hg and diastolic pressure is 120 mm of Hg.","The normal systolic pressure is about 72 mm of Hg and diastolic pressure is 35 mm of Hg.","The normal systolic pressure is about 160 mm of Hg and diastolic pressure is 80 mm of Hg.","The normal systolic pressure is about 120 mm of Hg and diastolic pressure is 80 mm of Hg"], a: "D",
    e: "Standard healthy arterial resting blood pressure in human adults is nominally 120 mm Hg (systolic) over 80 mm Hg (diastolic)." },
  { n: 57, sec: "Biology", q: "The red blood cells are produced by the",
    o: ["Liver","Hormones","Bone marrow","Heart"], a: "C",
    e: "Erythropoiesis (the production of red blood cells) occurs primarily in the red bone marrow of flat and long bones." },
  { n: 58, sec: "Biology", q: "In following Organ, which excrete water, fat and different waste (catabolic)-",
    o: ["Kidney","Skin","Spleen","Salivary gland"], a: "A",
    e: "The kidneys are the body's primary excretory organs, filtering water, nitrogenous wastes (urea, uric acid), and metabolic by-products." },
  { n: 59, sec: "Biology", q: "In hemichordate excretion take place by the -",
    o: ["Malpighion tubule","Pronephric Kidney","Mesonephic Kidney","Postxephric Kidney"], a: "A",
    e: "The paper's key marks (A) Malpighion tubule, which is biologically inaccurate. Hemichordates actually excrete through the proboscis gland (glomerulus).",
    flag: "Official key gives (A) Malpighion tubule; however, hemichordates (such as Balanoglossus) excrete through a proboscis gland (glomerulus)." },
  { n: 60, sec: "Biology", q: "What causes the mottling of the dental enamel?",
    o: ["High levels of chlorine in water","High levels of nitrate in the water","High levels of fluorides in the water","High levels of calcium in the water"], a: "C",
    e: "Chronic ingestion of drinking water containing elevated concentrations of fluoride (> 1.5 ppm) induces dental fluorosis, manifesting as enamel mottling and discolouration." },

  // ==================================================================
  // 12. STATIC GK  —  13 questions  (Q3, Q6, Q7, Q9, Q10, Q26, Q27, Q45, Q46, Q47, Q48, Q67, Q75)
  // ==================================================================
  { n: 3, sec: "Static GK", q: "Identify the state animal of Assam.",
    o: ["Elephant","Snow Leopard","Ox","One-horned Rhino"], a: "D",
    e: "The Great Indian One-Horned Rhinoceros (Rhinoceros unicornis) is the official state animal of Assam, famously preserved at Kaziranga National Park." },
  { n: 6, sec: "Static GK", q: "In which of the following years were the first Commonwealth Games held in Canada?",
    o: ["1956","1909","1930","1912"], a: "C",
    e: "The inaugural Commonwealth Games (originally called the British Empire Games) were held in Hamilton, Ontario, Canada in August 1930." },
  { n: 7, sec: "Static GK", q: "Who among the following is the author of the book 'Abode of Love'?",
    o: ["APJ Abdul Kalam","Manmohan Singh","Shankar Dayal Sharma","Narendra Modi"], a: "D",
    e: "'Abode of Love' is a collection of eight short stories authored by Narendra Modi." },
  { n: 9, sec: "Static GK", q: "Who among the following wrote the novel 'Gora'?",
    o: ["Rabindranath Tagore","Abanindranath Tagore","Premchand","Mahatma Gandhi"], a: "A",
    e: "'Gora' is a renowned philosophical novel written by Rabindranath Tagore, published in 1910. The paper's key mistakenly printed (B) in the list but points to Rabindranath Tagore.",
    flag: "Official key list marks (B) while displaying the text for Rabindranath Tagore (A); Rabindranath Tagore wrote 'Gora'." },
  { n: 10, sec: "Static GK", q: "Who among the following is the author of the book 'Unaccustomed Earth'?",
    o: ["Arundhati Roy","Anita Nair","Jhumpa Lahiri","Shobha De"], a: "C",
    e: "'Unaccustomed Earth' is an acclaimed collection of short stories authored by Pulitzer Prize-winning author Jhumpa Lahiri, published in 2008." },
  { n: 26, sec: "Static GK", q: "Which of the following is the windiest planet in the solar system?",
    o: ["Neptune","Uranus","Saturn","Mars"], a: "A",
    e: "Neptune experiences the most extreme and violent supersonic atmospheric wind speeds in the solar system, reaching up to 2,100 km/h." },
  { n: 27, sec: "Static GK", q: "Which of the following parallels of latitude represent the Tropic of Capricorn?",
    o: ["23½º in the Northern Hemisphere","66½º in the Southern Hemisphere","23½º in the Southern Hemisphere","66½º in the Northern Hemisphere"], a: "C",
    e: "The Tropic of Capricorn is the line of latitude situated at 23.5° South of the Equator." },
  { n: 45, sec: "Static GK", q: "The renowned ghazal singer Girija Devi was born in",
    o: ["Bihar","Punjab","Karnataka","Uttar Pradesh"], a: "D",
    e: "Padma Vibhushan recipient Girija Devi was born in Varanasi, Uttar Pradesh in 1929." },
  { n: 46, sec: "Static GK", q: "Which of the following is the only rack railway in India that was declared a UNESCO World Heritage Site in 2005?",
    o: ["Nilgiri Mountain Railway","Kangra Valley Railway","Matheran Hill Railway","Kalka-Shimla Railway"], a: "A",
    e: "The Nilgiri Mountain Railway in Tamil Nadu utilizes the Abt rack and pinion system and was inscribed as a UNESCO World Heritage Site in 2005 under 'Mountain Railways of India'." },
  { n: 47, sec: "Static GK", q: "Where is the headquarters of the Badminton World Federation located?",
    o: ["Malaysia","Singapore","Switzerland","Japan"], a: "A",
    e: "The Badminton World Federation (BWF) has its international headquarters in Kuala Lumpur, Malaysia." },
  { n: 48, sec: "Static GK", q: "The term 'Libero' is used in",
    o: ["snooker","basketball","volleyball","badminton"], a: "C",
    e: "In volleyball, a 'libero' is a specialized defensive player wearing a contrasting jersey, restricted from attacking or serving." },
  { n: 67, sec: "Static GK", q: "Bawris are traditionally used for:",
    o: ["storing and recharging water","getting useful minerals","getting petroleum oil","collecting garbage"], a: "A",
    e: "Bawris (or Baolis) are traditional architectural stepwells prevalent in arid regions of western India used for rainwater harvesting and aquifer recharge." },
  { n: 75, sec: "Static GK", q: "Willy Wonka is a fictional character from the children's story book",
    o: ["Alice's Adventures in Wonderland","Charlie and the Chocolate Factory","Matilda","Charlotte's Web"], a: "B",
    e: "Willy Wonka is the eccentric candy-maker created by British author Roald Dahl in his 1964 novel 'Charlie and the Chocolate Factory'." },

  // ==================================================================
  // 13. CURRENT AFFAIRS  —  1 question  (Q13)
  // ==================================================================
  { n: 13, sec: "Current Affairs", q: "The Purple Revolution, which was launched in Jammu and Kashmir, is also known as",
    o: ["Lavender Revolution","Indigo Revolution","Orchids Revolution","Lilac Revolution"], a: "A",
    e: "The Purple Revolution initiated by the Council of Scientific and Industrial Research (CSIR) promotes commercial lavender farming across the districts of Jammu and Kashmir." },

  // ==================================================================
  // 14. APTITUDE & MENTAL ABILITY  —  25 questions  (Q76 to Q100)
  // ==================================================================
  { n: 76, sec: "Aptitude & Mental Ability", q: "A invested ₹6000 for 5 months and B ₹5000 for x months in a business. If the profit of A and B be equal, find the value of x.",
    o: ["10 months","8 months","6 months","7 months"], a: "C",
    e: "Profit ratio equals capital × time: 6000 × 5 = 5000 × x => 30000 = 5000x => x = 6 months." },
  { n: 77, sec: "Aptitude & Mental Ability", q: "Three friends P, Q and R started a business with the capitals ₹15,000, ₹10,000 and ₹25,000. But at the end of the year, they suffer a loss of ₹25,000. How much each will have to pay for the loss?",
    o: ["₹500, ₹750 and ₹1000","₹7500, ₹5000 and ₹12500","₹500, ₹750 and ₹1150","₹1000, ₹500 and ₹700"], a: "B",
    e: "Ratio of investments = 15 : 10 : 25 = 3 : 2 : 5 (total 10 parts). P's loss = (3/10) × 25000 = ₹7500; Q's loss = (2/10) × 25000 = ₹5000; R's loss = (5/10) × 25000 = ₹12500." },
  { n: 78, sec: "Aptitude & Mental Ability", q: "X, Y and Z start a business with ₹7200. After 1 year X, Y and Z get ₹60, ₹90 and ₹120 as profit. Z invests an amount",
    o: ["₹1800","₹2400","₹2700","₹3200"], a: "D",
    e: "Profit ratio = 60 : 90 : 120 = 2 : 3 : 4 (total 9 parts). Z's investment = (4/9) × ₹7200 = ₹3200." },
  { n: 79, sec: "Aptitude & Mental Ability", q: "In a business P invests ₹12,000. After some days Q joins the business and invests ₹16,000 in it. 9 months after Q joins, P and Q get same profit. Find for how many months P's money was invested in the business.",
    o: ["20 months","11 months","12 months","10 months"], a: "C",
    e: "Let P's money be invested for t months. Since Q's money is invested for 9 months: 12000 × t = 16000 × 9 => 12t = 144 => t = 12 months." },
  { n: 80, sec: "Aptitude & Mental Ability", q: "In a joint business the ratio of the capitals of three partners is 5 : 7 : 9. If the profit in the business is ₹420, then the third partner will get",
    o: ["₹100","₹140","₹180","₹200"], a: "C",
    e: "Sum of ratio terms = 5 + 7 + 9 = 21. Third partner's share = (9 / 21) × ₹420 = 9 × ₹20 = ₹180." },
  { n: 81, sec: "Aptitude & Mental Ability", q: "S and T are partners sharing profits in the ratio of 3 : 2. W admitted as a partner. The new profit sharing ratio of S, T and W is 4 : 3 : 2. Find out the sacrificing ratio.",
    o: ["3:5","7:3","5:3","3:7"], a: "B",
    e: "Sacrifice = Old Share - New Share. S sacrifices: 3/5 - 4/9 = (27 - 20) / 45 = 7/45. T sacrifices: 2/5 - 3/9 = (18 - 15) / 45 = 3/45. Sacrificing ratio = 7 : 3." },
  { n: 82, sec: "Aptitude & Mental Ability", q: "A and B are partners sharing profits in the ratio of 7 : 5. They agree to admit C, their manager into partnership, who is to get 1/6 th share in profits. He acquires his share 1/24 th from A and 1/8 th from B. Calculate the new profit sharing ratio.",
    o: ["13:11:9","13:7:4","13:11:7","13:11:5"], a: "B",
    e: "A's new share = 7/12 - 1/24 = 13/24. B's new share = 5/12 - 1/8 = (10 - 3)/24 = 7/24. C's share = 1/6 = 4/24. Ratio = 13 : 7 : 4.",
    flag: "The official key marks (B) 13:7:4, corresponding to 13/24 : 7/24 : 4/24." },
  { n: 83, sec: "Aptitude & Mental Ability", q: "A and B are in partnership sharing profits and losses in the ratio of 3 : 2. They admit C as a new partner. Calculate the new profit sharing ratio if C purchases 1/10 th share from A.",
    o: ["5:4:3","4:3:2","3:2:1","5:4:1"], a: "D",
    e: "A's new share = 3/5 - 1/10 = 5/10. B retains 2/5 = 4/10. C gets 1/10. Ratio = 5 : 4 : 1." },
  { n: 84, sec: "Aptitude & Mental Ability", q: "If 25 men can weave 120 metres of cloth in a day, how many metres of cloth will be woven by 35 men in a day?",
    o: ["170 metres","168 metres","190 metres","180 metres"], a: "B",
    e: "Output per man = 120 / 25 = 4.8 metres. Output of 35 men = 35 × 4.8 = 168 metres." },
  { n: 85, sec: "Aptitude & Mental Ability", q: "12 men can do a piece of work in 30 days. How many extra men should be engaged to do the work in 20 days?",
    o: ["8 men","6 men","10 men","15 men"], a: "B",
    e: "Total man-days = 12 × 30 = 360. Men needed for 20 days = 360 / 20 = 18 men. Additional men required = 18 - 12 = 6 men." },
  { n: 86, sec: "Aptitude & Mental Ability", q: "If 50 men do a piece of work in 12 days working 8 hours a day. How many hours a day would 60 men have to work in order to do another piece of work twice as great in 16 days?",
    o: ["10 hours a day","12 hours a day","8 hours a day","6 hours a day"], a: "A",
    e: "(M1 × D1 × H1) / W1 = (M2 × D2 × H2) / W2 => (50 × 12 × 8) / 1 = (60 × 16 × H2) / 2 => 4800 = 480 × H2 => H2 = 10 hours/day." },
  { n: 87, sec: "Aptitude & Mental Ability", q: "10 men can do a piece of work in 18 days. In how many days 12 men can do it?",
    o: ["12 days","15 days","10 days","16 days"], a: "B",
    e: "Total man-days = 10 × 18 = 180. Days for 12 men = 180 / 12 = 15 days." },
  { n: 88, sec: "Aptitude & Mental Ability", q: "By what least number must 1260 be divided to make the quotient a perfect square?",
    o: ["35","30","40","45"], a: "A",
    e: "Prime factorisation of 1260 = 2² × 3² × 5 × 7. To leave a perfect square (2² × 3² = 36), the number must be divided by 5 × 7 = 35." },
  { n: 89, sec: "Aptitude & Mental Ability", q: "The ratio of two numbers is 5 : 8 and their difference is 69. Find the numbers.",
    o: ["120, 131","150, 163","115, 184","118, 173"], a: "C",
    e: "Let the numbers be 5x and 8x. Difference = 8x - 5x = 3x = 69 => x = 23. Numbers are 5 × 23 = 115 and 8 × 23 = 184." },
  { n: 90, sec: "Aptitude & Mental Ability", q: "One litre of spirit which contains 10% of water is added to 3 litres of spirit containing 7% of water and to this mixture half a litre is added. Find the percentage of water in the final mixture",
    o: ["15%","18%","20%","22%"], a: "B",
    e: "Water in 1 L spirit = 0.10 L. Water in 3 L spirit = 3 × 0.07 = 0.21 L. Pure water added = 0.50 L. Total water = 0.10 + 0.21 + 0.50 = 0.81 L. Total volume = 1 + 3 + 0.5 = 4.5 L. Water % = (0.81 / 4.5) × 100 = 18%." },
  { n: 91, sec: "Aptitude & Mental Ability", q: "A contractor undertook to finish a road 12 km long in 350 days. But after employing 45 men for 200 days he found that only 4 km of the road had been built. How many additional men must be engaged to finish the work in the given time?",
    o: ["70 men","80 men","75 men","85 men"], a: "C",
    e: "Remaining work = 12 - 4 = 8 km in 350 - 200 = 150 days. (45 × 200) / 4 = (Total Men × 150) / 8 => 2250 = (Total Men × 150) / 8 => Total Men = (2250 × 8) / 150 = 120 men. Additional men required = 120 - 45 = 75 men." },
  { n: 92, sec: "Aptitude & Mental Ability", q: "In a joint business the capitals of P, Q and R are in the ratio 1/4 : 1/3 : 1/2. At the end of the year they make a profit of ₹3900. Find how much of the profit R will get",
    o: ["₹2000","₹1500","₹1200","₹1800"], a: "D",
    e: "Converting to whole integers by multiplying by LCM (12): ratio = 3 : 4 : 6 (total 13 parts). R's share (printed as C in question) = (6 / 13) × ₹3900 = 6 × ₹300 = ₹1800.",
    flag: "The question text prints 'C will get' instead of 'R will get'. R's share calculates to ₹1800." },
  { n: 93, sec: "Aptitude & Mental Ability", q: "When the price of rice increases 12½%, a man can get 250 gm less rice for ₹18. Find the present cost of rice per kg.",
    o: ["₹8","₹7","₹9","₹7.50"], a: "C",
    e: "12.5% of ₹18 = ₹2.25. Therefore, 250 g (0.25 kg) currently costs ₹2.25 => Present price per kg = 2.25 / 0.25 = ₹9/kg." },
  { n: 94, sec: "Aptitude & Mental Ability", q: "A man saves 20% of his income. If his expenses be increased by 35%, by what percent his income is to be raised so that he can save 10% of his income?",
    o: ["20%","30%","25%","22%"], a: "A",
    e: "Let income = 100, saving = 20, expenses = 80. New expenses = 80 × 1.35 = 108. Since new savings are 10%, new expenses equal 90% of new income: 0.90 × I = 108 => I = 120. Income must increase by (120 - 100) = 20%." },
  { n: 95, sec: "Aptitude & Mental Ability", q: "There is some loss if an article is sold at ₹120. There is same amount of profit if the article is sold of ₹140. What is the cost price of the article?",
    o: ["₹120","₹150","₹130","₹160"], a: "C",
    e: "Since loss at ₹120 equals profit at ₹140: CP - 120 = 140 - CP => 2 CP = 260 => CP = ₹130." },
  { n: 96, sec: "Aptitude & Mental Ability", q: "There is a loss of 11% if an article is sold at ₹178. At what price should it be sold to make a profit of 11%?",
    o: ["₹200","₹220","₹222","₹226"], a: "C",
    e: "89% of CP = ₹178 => CP = 178 / 0.89 = ₹200. SP for 11% profit = 200 × 1.11 = ₹222." },
  { n: 97, sec: "Aptitude & Mental Ability", q: "A sum amounts to ₹1180 in 3 years and to ₹1300 in 5 years. Find the rate of interest.",
    o: ["5%","6%","4%","8%"], a: "B",
    e: "Interest for 2 years = 1300 - 1180 = ₹120 => Interest per year = ₹60. Interest for 3 years = 3 × 60 = ₹180. Principal = 1180 - 180 = ₹1000. Rate = (60 / 1000) × 100 = 6%." },
  { n: 98, sec: "Aptitude & Mental Ability", q: "Let us calculate the number of years for which the interest of ₹600 at the rate of simple interest of 8% per annum will be ₹168.",
    o: ["5½","4½","3½","2½"], a: "C",
    e: "T = (SI × 100) / (P × R) = (168 × 100) / (600 × 8) = 16800 / 4800 = 3.5 = 3½ years." },
  { n: 99, sec: "Aptitude & Mental Ability", q: "If a principal becomes twice of its amount in 10 years, the rate of simple interest per annum is",
    o: ["5%","10%","15%","20%"], a: "B",
    e: "If P doubles, SI = P. R = (SI × 100) / (P × T) = (P × 100) / (P × 10) = 10% per annum." },
  { n: 100, sec: "Aptitude & Mental Ability", q: "The area of a triangle is equal to the area of a square whose side measures 75 meters. Find the side of the triangle whose corresponding altitude is 125 meters",
    o: ["70 m","75 m","90 m","65 m"], a: "C",
    e: "Area of square = 75 × 75 = 5625 m². Area of triangle = (1/2) × base × altitude = (1/2) × b × 125 = 5625 => b = (5625 × 2) / 125 = 45 × 2 = 90 meters." },

]);